import { ActiveCurriculumModule } from '../../types.ts';
import { getPromotedLectureById } from '../../utils/lectureLibraryCatalog.ts';
import cpGovernanceModules from '../clinical_pathology/cpGovernanceModules.json';

const lectureRef = (id: string) => {
  const lecture = getPromotedLectureById(id);
  return lecture ? { id: lecture.id, label: lecture.title } : null;
};

const refs = (ids: string[]) => ids.map(lectureRef).filter(Boolean) as NonNullable<ReturnType<typeof lectureRef>>[];

export const activeCurriculumModules: ActiveCurriculumModule[] = [
  {
    moduleId: 'foundations-surgical-pathology',
    title: 'Foundations of Surgical Pathology',
    summary: 'Boards-first orientation to specimen context, pattern recognition, and margin logic before organ-system deep dives.',
    subspecialty: 'Foundations',
    boardPriority: 'core',
    promotionState: 'staged',
    recommendedOrder: 1,
    patternFamilies: ['clear cell', 'papillary', 'spindle cell', 'small round blue cell'],
    specimenContexts: ['biopsy', 'resection', 'margin'],
    plannedAssets: ['lectures', 'tutorials', 'images', 'algorithms', 'assessment'],
    lectures: [],
    referenceFocusTerms: ['pattern recognition', 'specimen orientation', 'margin assessment'],
    tutorialTopics: ['pattern-first sign-out', 'frozen versus permanent reasoning'],
    syllabusTopics: ['general anatomic pathology principles', 'specimen handling'],
    algorithmTopics: ['diagnostic triage', 'margin workflow'],
    assessmentTopics: ['introductory unknowns', 'specimen-context drills'],
  },
  {
    moduleId: 'spindle-cell-differential',
    title: 'Spindle Cell Differential',
    summary: 'Pattern-first review of spindle cell lesions across soft tissue, sarcomatoid carcinoma, and reactive mimics.',
    subspecialty: 'Foundations',
    boardPriority: 'high-yield',
    promotionState: 'staged',
    recommendedOrder: 2,
    patternFamilies: ['spindle cell'],
    specimenContexts: ['biopsy', 'resection'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: [],
    referenceFocusTerms: ['spindle cell', 'sarcomatoid', 'nerve sheath', 'fibromatosis'],
    tutorialTopics: ['spindle cell differential', 'reactive versus neoplastic spindle lesions'],
    syllabusTopics: ['soft tissue spindle cell lesions'],
    algorithmTopics: ['spindle cell triage'],
    assessmentTopics: ['spindle cell unknown'],
  },
  {
    moduleId: 'clear-cell-differential',
    title: 'Clear Cell Differential',
    summary: 'Cross-organ clear-cell reasoning anchored to renal neoplasia and common board-relevant mimics.',
    subspecialty: 'Foundations',
    boardPriority: 'high-yield',
    promotionState: 'staged',
    recommendedOrder: 3,
    patternFamilies: ['clear cell'],
    specimenContexts: ['biopsy', 'resection'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: refs(['renal_mass_eval']),
    referenceFocusTerms: ['clear cell', 'renal', 'clear cell papillary', 'oncocytoma'],
    tutorialTopics: ['clear cell renal differential', 'clear-cell mimics'],
    syllabusTopics: ['clear cell neoplasms'],
    algorithmTopics: ['clear cell differential'],
    assessmentTopics: ['clear-cell mimic case'],
  },
  {
    moduleId: 'small-round-blue-cell-differential',
    title: 'Small Round Blue Cell Differential',
    summary: 'Compact pattern block for round-blue-cell lesions across GU, mesenchymal, neuro, and pediatric contexts.',
    subspecialty: 'Foundations',
    boardPriority: 'high-yield',
    promotionState: 'staged',
    recommendedOrder: 4,
    patternFamilies: ['small round blue cell'],
    specimenContexts: ['biopsy', 'resection'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: refs(['testicular_mass_eval', 'ioc-overview-neuropathology']),
    referenceFocusTerms: ['small round blue cell', 'seminoma', 'ewing', 'pediatric tumor'],
    tutorialTopics: ['small round blue cell differential'],
    syllabusTopics: ['small round blue cell tumors'],
    algorithmTopics: ['round blue cell triage'],
    assessmentTopics: ['small round blue cell unknown'],
  },
  {
    moduleId: 'papillary-lesion-differential',
    title: 'Papillary Lesion Differential',
    summary: 'Pattern block for papillary lesions spanning thyroid, renal, breast, gynecologic, and urothelial sites.',
    subspecialty: 'Foundations',
    boardPriority: 'high-yield',
    promotionState: 'staged',
    recommendedOrder: 5,
    patternFamilies: ['papillary'],
    specimenContexts: ['biopsy', 'resection'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: refs(['ioc-overview-breast-surgery', 'ioc-overview-endocrine-surgery', 'renal_mass_eval']),
    referenceFocusTerms: ['papillary', 'thyroid', 'breast', 'renal', 'urothelial'],
    tutorialTopics: ['papillary lesion differential'],
    syllabusTopics: ['papillary neoplasms'],
    algorithmTopics: ['papillary lesion triage'],
    assessmentTopics: ['papillary-pattern capstone'],
  },
  {
    moduleId: 'necrosis-inflammatory-mimics',
    title: 'Necrosis and Inflammatory Mimics',
    summary: 'Boards-first inflammatory mimic block covering necrosis patterns, granulomas, and tumor-versus-inflammation traps.',
    subspecialty: 'Foundations',
    boardPriority: 'high-yield',
    promotionState: 'staged',
    recommendedOrder: 6,
    patternFamilies: ['inflammatory mimic', 'necrotizing'],
    specimenContexts: ['biopsy', 'resection', 'frozen section'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: [],
    referenceFocusTerms: ['granuloma', 'necrosis', 'gpa', 'sarcoidosis', 'fungal'],
    tutorialTopics: ['granulomatous mimics', 'tumor versus inflammation traps'],
    syllabusTopics: ['inflammatory mimics', 'necrotizing lesions'],
    algorithmTopics: ['infectious versus autoimmune mimic triage'],
    assessmentTopics: ['necrosis mimic case'],
  },
  {
    moduleId: 'breast-core',
    title: 'Breast Core Module',
    summary: 'High-yield breast pathology spanning benign/reactive change, proliferative lesions, in situ disease, and invasive carcinoma.',
    subspecialty: 'Breast',
    boardPriority: 'core',
    promotionState: 'canonical',
    recommendedOrder: 7,
    patternFamilies: ['glandular', 'papillary'],
    specimenContexts: ['core biopsy', 'excision', 'sentinel lymph node'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: refs(['ioc-overview-breast-surgery']),
    referenceFocusTerms: ['breast', 'papillary', 'dcis', 'lobular', 'phyllodes'],
    tutorialTopics: ['fibroepithelial lesions', 'dcis versus lcis', 'invasive carcinoma patterns'],
    syllabusTopics: ['breast benign proliferative lesions', 'breast carcinoma', 'sentinel lymph node'],
    algorithmTopics: ['calcification workup', 'mass lesion triage', 'biomarker interpretation'],
    assessmentTopics: ['margin-focused resection case', 'sclerosing lesion mimic case'],
  },
  {
    moduleId: 'gynecologic-core',
    title: 'Gynecologic Core Module',
    summary: 'Core cervix, endometrium, ovary, and trophoblastic disease review for boards-first sign-out reasoning.',
    subspecialty: 'Gynecologic',
    boardPriority: 'core',
    promotionState: 'canonical',
    recommendedOrder: 8,
    patternFamilies: ['papillary', 'mucinous', 'clear cell'],
    specimenContexts: ['biopsy', 'hysterectomy', 'frozen section'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: refs(['ioc-overview-gynecologic-oncology']),
    referenceFocusTerms: ['ovary', 'endometrium', 'serous', 'mucinous', 'clear cell'],
    tutorialTopics: ['endometrial hyperplasia versus carcinoma', 'ovarian epithelial tumors', 'cervical squamous lesions'],
    syllabusTopics: ['endometrial pathology', 'ovarian neoplasms', 'cervical dysplasia and carcinoma'],
    algorithmTopics: ['adnexal mass triage', 'uterine bleeding differential', 'ovarian frozen section'],
    assessmentTopics: ['ovarian frozen section case', 'endometrial biopsy progression case'],
  },
  {
    moduleId: 'renal-testicular-core',
    title: 'Renal and Testicular Core Module',
    summary: 'Clear-cell, papillary, oncocytic, seminomatous, and germ-cell high-yield diagnostics anchored to the existing GU lectures.',
    subspecialty: 'Genitourinary',
    boardPriority: 'core',
    promotionState: 'canonical',
    recommendedOrder: 9,
    patternFamilies: ['clear cell', 'papillary', 'oncocytic', 'small round blue cell'],
    specimenContexts: ['biopsy', 'orchiectomy', 'resection'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: refs(['renal_mass_eval', 'testicular_mass_eval', 'testicular_who_complete_pathology', 'ioc-overview-urologic-oncology']),
    referenceFocusTerms: ['renal', 'clear cell', 'chromophobe', 'oncocytoma', 'seminoma', 'WHO testis'],
    tutorialTopics: ['renal mass differentials', 'seminoma versus NSGCT', 'stromal testicular tumors'],
    syllabusTopics: ['renal neoplasms', 'testicular germ cell tumors', 'adrenal lesions'],
    algorithmTopics: ['renal mass differential', 'testicular mass workup'],
    assessmentTopics: ['clear cell trap case', 'serologic mismatch case'],
  },
  {
    moduleId: 'lower-gu-bladder-core',
    title: 'Lower GU and Bladder Core Module',
    summary: 'High-yield bladder teaching block built around papillary grading, CIS, TURBT staging, and invasive urothelial carcinoma.',
    subspecialty: 'Genitourinary',
    boardPriority: 'high-yield',
    promotionState: 'canonical',
    recommendedOrder: 10,
    patternFamilies: ['papillary', 'urothelial', 'inflammatory mimic'],
    specimenContexts: ['TURBT', 'biopsy', 'cystectomy'],
    plannedAssets: ['algorithms', 'assessment'],
    lectures: refs(['bladder_path_core_principles', 'penile_who_complete_pathology']),
    referenceFocusTerms: ['bladder', 'urothelial carcinoma in situ', 'PUNLMP', 'BCG cystitis', 'malakoplakia', 'penile carcinoma', 'PeIN'],
    tutorialTopics: ['urothelial carcinoma', 'bladder & ureter', 'non-neoplastic cystitis', 'reactive atypia versus CIS', 'penile carcinoma'],
    syllabusTopics: ['The Urothelial Tract and Bladder', 'High Grade Urothelial Carcinoma', 'Low Grade Urothelial Neoplasm (LGUN)'],
    algorithmTopics: ['urothelial neoplasms', 'papillary grading and invasion assessment'],
    assessmentTopics: ['TURBT staging case', 'reactive atypia versus CIS'],
  },
  {
    moduleId: 'upper-gi-staged',
    title: 'Upper GI Staged Module',
    summary: 'Staged upper GI pathway for esophagus and stomach boards review while the lecture layer is still being built out.',
    subspecialty: 'Gastrointestinal',
    boardPriority: 'high-yield',
    promotionState: 'staged',
    recommendedOrder: 10.5,
    patternFamilies: ['glandular', 'inflammatory mimic', 'dysplasia'],
    specimenContexts: ['biopsy', 'resection'],
    plannedAssets: ['lectures', 'tutorials', 'images', 'algorithms', 'assessment'],
    lectures: [],
    referenceFocusTerms: ['esophagus', 'barrett esophagus', 'gastric dysplasia', 'upper gi biopsy'],
    tutorialTopics: ["Barrett's esophagus and esophageal malignancy", 'upper gi dysplasia'],
    syllabusTopics: ['esophagus', 'stomach', 'barrett esophagus'],
    algorithmTopics: ['upper gi biopsy triage', 'barrett dysplasia workflow'],
    assessmentTopics: ['upper gi dysplasia case'],
  },
  {
    moduleId: 'colorectal-staged',
    title: 'Colorectal Staged Module',
    summary: 'Staged colorectal block for inflammatory bowel disease, polyps, cancer syndromes, and lower GI biopsy reasoning.',
    subspecialty: 'Gastrointestinal',
    boardPriority: 'high-yield',
    promotionState: 'staged',
    recommendedOrder: 10.6,
    patternFamilies: ['glandular', 'inflammatory mimic', 'polyp'],
    specimenContexts: ['biopsy', 'resection'],
    plannedAssets: ['lectures', 'tutorials', 'images', 'algorithms', 'assessment'],
    lectures: [],
    referenceFocusTerms: ['colon', 'colorectal', 'polyps', 'IBD', 'appendix'],
    tutorialTopics: ['colon pathology', 'ibd polyps and cancer syndromes'],
    syllabusTopics: ['colon', 'appendix', 'familial colorectal cancer syndromes'],
    algorithmTopics: ['polyp triage', 'lower gi biopsy workflow'],
    assessmentTopics: ['colorectal polyp case', 'ibd dysplasia case'],
  },
  {
    moduleId: 'hpb-pancreas-core',
    title: 'Hepatobiliary and Pancreatic Core Module',
    summary: 'Liver mass, cholangiocarcinoma, PDAC, and pancreatic core-principles review in one learner-facing block.',
    subspecialty: 'Hepatobiliary & Pancreatic',
    boardPriority: 'core',
    promotionState: 'canonical',
    recommendedOrder: 11,
    patternFamilies: ['glandular', 'mucinous', 'neuroendocrine'],
    specimenContexts: ['biopsy', 'resection', 'margin'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: refs(['ioc-overview-hepatobiliary-surgery', 'ioc-overview-pancreatic-surgery']),
    referenceFocusTerms: ['liver', 'pancreas', 'cholangiocarcinoma', 'pdac', 'neuroendocrine'],
    tutorialTopics: ['liver mass differentials', 'pancreatic cystic lesions', 'pdac versus chronic pancreatitis'],
    syllabusTopics: ['hepatocellular lesions', 'biliary neoplasia', 'pancreatic neoplasms'],
    algorithmTopics: ['liver mass triage', 'pancreatic cyst algorithm'],
    assessmentTopics: ['whipple margin case', 'liver biopsy pattern case'],
  },
  {
    moduleId: 'thoracic-core',
    title: 'Thoracic Core Module',
    summary: 'Lung carcinoma, pleural, and inflammatory mimic coverage oriented around the promoted lung core-principles lecture.',
    subspecialty: 'Thoracic',
    boardPriority: 'core',
    promotionState: 'canonical',
    recommendedOrder: 12,
    patternFamilies: ['glandular', 'neuroendocrine', 'inflammatory mimic'],
    specimenContexts: ['biopsy', 'resection', 'pleural specimen'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: refs(['ioc-overview-thoracic-surgery']),
    referenceFocusTerms: ['lung', 'adenocarcinoma', 'small cell', 'carcinoid', 'granuloma'],
    tutorialTopics: ['lung carcinoma patterns', 'pleural differentials', 'inflammatory mimics'],
    syllabusTopics: ['lung carcinoma', 'pleural pathology', 'granulomatous mimics'],
    algorithmTopics: ['lung nodule differential', 'neuroendocrine triage'],
    assessmentTopics: ['thoracic capstone', 'artifact versus permanent case'],
  },
  {
    moduleId: 'head-neck-endocrine-core',
    title: 'Head & Neck / Endocrine Core Module',
    summary: 'Integrated salivary, thyroid, neck node, and endocrine sign-out pathway built around the promoted H&N and thyroid lectures.',
    subspecialty: 'Head & Neck / Endocrine',
    boardPriority: 'core',
    promotionState: 'canonical',
    recommendedOrder: 13,
    patternFamilies: ['papillary', 'oncocytic', 'lymphoid interface'],
    specimenContexts: ['biopsy', 'thyroidectomy', 'neck dissection'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: refs(['ioc-overview-head-neck-surgery', 'ioc-overview-endocrine-surgery']),
    referenceFocusTerms: ['thyroid', 'papillary thyroid carcinoma', 'salivary', 'warthin', 'mucoepidermoid'],
    tutorialTopics: ['salivary gland tumors', 'thyroid follicular-patterned lesions', 'neck node differentials'],
    syllabusTopics: ['salivary gland pathology', 'thyroid neoplasms', 'head and neck squamous lesions'],
    algorithmTopics: ['thyroid nodule triage', 'salivary differential'],
    assessmentTopics: ['thyroid caution case', 'salivary/neck node capstone'],
  },
  {
    moduleId: 'skin-melanocytic-staged',
    title: 'Skin / Melanocytic Staged Module',
    summary: 'Staged image-first dermatopathology block covering melanocytic, keratinocytic, and adnexal differentials while dedicated lecture content is still incomplete.',
    subspecialty: 'Skin / Melanocytic',
    boardPriority: 'advanced',
    promotionState: 'staged',
    recommendedOrder: 13.5,
    patternFamilies: ['melanocytic', 'pagetoid', 'squamoid'],
    specimenContexts: ['shave biopsy', 'punch biopsy', 'wide excision'],
    plannedAssets: ['lectures', 'tutorials', 'images', 'algorithms', 'assessment'],
    lectures: [],
    referenceFocusTerms: ['melanoma', 'nevus', 'spitz', 'pagetoid spread', 'adnexal'],
    tutorialTopics: ['melanocytic differential', 'spitz versus melanoma', 'keratinocytic atypia'],
    syllabusTopics: ['melanocytic lesions', 'keratinocytic lesions', 'adnexal tumors'],
    algorithmTopics: ['melanocytic lesion triage', 'skin biopsy margin workflow'],
    assessmentTopics: ['melanocytic unknown', 'pagetoid differential drill'],
  },
  {
    moduleId: 'soft-tissue-bone-core',
    title: 'Soft Tissue / Bone Core Module',
    summary: 'Spindle-cell, bone-forming, and small-round-blue-cell pattern review staged for the active app curriculum.',
    subspecialty: 'Soft Tissue / Bone',
    boardPriority: 'high-yield',
    promotionState: 'staged',
    recommendedOrder: 14,
    patternFamilies: ['spindle cell', 'bone-cartilage', 'small round blue cell'],
    specimenContexts: ['biopsy', 'resection'],
    plannedAssets: ['lectures', 'tutorials', 'images', 'algorithms', 'assessment'],
    lectures: [],
    referenceFocusTerms: ['spindle cell', 'bone', 'cartilage', 'lipomatous'],
    tutorialTopics: ['spindle cell differential', 'bone-forming lesions', 'small round blue cell tumors'],
    syllabusTopics: ['soft tissue tumors', 'bone tumors'],
    algorithmTopics: ['spindle cell differential', 'bone lesion triage'],
    assessmentTopics: ['mesenchymal capstone'],
  },
  {
    moduleId: 'neuropathology-core',
    title: 'Neuropathology Core Module',
    summary: 'Compact CNS boards review focused on glioma, meningioma, and metastasis-versus-primary reasoning.',
    subspecialty: 'Neuropathology',
    boardPriority: 'high-yield',
    promotionState: 'canonical',
    recommendedOrder: 15,
    patternFamilies: ['small round blue cell', 'glandular'],
    specimenContexts: ['biopsy', 'resection', 'crush prep'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: refs(['ioc-overview-neuropathology']),
    referenceFocusTerms: ['glioma', 'meningioma', 'cns', 'metastasis'],
    tutorialTopics: ['glioma grading', 'meningioma', 'metastasis versus primary cns'],
    syllabusTopics: ['central nervous system tumors'],
    algorithmTopics: ['cns lesion differential'],
    assessmentTopics: ['crush-prep versus frozen case'],
  },
  {
    moduleId: 'pediatric-placental-staged',
    title: 'Pediatric / Placental Staged Module',
    summary: 'Staged pediatric and placental pathway for developmental, trophoblastic, and small-round-blue-cell review before a dedicated lecture layer is promoted.',
    subspecialty: 'Pediatric / Placental',
    boardPriority: 'advanced',
    promotionState: 'staged',
    recommendedOrder: 15.5,
    patternFamilies: ['small round blue cell', 'placental', 'developmental'],
    specimenContexts: ['placenta', 'biopsy', 'resection'],
    plannedAssets: ['lectures', 'tutorials', 'images', 'algorithms', 'assessment'],
    lectures: [],
    referenceFocusTerms: ['placenta', 'trophoblastic disease', 'pediatric tumor', 'wilms', 'neuroblastoma'],
    tutorialTopics: ['placental pathology essentials', 'pediatric small round blue cell differential', 'trophoblastic disease review'],
    syllabusTopics: ['placental pathology', 'pediatric tumors', 'gestational trophoblastic disease'],
    algorithmTopics: ['placental lesion triage', 'pediatric tumor differential'],
    assessmentTopics: ['placental-pattern unknown', 'pediatric round-blue-cell case'],
  },
  {
    moduleId: 'clinical-path-foundations',
    title: 'Clinical Pathology Foundations',
    summary: 'CP lab-correlation, transfusion, coagulation, and hematology framing retained inside the broader pathology curriculum shell.',
    subspecialty: 'Clinical Pathology',
    boardPriority: 'core',
    promotionState: 'canonical',
    recommendedOrder: 16,
    patternFamilies: ['hematology', 'coagulation', 'transfusion medicine'],
    specimenContexts: ['peripheral smear', 'bone marrow', 'blood bank triage'],
    plannedAssets: ['lectures', 'tutorials', 'images', 'algorithms', 'assessment'],
    lectures: [],
    referenceFocusTerms: ['hematology', 'coagulation', 'transfusion', 'microbiology', 'clinical chemistry'],
    tutorialTopics: ['Clinical Microbiology Methods and AST Studio', 'Chemical Pathology Endocrine and Metabolic Studio', 'DAT and Hemolytic Transfusion Reaction Studio'],
    syllabusTopics: ['hematology', 'coagulation', 'transfusion medicine', 'microbiology', 'chemical pathology'],
    algorithmTopics: ['anemia workup', 'bleeding diathesis triage', 'specimen-to-result CP workflow'],
    assessmentTopics: ['cp foundations review'],
    cpGovernance: cpGovernanceModules['clinical-path-foundations'],
  },
  {
    moduleId: 'hematology-red-cell-core',
    title: 'Hematology and Red Cell Disorders',
    summary: 'Canonical CP block for hemolysis, PNH, sickle-cell disease, anemia triage, flow-linked pattern recognition, and marrow-linked red-cell reasoning.',
    subspecialty: 'Clinical Pathology',
    boardPriority: 'core',
    promotionState: 'canonical',
    recommendedOrder: 17,
    patternFamilies: ['hematology', 'red cell disorder'],
    specimenContexts: ['peripheral smear', 'bone marrow', 'lab workup'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: [],
    referenceFocusTerms: ['hematology', 'anemia', 'hemolysis', 'peripheral smear', 'bone marrow', 'flow cytometry'],
    tutorialTopics: ['Flow Cytometry and Hematopathology Studio', 'paroxysmal nocturnal hemoglobinuria', 'anemia in oncology patients', 'drug induced hemolytic anemia'],
    syllabusTopics: ['hematology', 'anemia', 'hemolysis', 'hematopathology'],
    algorithmTopics: ['anemia workup', 'hemolysis triage', 'flow-based hematopathology triage'],
    assessmentTopics: ['hemolytic anemia workup', 'marrow-linked anemia case'],
    cpGovernance: cpGovernanceModules['hematology-red-cell-core'],
  },
  {
    moduleId: 'coagulation-hemostasis-core',
    title: 'Coagulation and Hemostasis Core',
    summary: 'Canonical CP block for bleeding, thrombosis, inhibitors, platelet dysfunction, and perioperative coagulation reasoning.',
    subspecialty: 'Clinical Pathology',
    boardPriority: 'core',
    promotionState: 'canonical',
    recommendedOrder: 18,
    patternFamilies: ['coagulation', 'hematology'],
    specimenContexts: ['lab workup', 'consult triage', 'perioperative testing'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: [],
    referenceFocusTerms: ['coagulation', 'hemostasis', 'platelet', 'bleeding', 'thrombosis'],
    tutorialTopics: ['bleeding from coagulation defects', 'immune thrombocytopenia', 'acquired coagulation inhibitors'],
    syllabusTopics: ['coagulation', 'hemostasis', 'platelet disorders'],
    algorithmTopics: ['bleeding diathesis triage', 'coagulation test interpretation'],
    assessmentTopics: ['coagulation mixing study case', 'platelet dysfunction review'],
    cpGovernance: cpGovernanceModules['coagulation-hemostasis-core'],
  },
  {
    moduleId: 'transfusion-cellular-therapy-core',
    title: 'Transfusion and Cellular Therapy Core',
    summary: 'Canonical CP block for blood-bank practice, transfusion reactions, platelet support, HLA matching, and cellular therapy complications.',
    subspecialty: 'Clinical Pathology',
    boardPriority: 'core',
    promotionState: 'canonical',
    recommendedOrder: 19,
    patternFamilies: ['transfusion medicine', 'hematology'],
    specimenContexts: ['blood bank triage', 'transfusion reaction', 'crossmatch'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: [],
    referenceFocusTerms: ['transfusion', 'blood bank', 'HLA', 'platelet', 'crossmatch'],
    tutorialTopics: ['DAT and Hemolytic Transfusion Reaction Studio', 'blood banking transfusion medicine', 'platelet count increment', 'HLA antigens and alleles'],
    syllabusTopics: ['transfusion medicine', 'HLA', 'cellular therapy'],
    algorithmTopics: ['transfusion reaction triage', 'crossmatch workup'],
    assessmentTopics: ['transfusion reaction workup', 'crossmatch discrepancy case'],
    cpGovernance: cpGovernanceModules['transfusion-cellular-therapy-core'],
  },
  {
    moduleId: 'clinical-microbiology-core',
    title: 'Clinical Microbiology Core',
    summary: 'Canonical CP block for specimen-to-bench workflow, organism identification, susceptibility testing, and communication of clinically actionable microbiology results.',
    subspecialty: 'Clinical Pathology',
    boardPriority: 'core',
    promotionState: 'canonical',
    recommendedOrder: 20,
    patternFamilies: ['microbiology', 'bacteriology', 'susceptibility testing'],
    specimenContexts: ['culture plate', 'gram stain', 'molecular assay', 'antibiogram'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: [],
    referenceFocusTerms: ['microbiology', 'gram stain', 'culture', 'AST', 'MALDI-TOF'],
    tutorialTopics: ['Clinical Microbiology Methods and AST Studio', 'Case Tutorial: Medical Microbiology', 'Antimicrobial Susceptibility Testing: A Case Tutorial'],
    syllabusTopics: ['microbiology', 'bacteriology', 'mycology', 'virology', 'parasitology'],
    algorithmTopics: ['specimen quality triage', 'organism identification workflow', 'AST interpretation'],
    assessmentTopics: ['microbiology bench interpretation', 'susceptibility reporting case'],
    cpGovernance: cpGovernanceModules['clinical-microbiology-core'],
  },
  {
    moduleId: 'chemical-pathology-core',
    title: 'Chemical Pathology Core',
    summary: 'Canonical CP block for clinical biochemistry, endocrine-metabolic interpretation, method awareness, and consult-level chemistry reasoning.',
    subspecialty: 'Clinical Pathology',
    boardPriority: 'core',
    promotionState: 'canonical',
    recommendedOrder: 21,
    patternFamilies: ['chemical pathology', 'clinical chemistry', 'endocrine-metabolic'],
    specimenContexts: ['chemistry panel', 'QC review', 'endocrine assay', 'metabolic profile'],
    plannedAssets: ['tutorials', 'images', 'algorithms', 'assessment'],
    lectures: [],
    referenceFocusTerms: ['chemical pathology', 'clinical chemistry', 'endocrine', 'metabolic', 'QC'],
    tutorialTopics: ['Chemical Pathology Endocrine and Metabolic Studio', 'Immune Recognition and Lipid Metabolism Studio', 'Chemical Pathology: Advanced Clinical Biochemistry Dossier'],
    syllabusTopics: ['chemical pathology', 'clinical biochemistry', 'quality control'],
    algorithmTopics: ['critical chemistry result triage', 'endocrine-metabolic interpretation', 'QC and method issue triage'],
    assessmentTopics: ['clinical chemistry interpretation', 'assay interference and metabolic pattern case'],
    cpGovernance: cpGovernanceModules['chemical-pathology-core'],
  },
];

export const activeCurriculumSubspecialties = [
  'Foundations',
  'Clinical Pathology',
  'Breast',
  'Gynecologic',
  'Genitourinary',
  'Gastrointestinal',
  'Hepatobiliary & Pancreatic',
  'Thoracic',
  'Head & Neck / Endocrine',
  'Skin / Melanocytic',
  'Soft Tissue / Bone',
  'Neuropathology',
  'Pediatric / Placental',
] as const;
