export const RAW_NODES = [
  // --- BST ENTITIES ---
  { id: "SFT", type: "entity", group: "Fibroblastic", locations: ["Extremities", "Pleura", "Orbit"] },
  { id: "Solitary Fibrous Tumor", type: "entity", group: "Fibroblastic", locations: ["Extremities", "Pleura", "Orbit"] }, // Alias
  { id: "Myxofibrosarcoma", type: "entity", group: "Fibroblastic", locations: ["Extremities", "Trunk"] },
  { id: "LGFMS", type: "entity", group: "Fibroblastic", locations: ["Extremities", "Trunk"] },
  { id: "Low-grade Fibromyxoid Sarcoma", type: "entity", group: "Fibroblastic", locations: ["Extremities", "Trunk"] }, // Alias
  { id: "Desmoid Fibromatosis", type: "entity", group: "Fibroblastic", locations: ["Abdominal Wall", "Extremities", "Intra-abdominal"] },
  { id: "WDLPS", type: "entity", group: "Adipocytic", locations: ["Retroperitoneum", "Extremities"] },
  { id: "Well-differentiated Liposarcoma", type: "entity", group: "Adipocytic", locations: ["Retroperitoneum", "Extremities"] }, // Alias
  { id: "DDLPS", type: "entity", group: "Adipocytic", locations: ["Retroperitoneum"] },
  { id: "Dedifferentiated Liposarcoma", type: "entity", group: "Adipocytic", locations: ["Retroperitoneum"] }, // Alias
  { id: "Myxoid Liposarcoma", type: "entity", group: "Adipocytic", locations: ["Extremities"] },
  { id: "Pleomorphic Liposarcoma", type: "entity", group: "Adipocytic", locations: ["Extremities"] },
  { id: "MPNST", type: "entity", group: "Nerve Sheath", locations: ["Extremities", "Trunk"] },
  { id: "Schwannoma", type: "entity", group: "Nerve Sheath", locations: ["Any"] },
  { id: "Neurofibroma", type: "entity", group: "Nerve Sheath", locations: ["Skin", "Soft Tissue"] },
  { id: "Granular Cell Tumor", type: "entity", group: "Nerve Sheath", locations: ["Skin", "Tongue", "Soft Tissue"] },
  { id: "Synovial Sarcoma", type: "entity", group: "Uncertain", locations: ["Extremities (Deep)"] },
  { id: "Epithelioid Sarcoma", type: "entity", group: "Uncertain", locations: ["Distal Extremities", "Proximally"] },
  { id: "Alveolar Soft Part Sarcoma", type: "entity", group: "Uncertain", locations: ["Extremities (Deep)", "Head & Neck"] },
  { id: "Clear Cell Sarcoma", type: "entity", group: "Uncertain", locations: ["Extremities (Tendons)"] },
  { id: "Angiosarcoma", type: "entity", group: "Vascular", locations: ["Skin", "Soft Tissue", "Breast", "Liver"] },
  { id: "Kaposi Sarcoma", type: "entity", group: "Vascular", locations: ["Skin", "Visceral"] },
  { id: "EHE", type: "entity", group: "Vascular", locations: ["Soft Tissue", "Bone", "Liver", "Lung"] },
  { id: "Leiomyosarcoma", type: "entity", group: "Smooth Muscle", locations: ["Retroperitoneum", "Uterus", "Vascular"] },
  { id: "Rhabdomyosarcoma", type: "entity", group: "Skeletal Muscle", locations: ["Head & Neck", "GU", "Extremities"] },
  { id: "GIST", type: "entity", group: "Gastrointestinal", locations: ["GI Tract", "Abdomen"] },
  { id: "Ewing Sarcoma", type: "entity", group: "Undifferentiated", locations: ["Bone", "Soft Tissue"] },
  { id: "UPS", type: "entity", group: "Undifferentiated", locations: ["Extremities", "Retroperitoneum"] },
  { id: "Undifferentiated Pleomorphic Sarcoma", type: "entity", group: "Undifferentiated", locations: ["Extremities", "Retroperitoneum"] }, // Alias
  { id: "Osteosarcoma", type: "entity", group: "Bone", locations: ["Bone"] },
  { id: "Chondrosarcoma", type: "entity", group: "Bone", locations: ["Bone"] },
  { id: "Chordoma", type: "entity", group: "Bone", locations: ["Axial Skeleton"] },
  { id: "Giant Cell Tumor", type: "entity", group: "Bone", locations: ["Epiphysis"] },
  { id: "Giant Cell Tumor of Bone", type: "entity", group: "Bone", locations: ["Epiphysis"] }, // Alias
  { id: "LCH", type: "entity", group: "Histiocytic", locations: ["Bone", "Skin"] },

  // --- BST ENTITIES ---
  { id: "SFT", type: "entity", group: "Fibroblastic", locations: ["Extremities", "Pleura", "Orbit"] },
  { id: "Myxofibrosarcoma", type: "entity", group: "Fibroblastic", locations: ["Extremities", "Trunk"] },
  { id: "LGFMS", type: "entity", group: "Fibroblastic", locations: ["Extremities", "Trunk"] },
  { id: "Desmoid Fibromatosis", type: "entity", group: "Fibroblastic", locations: ["Abdominal Wall", "Extremities", "Intra-abdominal"] },
  { id: "WDLPS", type: "entity", group: "Adipocytic", locations: ["Retroperitoneum", "Extremities"] },
  { id: "DDLPS", type: "entity", group: "Adipocytic", locations: ["Retroperitoneum"] },
  { id: "Myxoid Liposarcoma", type: "entity", group: "Adipocytic", locations: ["Extremities"] },
  { id: "Pleomorphic Liposarcoma", type: "entity", group: "Adipocytic", locations: ["Extremities"] },
  { id: "MPNST", type: "entity", group: "Nerve Sheath", locations: ["Extremities", "Trunk"] },
  { id: "Schwannoma", type: "entity", group: "Nerve Sheath", locations: ["Any"] },
  { id: "Neurofibroma", type: "entity", group: "Nerve Sheath", locations: ["Skin", "Soft Tissue"] },
  { id: "Granular Cell Tumor", type: "entity", group: "Nerve Sheath", locations: ["Skin", "Tongue", "Soft Tissue"] },
  { id: "Synovial Sarcoma", type: "entity", group: "Uncertain", locations: ["Extremities (Deep)"] },
  { id: "Epithelioid Sarcoma", type: "entity", group: "Uncertain", locations: ["Distal Extremities", "Proximally"] },
  { id: "Alveolar Soft Part Sarcoma", type: "entity", group: "Uncertain", locations: ["Extremities (Deep)", "Head & Neck"] },
  { id: "Clear Cell Sarcoma", type: "entity", group: "Uncertain", locations: ["Extremities (Tendons)"] },
  { id: "Angiosarcoma", type: "entity", group: "Vascular", locations: ["Skin", "Soft Tissue", "Breast", "Liver"] },
  { id: "Kaposi Sarcoma", type: "entity", group: "Vascular", locations: ["Skin", "Visceral"] },
  { id: "EHE", type: "entity", group: "Vascular", locations: ["Soft Tissue", "Bone", "Liver", "Lung"] },
  { id: "Leiomyosarcoma", type: "entity", group: "Smooth Muscle", locations: ["Retroperitoneum", "Uterus", "Vascular"] },
  { id: "Rhabdomyosarcoma", type: "entity", group: "Skeletal Muscle", locations: ["Head & Neck", "GU", "Extremities"] },
  { id: "GIST", type: "entity", group: "Gastrointestinal", locations: ["GI Tract", "Abdomen"] },
  { id: "Ewing Sarcoma", type: "entity", group: "Undifferentiated", locations: ["Bone", "Soft Tissue"] },
  { id: "UPS", type: "entity", group: "Undifferentiated", locations: ["Extremities", "Retroperitoneum"] },
  { id: "Osteosarcoma", type: "entity", group: "Bone", locations: ["Bone"] },
  { id: "Chondrosarcoma", type: "entity", group: "Bone", locations: ["Bone"] },
  { id: "Chordoma", type: "entity", group: "Bone", locations: ["Axial Skeleton"] },
  { id: "Giant Cell Tumor", type: "entity", group: "Bone", locations: ["Epiphysis"] },
  { id: "LCH", type: "entity", group: "Histiocytic", locations: ["Bone", "Skin"] },

  // --- NEW BST ADDITIONS ---
  { id: "Osteochondroma", type: "entity", group: "Bone", locations: ["Metaphysis"] },
  { id: "Enchondroma", type: "entity", group: "Bone", locations: ["Hands", "Feet"] },
  { id: "NOF", type: "entity", group: "Bone", locations: ["Knee"] },
  { id: "Plasma Cell Myeloma", type: "entity", group: "Bone", locations: ["Axial Skeleton"] },
  { id: "TGCT", type: "entity", group: "Fibrohistiocytic", locations: ["Joints", "Fingers"] },
  { id: "Nodular Fasciitis", type: "entity", group: "Fibroblastic", locations: ["Forearm", "Trunk"] },
  { id: "Intramuscular Myxoma", type: "entity", group: "Myxoid", locations: ["Thigh", "Shoulder"] },
  { id: "Angiolipoma", type: "entity", group: "Adipocytic", locations: ["Forearm", "Trunk"] },
  { id: "Glomus Tumor", type: "entity", group: "Pericytic", locations: ["Fingers"] },

  // --- NEW BONE/SOFT TISSUE EXPANSION ---
  { id: "Osteoid Osteoma", type: "entity", group: "Bone", locations: ["Femur", "Tibia"] },
  { id: "Osteoblastoma", type: "entity", group: "Bone", locations: ["Vertebra", "Long Bones"] },
  { id: "Chondromyxoid Fibroma", type: "entity", group: "Bone", locations: ["Metaphysis"] },
  { id: "ABC", type: "entity", group: "Bone", locations: ["Metaphysis"] },
  { id: "UBC", type: "entity", group: "Bone", locations: ["Humerus", "Femur"] },
  { id: "Fibrous Dysplasia", type: "entity", group: "Bone", locations: ["Rib", "Femur", "Craniofacial"] },
  { id: "Adamantinoma", type: "entity", group: "Bone", locations: ["Tibia"] },
  { id: "Metastatic Carcinoma", type: "entity", group: "Bone", locations: ["Axial Skeleton", "Ribs"] },
  { id: "Lipoma", type: "entity", group: "Adipocytic", locations: ["Subcutis", "Trunk"] },
  { id: "Angioleiomyoma", type: "entity", group: "Pericytic", locations: ["Leg", "Ankle"] },
  { id: "Elastofibroma", type: "entity", group: "Fibroblastic", locations: ["Back", "Subscapular"] },
  { id: "EMC", type: "entity", group: "Chondro-osseous", locations: ["Thigh", "Knee"] },

  // --- DERMPATH ENTITIES ---
  { id: "Melanoma", type: "entity", group: "Melanocytic", locations: ["Skin"] },
  { id: "Nevus", type: "entity", group: "Melanocytic", locations: ["Skin"] },
  { id: "Spitz Nevus", type: "entity", group: "Melanocytic", locations: ["Skin"] },
  { id: "Blue Nevus", type: "entity", group: "Melanocytic", locations: ["Skin"] },
  { id: "BCC", type: "entity", group: "Basaloid", locations: ["Skin (Sun-exposed)"] },
  { id: "SCC", type: "entity", group: "Squamous", locations: ["Skin (Sun-exposed)"] },
  { id: "Merkel Cell Ca", type: "entity", group: "Neuroendocrine", locations: ["Skin"] },
  { id: "DFSP", type: "entity", group: "Fibroblastic", locations: ["Skin", "Trunk"] },
  { id: "AFX", type: "entity", group: "Fibrohistiocytic", locations: ["Skin (Sun-exposed)"] },
  { id: "Sebaceous Ca", type: "entity", group: "Adnexal", locations: ["Head & Neck"] },

  // --- NEW DERMPATH ADDITIONS ---
  { id: "Dermatofibroma", type: "entity", group: "Fibrohistiocytic", locations: ["Legs", "Arms"] },
  { id: "Seborrheic Keratosis", type: "entity", group: "Basaloid", locations: ["Skin"] },
  { id: "Pyogenic Granuloma", type: "entity", group: "Vascular", locations: ["Fingers", "Face"] },
  { id: "Neurofibroma (Skin)", type: "entity", group: "Nerve Sheath", locations: ["Skin"] },
  { id: "Mycosis Fungoides", type: "entity", group: "Lymphoid", locations: ["Skin"] },
  { id: "Keratoacanthoma", type: "entity", group: "Squamous", locations: ["Skin (Sun-exposed)"] },

  // --- NEW DERMPATH EXPANSION ---
  { id: "Epidermal Inclusion Cyst", type: "entity", group: "Cystic", locations: ["Back", "Face"] },
  { id: "Verruca Vulgaris", type: "entity", group: "Squamous", locations: ["Hands", "Feet"] },
  { id: "Actinic Keratosis", type: "entity", group: "Squamous", locations: ["Face", "Hands"] },
  { id: "Pilomatricoma", type: "entity", group: "Adnexal", locations: ["Head & Neck", "Arm"] },
  { id: "Trichoepithelioma", type: "entity", group: "Adnexal", locations: ["Face"] },
  { id: "Sebaceous Adenoma", type: "entity", group: "Adnexal", locations: ["Face", "Trunk"] },

  // --- GYN ENTITIES ---
  { id: "Endometrioid Carcinoma", type: "entity", group: "Epithelial GYN", locations: ["Uterus", "Ovary"] },
  { id: "Serous Carcinoma", type: "entity", group: "Epithelial GYN", locations: ["Uterus", "Ovary", "Fallopian Tube"] },
  { id: "Clear Cell Carcinoma", type: "entity", group: "Epithelial GYN", locations: ["Uterus", "Ovary"] },
  { id: "Mucinous Carcinoma", type: "entity", group: "Epithelial GYN", locations: ["Ovary", "Uterus (rare)"] },
  { id: "HGSC", type: "entity", group: "Epithelial GYN", locations: ["Ovary", "Fallopian Tube", "Peritoneum"] },
  { id: "LGSC", type: "entity", group: "Epithelial GYN", locations: ["Ovary"] },
  { id: "Borderline Tumor", type: "entity", group: "Epithelial GYN", locations: ["Ovary"] },
  { id: "Uterine Leiomyosarcoma", type: "entity", group: "Mesenchymal GYN", locations: ["Uterus"] },
  { id: "Endometrial Stromal Sarcoma (LG)", type: "entity", group: "Mesenchymal GYN", locations: ["Uterus"] },
  { id: "High-grade Endometrial Stromal Sarcoma", type: "entity", group: "Mesenchymal GYN", locations: ["Uterus"] },
  { id: "Adenosarcoma", type: "entity", group: "Mesenchymal GYN", locations: ["Uterus", "Ovary"] },
  { id: "STUMP", type: "entity", group: "Mesenchymal GYN", locations: ["Uterus"] },
  { id: "PEComa (GYN)", type: "entity", group: "Mesenchymal GYN", locations: ["Uterus"] },
  { id: "Adult Granulosa Cell Tumor", type: "entity", group: "Sex Cord", locations: ["Ovary"] },
  { id: "Sertoli-Leydig Cell Tumor", type: "entity", group: "Sex Cord", locations: ["Ovary"] },
  { id: "Fibroma/Thecoma", type: "entity", group: "Sex Cord", locations: ["Ovary"] },
  { id: "Dysgerminoma", type: "entity", group: "Germ Cell", locations: ["Ovary"] },
  { id: "Yolk Sac Tumor", type: "entity", group: "Germ Cell", locations: ["Ovary"] },
  { id: "Vulvar SCC", type: "entity", group: "Squamous", locations: ["Vulva"] },
  { id: "Extramammary Paget Disease", type: "entity", group: "Epithelial GYN", locations: ["Vulva"] },
  { id: "STIC", type: "entity", group: "Epithelial GYN", locations: ["Fallopian Tube"] },
  { id: "SCCOHT", type: "entity", group: "Rare GYN", locations: ["Ovary"] },
  { id: "FATWO", type: "entity", group: "Rare GYN", locations: ["Adnexa", "Broad Ligament"] },
  { id: "Aggressive Angiomyxoma", type: "entity", group: "Mesenchymal GYN", locations: ["Vulva", "Perineum", "Pelvis"] },
  { id: "PSTT", type: "entity", group: "Trophoblastic", locations: ["Uterus"] },
  { id: "ETT", type: "entity", group: "Trophoblastic", locations: ["Uterus", "Cervix"] },
  { id: "Struma Ovarii", type: "entity", group: "Germ Cell", locations: ["Ovary"] },
  { id: "Gonadoblastoma", type: "entity", group: "Germ Cell", locations: ["Ovary"] },
  { id: "UTROSCT", type: "entity", group: "Sex Cord", locations: ["Uterus"] },
  { id: "LAMN", type: "entity", group: "GI/Metastatic", locations: ["Appendix", "Ovary"] },
  { id: "Cervical SCC", type: "entity", group: "Cervical", locations: ["Cervix"] },
  { id: "Endocervical Adeno HPV+", type: "entity", group: "Cervical", locations: ["Cervix"] },
  { id: "Gastric-type Adeno", type: "entity", group: "Cervical", locations: ["Cervix"] },
  { id: "Adenoid Cystic Ca", type: "entity", group: "Cervical", locations: ["Cervix", "Vulva"] },
  { id: "Mesonephric-like Adeno", type: "entity", group: "Epithelial GYN", locations: ["Uterus", "Ovary"] },
  { id: "HSIL", type: "entity", group: "Cervical", locations: ["Cervix"] },
  { id: "dVIN", type: "entity", group: "Vulvar", locations: ["Vulva"] },
  { id: "Steroid Cell Tumor", type: "entity", group: "Sex Cord", locations: ["Ovary"] },
  { id: "Leydig Cell Tumor", type: "entity", group: "Sex Cord", locations: ["Ovary"] },
  { id: "Sertoli Cell Tumor", type: "entity", group: "Sex Cord", locations: ["Ovary"] },
  { id: "Endometriosis", type: "entity", group: "Non-Neoplastic", locations: ["Ovary", "Peritoneum", "Uterus"] },
  { id: "Adenomyosis", type: "entity", group: "Non-Neoplastic", locations: ["Uterus"] },
  { id: "Massive Ovarian Edema", type: "entity", group: "Non-Neoplastic", locations: ["Ovary"] },
  { id: "Luteoma of Pregnancy", type: "entity", group: "Non-Neoplastic", locations: ["Ovary"] },
  { id: "Hyperreactio Luteinalis", type: "entity", group: "Non-Neoplastic", locations: ["Ovary"] },
  { id: "Placental Site Nodule", type: "entity", group: "Non-Neoplastic", locations: ["Uterus"] },
  { id: "Lichen Sclerosus", type: "entity", group: "Non-Neoplastic", locations: ["Vulva"] },
  { id: "Tubo-Ovarian Abscess", type: "entity", group: "Infectious", locations: ["Adnexa"] },
  { id: "Hydrosalpinx", type: "entity", group: "Non-Neoplastic", locations: ["Fallopian Tube"] },
  { id: "Decidualized Endometrioma", type: "entity", group: "Non-Neoplastic", locations: ["Ovary"] },
  { id: "MGH", type: "entity", group: "Non-Neoplastic", locations: ["Cervix"] },
  { id: "Tunneled Clusters", type: "entity", group: "Non-Neoplastic", locations: ["Cervix"] },
  { id: "Endocervical Polyp", type: "entity", group: "Non-Neoplastic", locations: ["Cervix"] },
  { id: "Nabothian Cyst", type: "entity", group: "Non-Neoplastic", locations: ["Cervix"] },
  { id: "Condyloma", type: "entity", group: "Infectious", locations: ["Vulva", "Cervix"] },
  { id: "Lichen Planus", type: "entity", group: "Non-Neoplastic", locations: ["Vulva"] },
  { id: "Lichen Simplex Chronicus", type: "entity", group: "Non-Neoplastic", locations: ["Vulva"] },
  { id: "Arias-Stella", type: "entity", group: "Non-Neoplastic", locations: ["Cervix", "Endometrium"] },
  { id: "Tubal Metaplasia", type: "entity", group: "Non-Neoplastic", locations: ["Cervix", "Endometrium"] },
  { id: "Walthard Cell Rest", type: "entity", group: "Non-Neoplastic", locations: ["Fallopian Tube"] },
  { id: "VAIN", type: "entity", group: "Vaginal", locations: ["Vagina"] },
  { id: "Vaginal SCC", type: "entity", group: "Vaginal", locations: ["Vagina"] },
  { id: "Vaginal Adenosis", type: "entity", group: "Vaginal", locations: ["Vagina"] },
  { id: "Clear Cell Ca (Vagina)", type: "entity", group: "Vaginal", locations: ["Vagina"] },
  { id: "Vaginal Melanoma", type: "entity", group: "Vaginal", locations: ["Vagina"] },
  { id: "Botryoid RMS", type: "entity", group: "Vaginal", locations: ["Vagina", "Cervix"] },
  { id: "Fibroepithelial Polyp", type: "entity", group: "Vaginal", locations: ["Vagina", "Vulva"] },
  { id: "Spindle Cell Epithelioma", type: "entity", group: "Vaginal", locations: ["Vagina"] },
  { id: "Yolk Sac Tumor (Vagina)", type: "entity", group: "Vaginal", locations: ["Vagina"] },

  // --- NEW NEOPLASTIC GYN EXPANSION ---
  { id: "Adenomatoid Tumor", type: "entity", group: "Mesothelial", locations: ["Uterus", "Fallopian Tube"] },
  { id: "Cotyledonoid Dissecting Leiomyoma", type: "entity", group: "Mesenchymal GYN", locations: ["Uterus", "Pelvis"] },
  { id: "Intravenous Leiomyomatosis", type: "entity", group: "Mesenchymal GYN", locations: ["Uterus", "Pelvic Veins", "Heart"] },
  { id: "Sclerosing Stromal Tumor", type: "entity", group: "Sex Cord", locations: ["Ovary"] },
  { id: "Papillary Hidradenoma", type: "entity", group: "Adnexal", locations: ["Vulva", "Labia"] },
  { id: "Brenner Tumor", type: "entity", group: "Epithelial GYN", locations: ["Ovary"] },
  { id: "Endometrial Stromal Nodule", type: "entity", group: "Mesenchymal GYN", locations: ["Uterus"] },
  { id: "Seromucinous Borderline Tumor", type: "entity", group: "Epithelial GYN", locations: ["Ovary"] },
  { id: "Malignant PEComa", type: "entity", group: "Mesenchymal GYN", locations: ["Uterus"] },
  { id: "Large Cell Neuroendocrine Ca", type: "entity", group: "Cervical", locations: ["Cervix"] },

  // --- NEW NON-NEOPLASTIC GYN EXPANSION ---
  { id: "Endosalpingiosis", type: "entity", group: "Non-Neoplastic", locations: ["Peritoneum", "Lymph Node"] },
  { id: "Mesothelial Hyperplasia", type: "entity", group: "Non-Neoplastic", locations: ["Peritoneum", "Hernia Sac"] },
  { id: "Postoperative Spindle Cell Nodule", type: "entity", group: "Non-Neoplastic", locations: ["Vagina", "Cervix"] },
  { id: "Ligneous Cervicitis", type: "entity", group: "Non-Neoplastic", locations: ["Cervix"] },
  { id: "Malakoplakia", type: "entity", group: "Infectious", locations: ["Vagina", "Cervix", "Endometrium"] },
  { id: "Xanthogranulomatous Inflammation", type: "entity", group: "Inflammatory", locations: ["Endometrium", "Fallopian Tube"] },
  { id: "Zoon's Vulvitis", type: "entity", group: "Inflammatory", locations: ["Vulva"] },
  { id: "Mesonephric Remnants", type: "entity", group: "Non-Neoplastic", locations: ["Cervix", "Broad Ligament"] },
  { id: "Amputation Neuroma", type: "entity", group: "Non-Neoplastic", locations: ["Cervix", "Vagina"] },
  { id: "Cervical Deciduosis", type: "entity", group: "Non-Neoplastic", locations: ["Cervix"] },

  // --- BREAST ---
  { id: "Fat Necrosis (Breast)", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Granulomatous Mastitis", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Fibroadenoma", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Phyllodes Tumor", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "DCIS", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Invasive Ductal Carcinoma", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Invasive Lobular Carcinoma", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Tubular Carcinoma", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Mucinous Carcinoma (Breast)", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Metaplastic Carcinoma", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "PASH", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Medullary Carcinoma", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Secretory Carcinoma", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "LCIS", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "ADH", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "FEA", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Radial Scar", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Lactating Adenoma", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Nipple Adenoma", type: "entity", group: "Breast", locations: ["Nipple"] },
  { id: "Inflammatory Carcinoma", type: "entity", group: "Breast", locations: ["Breast", "Skin"] },
  { id: "Encapsulated Papillary Carcinoma", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Intraductal Papilloma", type: "entity", group: "Breast", locations: ["Breast"] },
  { id: "Paget Disease (Breast)", type: "entity", group: "Breast", locations: ["Nipple", "Breast"] },

  // --- GU (Kidney, Bladder, Prostate, Testis) ---
  { id: "Clear Cell RCC", type: "entity", group: "Kidney", locations: ["Kidney"] },
  { id: "Papillary RCC", type: "entity", group: "Kidney", locations: ["Kidney"] },
  { id: "Chromophobe RCC", type: "entity", group: "Kidney", locations: ["Kidney"] },
  { id: "Oncocytoma", type: "entity", group: "Kidney", locations: ["Kidney"] },
  { id: "Angiomyolipoma", type: "entity", group: "Kidney", locations: ["Kidney"] },
  { id: "Wilms Tumor", type: "entity", group: "Kidney", locations: ["Kidney"] },
  { id: "Metanephric Adenoma", type: "entity", group: "Kidney", locations: ["Kidney"] },
  { id: "Clear Cell Sarcoma of Kidney", type: "entity", group: "Kidney", locations: ["Kidney"] },
  { id: "Rhabdoid Tumor (Kidney)", type: "entity", group: "Kidney", locations: ["Kidney"] },
  { id: "Xanthogranulomatous Pyelonephritis", type: "entity", group: "Kidney", locations: ["Kidney"] },
  { id: "Malakoplakia (Kidney)", type: "entity", group: "Kidney", locations: ["Kidney", "Bladder"] },
  { id: "Urothelial Carcinoma", type: "entity", group: "Bladder", locations: ["Bladder", "Ureter", "Renal Pelvis"] },
  { id: "Urothelial CIS", type: "entity", group: "Bladder", locations: ["Bladder"] },
  { id: "Squamous Cell Ca (Bladder)", type: "entity", group: "Bladder", locations: ["Bladder"] },
  { id: "Inverted Papilloma", type: "entity", group: "Bladder", locations: ["Bladder"] },
  { id: "Nephrogenic Adenoma", type: "entity", group: "Bladder", locations: ["Bladder", "Ureter"] },
  { id: "Cystitis Cystica", type: "entity", group: "Bladder", locations: ["Bladder"] },
  { id: "Prostate Adenocarcinoma", type: "entity", group: "Prostate", locations: ["Prostate"] },
  { id: "Prostatic Duct Adeno", type: "entity", group: "Prostate", locations: ["Prostate"] },
  { id: "PIN", type: "entity", group: "Prostate", locations: ["Prostate"] },
  { id: "ASAP", type: "entity", group: "Prostate", locations: ["Prostate"] },
  { id: "Basal Cell Hyperplasia", type: "entity", group: "Prostate", locations: ["Prostate"] },
  { id: "Seminoma", type: "entity", group: "Testis", locations: ["Testis"] },
  { id: "Embryonal Carcinoma (Testis)", type: "entity", group: "Testis", locations: ["Testis"] },
  { id: "Yolk Sac Tumor (Testis)", type: "entity", group: "Testis", locations: ["Testis"] },
  { id: "Leydig Cell Tumor (Testis)", type: "entity", group: "Testis", locations: ["Testis"] },
  { id: "Spermatocytic Tumor", type: "entity", group: "Testis", locations: ["Testis"] },
  { id: "Teratoma (Testis)", type: "entity", group: "Testis", locations: ["Testis"] },
  { id: "Sertoli Cell Tumor (Testis)", type: "entity", group: "Testis", locations: ["Testis"] },
  { id: "Adenomatoid Tumor (Epididymis)", type: "entity", group: "Testis", locations: ["Testis", "Paratesticular"] },

  // --- THORACIC (Lung, Mediastinum) ---
  { id: "Lung Adenocarcinoma", type: "entity", group: "Lung", locations: ["Lung"] },
  { id: "Lung Squamous Cell Ca", type: "entity", group: "Lung", locations: ["Lung"] },
  { id: "Small Cell Lung Ca", type: "entity", group: "Lung", locations: ["Lung"] },
  { id: "Large Cell Neuroendocrine Ca (Lung)", type: "entity", group: "Lung", locations: ["Lung"] },
  { id: "Lung Carcinoid", type: "entity", group: "Lung", locations: ["Lung"] },
  { id: "Hamartoma (Lung)", type: "entity", group: "Lung", locations: ["Lung"] },
  { id: "Solitary Fibrous Tumor (Pleura)", type: "entity", group: "Pleura", locations: ["Pleura"] },
  { id: "Organizing Pneumonia", type: "entity", group: "Lung", locations: ["Lung"] },
  { id: "UIP", type: "entity", group: "Lung", locations: ["Lung"] },
  { id: "Sarcoidosis", type: "entity", group: "Lung", locations: ["Lung", "Mediastinum"] },
  { id: "Thymoma", type: "entity", group: "Mediastinum", locations: ["Mediastinum"] },
  { id: "Thymic Carcinoma", type: "entity", group: "Mediastinum", locations: ["Mediastinum"] },
  { id: "Mediastinal Germ Cell Tumor", type: "entity", group: "Mediastinum", locations: ["Mediastinum"] },
  { id: "Mediastinal Lymphoma", type: "entity", group: "Mediastinum", locations: ["Mediastinum"] },
  { id: "Mesothelioma", type: "entity", group: "Pleura", locations: ["Pleura"] },

  // --- GI (Esophagus, Stomach, Colon, Liver, Pancreas) ---
  { id: "Barrett Esophagus", type: "entity", group: "GI", locations: ["Esophagus"] },
  { id: "Esophageal Adenocarcinoma", type: "entity", group: "GI", locations: ["Esophagus"] },
  { id: "Gastric Adenocarcinoma", type: "entity", group: "GI", locations: ["Stomach"] },
  { id: "Chronic Gastritis", type: "entity", group: "GI", locations: ["Stomach"] },
  { id: "Fundic Gland Polyp", type: "entity", group: "GI", locations: ["Stomach"] },
  { id: "Hyperplastic Polyp", type: "entity", group: "GI", locations: ["Stomach", "Colon"] },
  { id: "Gastric Neuroendocrine Tumor", type: "entity", group: "GI", locations: ["Stomach"] },
  { id: "Colonic Adenocarcinoma", type: "entity", group: "GI", locations: ["Colon", "Rectum"] },
  { id: "Sessile Serrated Lesion", type: "entity", group: "GI", locations: ["Colon"] },
  { id: "Tubular Adenoma", type: "entity", group: "GI", locations: ["Colon"] },
  { id: "Tubulovillous Adenoma", type: "entity", group: "GI", locations: ["Colon"] },
  { id: "Neuroendocrine Tumor (GI)", type: "entity", group: "GI", locations: ["Stomach", "Colon", "Small Bowel"] },
  { id: "IBD", type: "entity", group: "GI", locations: ["Colon", "Small Bowel"] },
  { id: "Peutz-Jeghers Polyp", type: "entity", group: "GI", locations: ["Small Bowel", "Colon"] },
  { id: "Juvenile Polyp", type: "entity", group: "GI", locations: ["Colon"] },
  { id: "Hepatocellular Carcinoma", type: "entity", group: "Liver", locations: ["Liver"] },
  { id: "Cholangiocarcinoma", type: "entity", group: "Liver", locations: ["Liver", "Bile Duct"] },
  { id: "Hepatic Adenoma", type: "entity", group: "Liver", locations: ["Liver"] },
  { id: "Focal Nodular Hyperplasia", type: "entity", group: "Liver", locations: ["Liver"] },
  { id: "Metastatic Carcinoma to Liver", type: "entity", group: "Liver", locations: ["Liver"] },
  { id: "Pancreatic Ductal Adeno", type: "entity", group: "Pancreas", locations: ["Pancreas"] },
  { id: "Pancreatic Neuroendocrine", type: "entity", group: "Pancreas", locations: ["Pancreas"] },
  { id: "Solid Pseudopapillary Neoplasm", type: "entity", group: "Pancreas", locations: ["Pancreas"] },
  { id: "Acinar Cell Carcinoma", type: "entity", group: "Pancreas", locations: ["Pancreas"] },
  { id: "IPMN", type: "entity", group: "Pancreas", locations: ["Pancreas"] },
  { id: "Serous Cystadenoma", type: "entity", group: "Pancreas", locations: ["Pancreas"] },
  { id: "Mucinous Cystic Neoplasm", type: "entity", group: "Pancreas", locations: ["Pancreas"] },

  // --- NEURO (CNS) ---
  { id: "Glioblastoma", type: "entity", group: "CNS", locations: ["Brain"] },
  { id: "Meningioma", type: "entity", group: "CNS", locations: ["Brain", "Spine"] },
  { id: "Oligodendroglioma", type: "entity", group: "CNS", locations: ["Brain"] },
  { id: "Ependymoma", type: "entity", group: "CNS", locations: ["Brain", "Spine"] },
  { id: "Medulloblastoma", type: "entity", group: "CNS", locations: ["Brain"] },
  { id: "Pilocytic Astrocytoma", type: "entity", group: "CNS", locations: ["Brain"] },
  { id: "Astrocytoma", type: "entity", group: "CNS", locations: ["Brain", "Spine"] },
  { id: "Schwannoma (CNS)", type: "entity", group: "CNS", locations: ["Brain", "Spine"] },
  { id: "Hemangioblastoma", type: "entity", group: "CNS", locations: ["Brain", "Spine"] },
  { id: "Craniopharyngioma", type: "entity", group: "CNS", locations: ["Brain"] },
  { id: "Pituitary Adenoma", type: "entity", group: "CNS", locations: ["Brain"] },
  { id: "Metastatic Carcinoma to Brain", type: "entity", group: "CNS", locations: ["Brain"] },
  { id: "Primary CNS Lymphoma", type: "entity", group: "CNS", locations: ["Brain"] },
  { id: "PCNSL", type: "entity", group: "CNS", locations: ["Brain"] }, // Alias

  // --- HEAD & NECK ---
  { id: "Pleomorphic Adenoma", type: "entity", group: "Salivary", locations: ["Parotid", "Salivary Gland"] },
  { id: "Warthin Tumor", type: "entity", group: "Salivary", locations: ["Parotid"] },
  { id: "Mucoepidermoid Carcinoma", type: "entity", group: "Salivary", locations: ["Salivary Gland"] },
  { id: "Adenoid Cystic Ca (Salivary)", type: "entity", group: "Salivary", locations: ["Salivary Gland"] },
  { id: "Acinic Cell Carcinoma", type: "entity", group: "Salivary", locations: ["Salivary Gland"] },
  { id: "Salivary Duct Carcinoma", type: "entity", group: "Salivary", locations: ["Salivary Gland"] },
  { id: "Papillary Thyroid Ca", type: "entity", group: "Thyroid", locations: ["Thyroid"] },
  { id: "Follicular Thyroid Ca", type: "entity", group: "Thyroid", locations: ["Thyroid"] },
  { id: "Medullary Thyroid Ca", type: "entity", group: "Thyroid", locations: ["Thyroid"] },
  { id: "Anaplastic Thyroid Ca", type: "entity", group: "Thyroid", locations: ["Thyroid"] },
  { id: "Follicular Adenoma", type: "entity", group: "Thyroid", locations: ["Thyroid"] },
  { id: "Hashimoto Thyroiditis", type: "entity", group: "Thyroid", locations: ["Thyroid"] },
  { id: "Graves Disease", type: "entity", group: "Thyroid", locations: ["Thyroid"] },
  { id: "Nasopharyngeal Carcinoma", type: "entity", group: "Head & Neck", locations: ["Nasopharynx"] },
  { id: "Sinonasal Papilloma", type: "entity", group: "Head & Neck", locations: ["Sinonasal"] },
  { id: "Olfactory Neuroblastoma", type: "entity", group: "Head & Neck", locations: ["Sinonasal"] },
  { id: "Paraganglioma", type: "entity", group: "Head & Neck", locations: ["Neck", "Carotid Body"] },
  { id: "Squamous Cell Ca (Head & Neck)", type: "entity", group: "Head & Neck", locations: ["Oral Cavity", "Larynx"] },

  // --- FEATURES (MORPH/IHC/MOL) ---
  { id: "CD34", type: "ihc", desc: "Vascular/Fibroblastic" },
  { id: "S100", type: "ihc", desc: "Neural/Melanocytic" },
  { id: "SOX10", type: "ihc", desc: "Neural/Melanocytic" },
  { id: "SMA", type: "ihc", desc: "Smooth Muscle/Myofibroblastic" },
  { id: "Desmin", type: "ihc", desc: "Muscle" },
  { id: "Myogenin", type: "ihc", desc: "Skeletal Muscle" },
  { id: "Keratin", type: "ihc", desc: "Epithelial" },
  { id: "MDM2", type: "molecular", desc: "Amplified in WDLPS/DDLPS" },
  { id: "CDK4", type: "ihc", desc: "Amplified in WDLPS/DDLPS" },
  { id: "STAT6", type: "ihc", desc: "Nuclear in SFT" },
  { id: "TLE1", type: "ihc", desc: "Synovial Sarcoma" },
  { id: "H3K27me3", type: "ihc", desc: "Loss in MPNST" },
  { id: "Beta-Catenin", type: "ihc", desc: "Nuclear in Desmoid" },
  { id: "MUC4", type: "ihc", desc: "LGFMS/SEF" },
  { id: "ERG", type: "ihc", desc: "Vascular" },
  { id: "HHV8", type: "ihc", desc: "Kaposi Sarcoma" },
  { id: "KIT", type: "ihc", desc: "GIST/Melanoma" },
  { id: "DOG1", type: "ihc", desc: "GIST" },
  { id: "Brachyury", type: "ihc", desc: "Chordoma" },
  { id: "CD99", type: "ihc", desc: "Ewing/Synovial" },
  { id: "NKX2.2", type: "ihc", desc: "Ewing Sarcoma" },
  { id: "Melan-A", type: "ihc", desc: "Melanocytic" },
  { id: "HMB45", type: "ihc", desc: "Melanocytic/PEComa" },
  { id: "PRAME", type: "ihc", desc: "Melanoma" },
  { id: "Ber-EP4", type: "ihc", desc: "BCC" },
  { id: "CK20", type: "ihc", desc: "Below Diaphragm/Merkel" },
  { id: "INSM1", type: "ihc", desc: "Neuroendocrine" },
  { id: "Staghorn Vessels", type: "morph", desc: "Branching vasculature" },
  { id: "Herringbone", type: "morph", desc: "Pattern" },
  { id: "Storiform", type: "morph", desc: "Pattern" },
  { id: "Spindle Cell", type: "morph", desc: "Cell shape" },
  { id: "Epithelioid", type: "morph", desc: "Cell shape" },
  { id: "Myxoid", type: "morph", desc: "Stroma" },
  { id: "Small Round Blue", type: "morph", desc: "Cell type" },
  { id: "Lipoblast", type: "morph", desc: "Adipocytic differentiation" },
  { id: "PAX8", type: "ihc", desc: "Mullerian/Renal" },
  { id: "WT1", type: "ihc", desc: "Serous/Mesothelial" },
  { id: "p53", type: "ihc", desc: "Mutant in HGSC/Leiomyosarcoma" },
  { id: "p16", type: "ihc", desc: "Block pos in HPV/LMS" },
  { id: "Inhibin", type: "ihc", desc: "Sex Cord" },
  { id: "SALL4", type: "ihc", desc: "Germ Cell" },
  { id: "OCT4", type: "ihc", desc: "Germ Cell" },
  { id: "HCG", type: "ihc", desc: "Choriocarcinoma" },
  { id: "Michaelis-Gutmann Bodies", type: "morph", desc: "Targetoid calcifications" },
  { id: "Psammoma Bodies", type: "morph", desc: "Calcified spherules" },
  { id: "Reinke Crystals", type: "morph", desc: "Eosinophilic rods" },
  { id: "Hydropic Change", type: "morph", desc: "Edema/Watery" },
  { id: "Walthard Rests", type: "morph", desc: "Transitional nests" },
  { id: "D2-40", type: "ihc", desc: "Lymphatic/Mesothelial" },
  { id: "Calretinin", type: "ihc", desc: "Mesothelial/Sex Cord" },
  { id: "Plasminogen", type: "molecular", desc: "Deficiency in Ligneous" },
  { id: "GATA3", type: "ihc", desc: "Breast/Urothelial" },
  { id: "JAZF1-SUZ12", type: "molecular", desc: "ESS Fusion" },
  { id: "Nidus", type: "morph", desc: "Central reactive zone" },
  { id: "Chinese Characters", type: "morph", desc: "Curvilinear bone trabeculae" },
  { id: "Ghost Cells", type: "morph", desc: "Anucleate keratinized cells" },
  { id: "Fluid-Fluid Levels", type: "morph", desc: "MRI finding in ABC" },
  { id: "GNAS", type: "molecular", desc: "Fibrous Dysplasia mutation" },
  { id: "USP6", type: "molecular", desc: "Nodular Fasciitis / ABC" },
  { id: "NR4A3", type: "molecular", desc: "EMC Fusion" },
  { id: "HMGA2", type: "molecular", desc: "Lipoma" },
  { id: "BCL2", type: "ihc", desc: "SFT/Trichoepithelioma" },
  { id: "CD68", type: "ihc", desc: "Histiocytic/Granular" },
  { id: "CD1a", type: "ihc", desc: "Langerhans Cell" },
  { id: "Langerin", type: "ihc", desc: "Langerhans Cell" },
  { id: "TTF1", type: "ihc", desc: "Lung/Thyroid" },
  { id: "PSA", type: "ihc", desc: "Prostate" },
  { id: "NKX3.1", type: "ihc", desc: "Prostate" },
  { id: "ER", type: "ihc", desc: "Breast/GYN" },
  { id: "PR", type: "ihc", desc: "Breast/GYN" },
  { id: "HER2", type: "ihc", desc: "Breast/Gastric" },
  { id: "CDX2", type: "ihc", desc: "GI" },
  { id: "CK7", type: "ihc", desc: "Above Diaphragm" },
  { id: "Chromogranin", type: "ihc", desc: "Neuroendocrine" },
  { id: "Synaptophysin", type: "ihc", desc: "Neuroendocrine" },
  { id: "GFAP", type: "ihc", desc: "Glial" },
  { id: "Olig2", type: "ihc", desc: "Glial" },
  { id: "HepPar1", type: "ihc", desc: "Hepatocellular" },
  { id: "Arginase-1", type: "ihc", desc: "Hepatocellular" },
  { id: "E-Cadherin", type: "ihc", desc: "Loss in Lobular Ca" },
  { id: "VHL", type: "molecular", desc: "Clear Cell RCC" },
  { id: "IDH1", type: "molecular", desc: "Glioma/Chondrosarcoma" },
  { id: "1p/19q", type: "molecular", desc: "Oligodendroglioma" },
  { id: "BRAF", type: "molecular", desc: "Melanoma/Thyroid/Colon" },
  { id: "KRAS", type: "molecular", desc: "Lung/Colon/Pancreas" },
  { id: "EGFR", type: "molecular", desc: "Lung/Glioblastoma" },
  { id: "ALK", type: "molecular", desc: "Lung/IMT" },
  { id: "MSI", type: "molecular", desc: "Lynch Syndrome" },
  { id: "EBER", type: "molecular", desc: "EBV (Nasopharyngeal)" },
  { id: "Triple Negative", type: "molecular", desc: "ER/PR/HER2 neg" },
  { id: "ETV6-NTRK3", type: "molecular", desc: "Secretory Ca" },
  { id: "Benign", type: "morph", desc: "Benign Behavior" },
  { id: "Syringomatous", type: "morph", desc: "Sweat gland diff" },
  { id: "Dermal Lymphatics", type: "morph", desc: "Invasion site" },
  { id: "BCOR", type: "molecular", desc: "CCSK/Sarcoma" },
  { id: "INI1", type: "ihc", desc: "Loss in Rhabdoid/Epithelioid Sarc" },
  { id: "Foamy Histiocytes", type: "morph", desc: "Xanthoma cells" },
  { id: "Neuroendocrine Markers", type: "ihc", desc: "Synapto/Chromo/INSM1" },
  { id: "Cartilage", type: "morph", desc: "Chondroid matrix" },
  { id: "Masson Bodies", type: "morph", desc: "Fibroblast plugs" },
  { id: "Granuloma", type: "morph", desc: "Histiocytic aggregate" },
  { id: "H. pylori", type: "molecular", desc: "Bacteria" },
  { id: "PPI", type: "morph", desc: "Proton Pump Inhibitor effect" },
  { id: "Mucin", type: "morph", desc: "Mucinous content" },
  { id: "Glycogen", type: "morph", desc: "Clear cytoplasm" },
  { id: "Ovarian Stroma", type: "morph", desc: "Spindle cell stroma" },
  { id: "CD20", type: "ihc", desc: "B-cell" },
  { id: "Androgen Receptor", type: "ihc", desc: "Salivary Duct/Sebaceous" },
  { id: "Capsule", type: "morph", desc: "Fibrous rim" },
  { id: "Hurthle Cells", type: "morph", desc: "Oncocytic metaplasia" }
];

export const RAW_LINKS = [
  // ... [Existing links preserved] ...

  // --- NEW LINKS FOR SYNCED ENTITIES ---
  { source: "Medullary Carcinoma", target: "Triple Negative" }, // Breast subtype
  { source: "Secretory Carcinoma", target: "ETV6-NTRK3" },
  { source: "LCIS", target: "E-Cadherin" }, // Loss
  { source: "ADH", target: "DCIS" }, // Precursor
  { source: "FEA", target: "ADH" }, // Precursor
  { source: "Radial Scar", target: "Benign" },
  { source: "Nipple Adenoma", target: "Syringomatous" },
  { source: "Inflammatory Carcinoma", target: "Dermal Lymphatics" },

  { source: "Metanephric Adenoma", target: "WT1" },
  { source: "Clear Cell Sarcoma of Kidney", target: "BCOR" },
  { source: "Rhabdoid Tumor (Kidney)", target: "INI1" }, // Loss
  { source: "Xanthogranulomatous Pyelonephritis", target: "Foamy Histiocytes" },
  { source: "Malakoplakia (Kidney)", target: "Michaelis-Gutmann Bodies" },
  { source: "Inverted Papilloma", target: "Benign" },
  { source: "Nephrogenic Adenoma", target: "PAX8" },

  { source: "Large Cell Neuroendocrine Ca (Lung)", target: "Neuroendocrine Markers" },
  { source: "Hamartoma (Lung)", target: "Cartilage" },
  { source: "Solitary Fibrous Tumor (Pleura)", target: "STAT6" },
  { source: "Organizing Pneumonia", target: "Masson Bodies" },
  { source: "Sarcoidosis", target: "Granuloma" },
  { source: "Mediastinal Germ Cell Tumor", target: "SALL4" },

  { source: "Chronic Gastritis", target: "H. pylori" },
  { source: "Fundic Gland Polyp", target: "PPI" },
  { source: "Neuroendocrine Tumor (GI)", target: "Chromogranin" },
  { source: "IPMN", target: "Mucin" },
  { source: "Serous Cystadenoma", target: "Glycogen" },
  { source: "Mucinous Cystic Neoplasm", target: "Ovarian Stroma" },

  { source: "Astrocytoma", target: "IDH1" },
  { source: "Schwannoma (CNS)", target: "S100" },
  { source: "Primary CNS Lymphoma", target: "CD20" },

  { source: "Salivary Duct Carcinoma", target: "Androgen Receptor" },
  { source: "Follicular Adenoma", target: "Capsule" },
  { source: "Hashimoto Thyroiditis", target: "Hurthle Cells" },
  { source: "Olfactory Neuroblastoma", target: "Synaptophysin" },
  { source: "Paraganglioma", target: "S100" }, // Sustentacular

  // GYN Links
  { source: "HGSC", target: "WT1" },
  { source: "HGSC", target: "p53" },
  { source: "HGSC", target: "PAX8" },
  { source: "HGSC", target: "STIC", label: "Precursor", type: "bridge" },
  { source: "Endometrioid Carcinoma", target: "ER" },
  { source: "Endometrioid Carcinoma", target: "Vimentin" },
  { source: "Endometrioid Carcinoma", target: "PAX8" },
  { source: "Clear Cell Carcinoma", target: "Napsin A" },
  { source: "Clear Cell Carcinoma", target: "HNF1B" },

  // GU Links
  { source: "Clear Cell Renal Cell Carcinoma", target: "CA9" },
  { source: "Clear Cell Renal Cell Carcinoma", target: "CD10" },
  { source: "Clear Cell Renal Cell Carcinoma", target: "PAX8" },
  { source: "Seminoma", target: "SALL4" },
  { source: "Seminoma", target: "OCT4" },
  { source: "Seminoma", target: "CD117" },
  { source: "Embryonal Carcinoma", target: "CD30" },
  { source: "Embryonal Carcinoma", target: "OCT4" },

  // Lung Links
  { source: "Lung Adenocarcinoma", target: "TTF1" },
  { source: "Lung Adenocarcinoma", target: "Napsin A" },
  { source: "SCC", target: "p40" },
  { source: "SCC", target: "CK5/6" },
];

// Re-exporting existing data structures to maintain continuity
// This file is now fully populated with the content from the previous steps
export const EXTENDED_DATA: Record<string, { clinical?: string, morphology?: string, ihc?: string, molecular?: string, prognosis?: string, differential?: string, pearls?: string[] }> = {
  // BST - Fibroblastic/Myofibroblastic
  "SFT": {
    clinical: "Deep soft tissue mass (thigh, pleura, orbit).",
    morphology: "Patternless architecture with alternating hypo/hypercellular areas. 'Ropey' collagen. Staghorn (branching) hemangiopericytoma-like vessels.",
    ihc: "STAT6 (diffuse nuclear), CD34, CD99, BCL2. Negative for S100, SOX10, Keratin.",
    molecular: "NAB2-STAT6 fusion (chr 12q).",
    differential: "MPNST, Synovial Sarcoma, Fibromatosis, GIST.",
    pearls: ["Staghorn vessels are characteristic but not pathognomonic.", "Nuclear STAT6 is the gold standard."]
  },
  "Desmoid Fibromatosis": {
    clinical: "Deep soft tissue (abdominal wall, intra-abdominal, extremity).",
    morphology: "Long sweeping fascicles of bland myofibroblasts. Infiltrative borders. 'Keloid-like' collagen.",
    ihc: "Beta-catenin (nuclear), SMA. Negative for CD34, S100.",
    molecular: "CTNNB1 mutation or APC (Gardner syndrome).",
    prognosis: "Locally aggressive, does not metastasize.",
    differential: "Low-grade Fibromyxoid Sarcoma, Scar/Reactive Fibrosis.",
    pearls: ["Better prognosis if abdominal wall.", "Nuclear Beta-catenin in ~80%."]
  },
  "Myxofibrosarcoma": {
    clinical: "Elderly, superficial soft tissue of extremities.",
    morphology: "Multinodular growth. Myxoid stroma. Curvilinear vessels with perivascular condensation of atypical cells.",
    ihc: "None specific (diagnosis of exclusion).",
    molecular: "Complex karyotype.",
    prognosis: "High recurrence rate, metastatic potential increases with grade.",
    differential: "Myxoid Liposarcoma, Low-grade Fibromyxoid Sarcoma.",
    pearls: ["Curvilinear vessels + Atypia = MFS."]
  },
  "LGFMS": {
    clinical: "Young adults, deep soft tissue.",
    morphology: "Alternating fibrous and myxoid areas. Whorled growth pattern. Bland spindle cells.",
    ihc: "MUC4 (diffuse).",
    molecular: "FUS-CREB3L2 fusion.",
    prognosis: "Late metastases (lung) can occur even after many years.",
    differential: "Desmoid, Myxofibrosarcoma, Perineurioma.",
    pearls: ["'Bland looking but dangerous'.", "MUC4 is highly specific."]
  },
  "Nodular Fasciitis": {
    clinical: "Rapidly growing, painful subcutaneous nodule. Young adults.",
    morphology: "Tissue culture-like fibroblasts. Myxoid stroma. Extravasated RBCs. Mitotically active but no atypia.",
    ihc: "SMA, USP6 rearrangement.",
    prognosis: "Self-limiting / Benign.",
    differential: "Sarcoma (due to rapid growth/mitoses).",
    pearls: ["'Feather-like' pattern.", "Does not recur after excision."]
  },
  "Elastofibroma": {
    clinical: "Subscapular mass in elderly. 'Clunk' sensation.",
    morphology: "Collagen and coarse elastic fibers (daisy-like in cross section).",
    prognosis: "Benign.",
    differential: "Fibroma.",
    pearls: ["Elastic stain highlights serrated fibers."]
  },

  // BST - Adipocytic
  "WDLPS": {
    clinical: "Retroperitoneal or deep limb mass in older adults.",
    morphology: "Mature adipose tissue with variation in adipocyte size. Hyperchromatic, atypical stromal spindle cells. Lipoblasts may be seen but are not required.",
    ihc: "MDM2+, CDK4+, p16+. Negative for CD34 (variable).",
    molecular: "MDM2/CDK4 amplification (12q13-15).",
    differential: "Lipoma, Fat Necrosis, Pleomorphic Lipoma.",
    pearls: ["A 'lipoma' in the retroperitoneum is WDLPS until proven otherwise.", "Look for atypical cells in fibrous septa."]
  },
  "DDLPS": {
    clinical: "Retroperitoneum, often recurrent WDLPS.",
    morphology: "Abrupt transition from WDLPS to non-lipogenic sarcoma (often high-grade, UPS-like or neural-like).",
    ihc: "MDM2+, CDK4+, p16+.",
    molecular: "MDM2 amplification.",
    differential: "UPS, Leiomyosarcoma, MPNST.",
    pearls: ["Can have heterologous elements (rhabdo, osteo, chondro)."]
  },
  "Myxoid Liposarcoma": {
    clinical: "Deep thigh mass in young adults (30-50y).",
    morphology: "Hypocellular, myxoid background with 'chicken-wire' capillary network. Lipoblasts (signet-ring like) often present.",
    ihc: "S100 (focal), NY-ESO-1.",
    molecular: "t(12;16) FUS-DDIT3.",
    differential: "Myxofibrosarcoma, Myxoma, Extraskeletal Myxoid Chondrosarcoma.",
    pearls: ["Round cell component >5% indicates higher grade.", "Pulmonary metastases are rare; look for extrapulmonary (bone, retroperitoneum) spread."]
  },
  "Pleomorphic Liposarcoma": {
    clinical: "Deep soft tissue, elderly.",
    morphology: "High-grade pleomorphic sarcoma with pleomorphic lipoblasts (hyperchromatic scalloped nuclei).",
    ihc: "None specific (MDM2 negative).",
    prognosis: "Poor.",
    differential: "Dedifferentiated Liposarcoma, UPS.",
    pearls: ["Must find pleomorphic lipoblasts for diagnosis."]
  },
  "Lipoma": {
    clinical: "Soft, mobile mass.",
    morphology: "Mature adipocytes. No atypia. No lipoblasts.",
    molecular: "HMGA2 rearrangement (subset).",
    prognosis: "Benign.",
    differential: "ALT/WDLPS, Angiolipoma.",
    pearls: ["Any atypia in a retroperitoneal 'lipoma' makes it WDLPS."]
  },
  "Angiolipoma": {
    clinical: "Painful subcutaneous nodules, often multiple.",
    morphology: "Mature fat with capillary thrombi (fibrin).",
    prognosis: "Benign.",
    differential: "Lipoma, Angiosarcoma (rarely).",
    pearls: ["Fibrin thrombi are diagnostic."]
  },

  // BST - Nerve Sheath
  "MPNST": {
    clinical: "NF1 patient with enlarging mass or sporadic deep mass.",
    morphology: "Marbled (alternating cellularity), hypercellular fascicles, perivascular herniation, geographic necrosis, tapering ('wavy') nuclei.",
    ihc: "S100 (patchy/weak in 50%), SOX10 (often negative), H3K27me3 (loss in ~50-70%).",
    molecular: "NF1 loss, PRC2 complex (SUZ12/EED) inactivation.",
    differential: "Cellular Schwannoma, Fibrosarcoma, Synovial Sarcoma, Melanoma.",
    pearls: ["Complete loss of H3K27me3 is highly specific for MPNST in the context of a nerve sheath tumor."]
  },
  "Schwannoma": {
    clinical: "Any site, encapsulated.",
    morphology: "Antoni A (cellular, Verocay bodies) and Antoni B (myxoid). Hyalinized vessels.",
    ihc: "S100 (diffuse strong), SOX10.",
    prognosis: "Benign.",
    differential: "MPNST, Neurofibroma, Leiomyoma.",
    pearls: ["Ancient change (atypia) is common and benign."]
  },
  "Neurofibroma": {
    clinical: "Skin nodule or deep mass (NF1).",
    morphology: "Wavy spindle cells, 'shredded carrot' collagen, mast cells.",
    ihc: "S100 (scattered), CD34 (fingerprint), SOX10.",
    prognosis: "Benign (unless Plexiform -> risk of MPNST).",
    differential: "Schwannoma, DFSP.",
    pearls: ["Diffuse CD34 pattern helps distinguish from Schwannoma."]
  },
  "Granular Cell Tumor": {
    clinical: "Tongue, Skin, Breast.",
    morphology: "Large cells with abundant granular eosinophilic cytoplasm. Pseudoepitheliomatous hyperplasia (PEH) of overlying epithelium.",
    ihc: "S100+, CD68+, PAS-D+.",
    molecular: "Inactivating mutations in ATP6AP1 or ATP6AP2.",
    prognosis: "Benign (mostly). Malignant if: necrosis, spindling, high mitoses.",
    differential: "SCC (due to PEH), Rhabdomyoma.",
    pearls: ["Granules are lysosomes.", "Beware misdiagnosing PEH as SCC."]
  },

  // BST - Uncertain/Misc
  "Synovial Sarcoma": {
    clinical: "Deep soft tissue of extremities (knee) in young adults.",
    morphology: "Monophasic (spindle cells only) or Biphasic (spindle + glands). Dense cellularity, high N:C ratio, 'herringbone' pattern.",
    ihc: "TLE1 (nuclear), Cytokeratin (focal), EMA, CD99. Negative for CD34.",
    molecular: "t(X;18) SS18-SSX1/2/4.",
    differential: "MPNST, SFT, Fibrosarcoma, Ewing Sarcoma.",
    pearls: ["Paradoxical co-expression of mesenchymal (Vimentin) and epithelial (Keratin) markers.", "Differential includes MPNST (TLE1 can be +) and Ewing Sarcoma (CD99+)."]
  },
  "Epithelioid Sarcoma": {
    clinical: "Distal extremity (hand/wrist) in young adults. Ulcerates.",
    morphology: "Nodular growth, central necrosis (granuloma-like). Epithelioid cells.",
    ihc: "Keratin+, CD34+, INI1 (Loss).",
    molecular: "SMARCB1 (INI1) deletion.",
    prognosis: "Aggressive, lymph node metastasis common.",
    differential: "Granuloma annulare, SCC, Angiosarcoma.",
    pearls: ["'CAKS' - Classic type: Acral, Keratin+, Sarcoma.", "INI1 loss is diagnostic."]
  },
  "Alveolar Soft Part Sarcoma": {
    clinical: "Deep thigh (adults) or Head/Neck (kids).",
    morphology: "Nests (alveolar) of large polygonal cells. Granular cytoplasm. PAS+ crystals.",
    ihc: "TFE3 (nuclear).",
    molecular: "ASPSCR1-TFE3 fusion.",
    prognosis: "Brain metastases common.",
    differential: "RCC, Granular Cell Tumor.",
    pearls: ["PAS-D highlights crystals."]
  },
  "Clear Cell Sarcoma": {
    clinical: "Tendons/Aponeuroses of extremities (foot/ankle).",
    morphology: "Nests of pale/clear cells separated by fibrous septa. Melanin pigment.",
    ihc: "S100+, HMB45+, Melan-A+.",
    molecular: "t(12;22) EWSR1-ATF1.",
    differential: "Metastatic Melanoma.",
    pearls: ["'Melanoma of soft parts' - but distinct translocation."]
  },
  "Intramuscular Myxoma": {
    clinical: "Thigh/Shoulder muscle mass.",
    morphology: "Hypocellular, abundant myxoid stroma. Atrophic muscle fibers at periphery.",
    ihc: "CD34 (variable), GNAS (molecular).",
    molecular: "GNAS mutation (Mazabraud syndrome).",
    prognosis: "Benign.",
    differential: "Myxoid Liposarcoma, MFS.",
    pearls: ["Lack of vasculature compared to sarcomas."]
  },

  // BST - Vascular
  "Angiosarcoma": {
    clinical: "Sun-exposed scalp (elderly) or post-radiation breast.",
    morphology: "Vasoformative channels lined by atypical endothelial cells. Can be solid/spindled. 'Dissection' of collagen planes.",
    ihc: "CD31+, ERG+, CD34+, FLI1+.",
    molecular: "MYC amplification (in post-radiation cases).",
    prognosis: "Poor.",
    differential: "Kaposi Sarcoma, Epithelioid Hemangioendothelioma, Undifferentiated Carcinoma.",
    pearls: ["Look for intracytoplasmic lumina containing RBCs."]
  },
  "Kaposi Sarcoma": {
    clinical: "HHV8 associated (Classic, HIV, Transplant). Skin/Visceral.",
    morphology: "Spindle cells, slit-like vascular spaces, extravasated RBCs, hyaline globules.",
    ihc: "HHV8 (LANA-1), CD31, CD34, ERG.",
    prognosis: "Variable.",
    differential: "Angiosarcoma, Spindle Cell Hemangioma.",
    pearls: ["Promontory sign (vessel protrudes into space)."]
  },
  "EHE": {
    clinical: "Liver, Lung, Bone, Soft Tissue.",
    morphology: "Cords/chains of epithelioid endothelial cells in myxohyaline stroma. Intracytoplasmic vacuoles (blister cells).",
    ihc: "CD31+, ERG+, CD34+, CAMTA1 (nuclear).",
    molecular: "WWTR1-CAMTA1 fusion.",
    prognosis: "Intermediate malignancy.",
    differential: "Carcinoma, Epithelioid Angiosarcoma.",
    pearls: ["Blister cells containing RBCs."]
  },
  "Glomus Tumor": {
    clinical: "Subungual, painful, cold-sensitive.",
    morphology: "Round uniform cells surrounding vessels. punched-out nuclei.",
    ihc: "SMA+, CD34-.",
    prognosis: "Benign.",
    differential: "Myopericytoma.",
    pearls: ["Classic triad: Pain, Cold sensitivity, Pinpoint tenderness."]
  },

  // BST - Muscle & GIST
  "Leiomyosarcoma": {
    clinical: "Rapidly enlarging uterus, single mass.",
    morphology: "Fascicles of spindle cells, severe nuclear atypia, tumor cell necrosis (coagulative), mitoses >10/10 HPF.",
    ihc: "SMA+, Desmin+, h-Caldesmon+, p16 (diffuse), p53 (mutant). ER/PR often negative.",
    prognosis: "Aggressive.",
    differential: "Leiomyoma with infarct, STUMP, Endometrial Stromal Sarcoma.",
    pearls: ["Evaluation of 'coagulative tumor cell necrosis' is critical."]
  },
  "Rhabdomyosarcoma": {
    clinical: "Pediatric (Head/Neck, GU).",
    morphology: "Small round blue cells (Embryonal/Alveolar). Strap cells (rhabdomyoblasts) with cross-striations.",
    ihc: "Desmin+, Myogenin (nuclear), MyoD1.",
    molecular: "PAX3/7-FOXO1 (Alveolar).",
    differential: "Ewing, Lymphoma.",
    pearls: ["Alveolar subtype has worse prognosis."]
  },
  "GIST": {
    clinical: "GI tract (Stomach > Small Bowel).",
    morphology: "Spindle or Epithelioid. Perinuclear vacuoles. Skenoid fibers.",
    ihc: "KIT (CD117)+, DOG1+, CD34+.",
    molecular: "KIT or PDGFRA mutation.",
    prognosis: "Risk stratification based on Size, Mitoses, Site.",
    differential: "Leiomyoma, Schwannoma.",
    pearls: ["Succinate Dehydrogenase (SDH) deficient GIST in young females (Carney triad)."]
  },
  "UPS": {
    clinical: "Deep soft tissue mass, elderly.",
    morphology: "Pleomorphic spindle/epithelioid cells, storiform pattern, bizarre giant cells.",
    ihc: "Diagnosis of exclusion. Vimentin+, CD68+ (non-specific). Negative for specific lineage markers (Keratin, S100, Desmin, etc.).",
    prognosis: "Aggressive.",
    differential: "Dedifferentiated Liposarcoma, Pleomorphic Rhabdomyosarcoma, Melanoma.",
    pearls: ["Must rule out Dedifferentiated Liposarcoma (MDM2) and Pleomorphic Rhabdo/LMS."]
  },

  // BST - Bone
  "Osteosarcoma": {
    clinical: "Metaphysis of long bones (knee) in adolescents. bimodal peak in elderly.",
    morphology: "Malignant mesenchymal cells producing osteoid (lace-like, pink matrix). Pleomorphic cells.",
    ihc: "SATB2+, Osteocalcin. Negative for SOX10, Keratin.",
    molecular: "Complex karyotype, TP53, RB1 mutations.",
    prognosis: "Aggressive, requires chemo + surgery.",
    differential: "Osteoblastoma, Fracture Callus, Chondrosarcoma.",
    pearls: ["Production of osteoid by malignant cells is the definition.", "Codman triangle on X-ray."]
  },
  "Ewing Sarcoma": {
    clinical: "Diaphysis of long bones in children/young adults.",
    morphology: "Sheets of uniform small round blue cells. Glycogenated cytoplasm (PAS+). Necrosis common.",
    ihc: "CD99 (diffuse membranous), NKX2.2, FLI1. Negative for lymphoid markers.",
    molecular: "t(11;22) EWSR1-FLI1 (85%).",
    differential: "Lymphoma, Rhabdomyosarcoma, Small Cell Osteosarcoma, Neuroblastoma.",
    pearls: ["'Onion-skinning' periosteal reaction.", "CD99 is sensitive but not specific; verify with molecular or NKX2.2."]
  },
  "Chondrosarcoma": {
    clinical: "Older adults, axial skeleton (pelvis, shoulder).",
    morphology: "Lobules of cartilage with atypical chondrocytes (binucleation, hyperchromasia). Permeation of marrow fat (trapping host bone).",
    ihc: "S100+, D2-40+, IDH1/2 (mutant protein).",
    molecular: "IDH1 or IDH2 mutations.",
    differential: "Enchondroma, Chondroblastic Osteosarcoma, Chordoma.",
    pearls: ["Permeation of marrow fat is the best sign of malignancy vs enchondroma."]
  },
  "Osteoid Osteoma": {
    clinical: "Night pain relieved by NSAIDs. Young patients.",
    morphology: "Central nidus of osteoid and woven bone, surrounded by sclerotic bone.",
    prognosis: "Benign.",
    differential: "Osteoblastoma (if >2cm), Osteomyelitis.",
    pearls: ["Nidus is usually <1.5 cm.", "Targetoid appearance on imaging."]
  },
  "Osteoblastoma": {
    clinical: "Dull pain, not relieved by NSAIDs. Spine/Sacrum common.",
    morphology: "Similar to Osteoid Osteoma but larger. Sheets of osteoblasts, vascular stroma.",
    prognosis: "Benign, locally aggressive.",
    differential: "Osteosarcoma, Osteoid Osteoma.",
    pearls: ["'Giant Osteoid Osteoma' >2cm."]
  },
  "ABC": {
    clinical: "Rapidly expanding lytic lesion. 'Blow-out'.",
    morphology: "Blood-filled cystic spaces separated by fibrous septa. Giant cells, osteoid.",
    molecular: "USP6 rearrangement (primary ABC).",
    prognosis: "Benign, locally destructive.",
    differential: "Telangiectatic Osteosarcoma, Giant Cell Tumor.",
    pearls: ["Fluid-fluid levels on MRI.", "Solid variant exists."]
  },
  "UBC": {
    clinical: "Proximal humerus/femur in kids. Fallen fragment sign.",
    morphology: "Thin fibrous lining. Fluid filled. Cementum-like material.",
    prognosis: "Benign.",
    differential: "ABC.",
    pearls: ["Fallen fragment sign is pathognomonic."]
  },
  "Fibrous Dysplasia": {
    clinical: "Monostotic or Polyostotic (McCune-Albright).",
    morphology: "Curvilinear woven bone trabeculae ('Chinese characters') in fibrous stroma without osteoblastic rimming.",
    molecular: "GNAS mutation.",
    prognosis: "Benign.",
    differential: "Low-grade Central Osteosarcoma, Ossifying Fibroma.",
    pearls: ["Lack of osteoblastic rimming is the key feature."]
  },
  "Adamantinoma": {
    clinical: "Tibial diaphysis. Pain/swelling.",
    morphology: "Biphasic: Epithelial nests (basaloid/squamous) in osteofibrous stroma.",
    ihc: "Keratin+, p63+.",
    prognosis: "Low-grade malignancy.",
    differential: "Osteofibrous Dysplasia (precursor?), Metastatic Carcinoma.",
    pearls: ["Almost exclusive to the tibia."]
  },
  "EMC": {
    clinical: "Deep soft tissue of extremities.",
    morphology: "Cords of uniform eosinophilic cells in abundant myxoid matrix. 'Cord-like' pattern.",
    molecular: "NR4A3 rearrangement.",
    prognosis: "Indolent malignancy, late metastases.",
    differential: "Myoepithelioma, Chondroma.",
    pearls: ["Not actually a cartilage tumor (misnomer)."]
  },
  "Osteochondroma": {
    clinical: "Metaphysis. Bony projection.",
    morphology: "Cartilage cap overlying bone with continuous marrow space.",
    molecular: "EXT1/EXT2 mutations.",
    prognosis: "Benign. Risk of secondary chondrosarcoma if cap >2cm.",
    differential: "Parosteal Osteosarcoma.",
    pearls: ["Medullary continuity with host bone is diagnostic."]
  },
  "Enchondroma": {
    clinical: "Hands/Feet. Lytic lesion.",
    morphology: "Lobules of hyaline cartilage. Hypocellular. Host bone encasement (not permeation).",
    molecular: "IDH1/2 mutations.",
    prognosis: "Benign.",
    differential: "Chondrosarcoma (low grade).",
    pearls: ["Pain in the absence of fracture suggests malignancy."]
  },
  "NOF": {
    clinical: "Metaphyseal cortical defect. Kids.",
    morphology: "Storiform spindle cells, foam cells, hemosiderin, giant cells.",
    molecular: "KRAS/FGFR1 mutations.",
    prognosis: "Benign (don't touch).",
    differential: "Giant Cell Tumor.",
    pearls: ["Spontaneous regression is common."]
  },
  "Chondromyxoid Fibroma": {
    clinical: "Metaphysis (Tibia).",
    morphology: "Lobulated with chondroid/myxoid matrix. Stellate cells at periphery of lobules. Giant cells in septa.",
    prognosis: "Benign.",
    differential: "Chondrosarcoma.",
    pearls: ["Hypocellular center, hypercellular periphery of lobules."]
  },
  "Plasma Cell Myeloma": {
    clinical: "Lytic bone lesions, older adults. CRAB symptoms.",
    morphology: "Sheets of plasma cells (clockface chromatin, perinuclear hof).",
    ihc: "CD138+, Kappa/Lambda restriction.",
    prognosis: "Malignant.",
    differential: "Osteomyelitis, Metastatic Carcinoma.",
    pearls: ["Bone marrow biopsy required."]
  },
  "TGCT": {
    clinical: "Joints/Tendon sheaths (Finger - localized, Knee - diffuse).",
    morphology: "Mononuclear cells, osteoclast-like giant cells, foam cells, hemosiderin.",
    molecular: "CSF1 translocation (COL6A3-CSF1).",
    prognosis: "Locally aggressive (Diffuse type).",
    differential: "Sarcoma.",
    pearls: ["Diffuse type = Pigmented Villonodular Synovitis (PVNS)."]
  },
  "Chordoma": {
    clinical: "Axial skeleton (Clivus, Sacrum).",
    morphology: "Physaliphorous (bubbly) cells in myxoid stroma. Cords/Lobules.",
    ihc: "Brachyury (nuclear)+, Keratin+, S100+.",
    prognosis: "Malignant, local recurrence common.",
    differential: "Chondrosarcoma.",
    pearls: ["Brachyury is the specific marker."]
  },
  "Giant Cell Tumor": {
    clinical: "Epiphysis (Knee), closed growth plates.",
    morphology: "Uniform mononuclear stromal cells mixed with evenly distributed giant cells.",
    ihc: "H3.3 G34W+ (nuclear in mononuclear cells).",
    molecular: "H3F3A mutation.",
    prognosis: "Benign but locally aggressive. Lung mets (benign) possible.",
    differential: "ABC, Chondroblastoma, Brown Tumor.",
    pearls: ["H3.3 G34W confirms diagnosis."]
  },
  "LCH": {
    clinical: "Lytic bone lesion (Eosinophilic Granuloma). Skin rash.",
    morphology: "Langerhans cells (grooved nuclei) + Eosinophils.",
    ihc: "CD1a+, S100+, Langerin+.",
    molecular: "BRAF V600E.",
    differential: "Osteomyelitis, Lymphoma.",
    pearls: ["Coffee-bean nuclei.", "Birbeck granules on EM."]
  },
  "Metastatic Carcinoma": {
    clinical: "History of cancer (Breast, Prostate, Lung, Kidney, Thyroid).",
    morphology: "Nests of atypical epithelial cells, glandular formation, or desmoplasia.",
    ihc: "Pan-Keratin+, Lineage markers (TTF1, GATA3, PAX8).",
    prognosis: "Stage IV disease.",
    differential: "Primary bone sarcoma, Myeloma.",
    pearls: ["Most common malignant tumor of bone in adults.", "Kidney/Thyroid can mimic vascular/sarcomatous lesions."]
  },
  "Angioleiomyoma": {
    clinical: "Painful subcutaneous nodule, often on leg.",
    morphology: "Well-circumscribed. Whorls of smooth muscle around thick-walled vessels.",
    ihc: "SMA+, Desmin+, HMB45 negative.",
    prognosis: "Benign.",
    differential: "Leiomyosarcoma, Myopericytoma.",
    pearls: ["Can be very painful.", "Fat is usually absent."]
  },
  "Neurofibroma (Skin)": {
    clinical: "Soft, fleshy, pedunculated nodule.",
    morphology: "Unencapsulated. Wavy spindle cells in loose stroma. Mast cells.",
    ihc: "S100 (scattered), CD34 (fingerprint), SOX10.",
    prognosis: "Benign.",
    differential: "Neurotized Nevus, Dermatofibroma.",
    pearls: ["Wagner-Meissner bodies may be seen.", "Does not have the risk of malignancy of plexiform types."]
  },
  "Nevus": {
    clinical: "Pigmented macule/papule.",
    morphology: "Nests of melanocytes at junction (Junctional) or dermis (Intradermal). Maturation with depth.",
    ihc: "S100+, SOX10+, Melan-A+, HMB45 (superficial only).",
    prognosis: "Benign.",
    differential: "Melanoma, Dysplastic Nevus.",
    pearls: ["Maturation is key: cells get smaller and disperse deeper.", "No mitoses in dermis."]
  },

  // DermPath
  "BCC": {
    clinical: "Pearly papule, telangiectasia. Sun-exposed.",
    morphology: "Basaloid islands, peripheral palisading, retraction artifact, mucin.",
    ihc: "Ber-EP4+, Bcl2+.",
    prognosis: "Malignant but rarely metastasizes.",
    differential: "Trichoepithelioma, SCC.",
    pearls: ["Retraction clefts are characteristic."]
  },
  "SCC": {
    clinical: "Skin ulcer/plaque in sun-exposed area, or lung mass (central).",
    morphology: "Atypical keratinocytes, keratin pearls, intercellular bridges. Infiltrative growth.",
    ihc: "p40, p63, CK5/6. Negative for TTF1 (lung).",
    prognosis: "Generally good for skin (if small); poor for lung.",
    differential: "BCC, Pseudoepitheliomatous Hyperplasia.",
    pearls: ["Infiltrative borders differentiate from PEH."]
  },
  "Melanoma": {
    clinical: "Sun-exposed skin, history of changing mole.",
    morphology: "The great mimicker. Nests, sheets, spindled or epithelioid. Prominent nucleoli ('cherry red'). Pagetoid spread in epidermis.",
    ihc: "S100 (sensitive), SOX10, Melan-A, HMB45, PRAME.",
    molecular: "BRAF V600E (common), NRAS, KIT (acral/mucosal).",
    differential: "Spitz Nevus, MPNST, Clear Cell Sarcoma, Carcinoma.",
    pearls: ["S100 is negative in carcinomas; Keratin is negative in melanoma (mostly)."]
  },
  "Merkel Cell Ca": {
    clinical: "Rapidly growing red/purple nodule. Elderly.",
    morphology: "Sheets of small round blue cells. Salt and pepper chromatin. Mitoses.",
    ihc: "CK20 (perinuclear dot)+, Neuroendocrine markers+.",
    molecular: "MCPyV (Polyomavirus).",
    prognosis: "Aggressive.",
    differential: "Small Cell Lung Ca (TTF1+), Lymphoma.",
    pearls: ["CK20 dot-like pattern is classic."]
  },
  "DFSP": {
    clinical: "Protuberant mass on trunk/proximal extremity.",
    morphology: "Uniform spindle cells, storiform (cartwheel) pattern. Honeycomb infiltration of fat.",
    ihc: "CD34+.",
    molecular: "COL1A1-PDGFB translocation.",
    prognosis: "Local recurrence if incomplete excision. Fibrosarcomatous transformation possible.",
    differential: "Dermatofibroma, Neurofibroma.",
    pearls: ["Honeycomb fat entrapment."]
  },
  "AFX": {
    clinical: "Sun-damaged skin (Head/Neck). Rapid growth.",
    morphology: "Pleomorphic spindle/epithelioid cells. Bizarre giant cells. No keratin/S100.",
    ihc: "CD10+, Procollagen-1+, CD68+.",
    prognosis: "Good (superficial). If deep/necrosis/LVI -> PDS.",
    differential: "Spindle Cell SCC, Melanoma, Leiomyosarcoma.",
    pearls: ["Diagnosis of exclusion."]
  },
  "Sebaceous Ca": {
    clinical: "Eyelid (Meibomian) or extraocular.",
    morphology: "Lobules of basaloid cells with vacuolated (sebaceous) cells. Pagetoid spread common.",
    ihc: "Adipophilin+, Androgen Receptor+, EMA+.",
    molecular: "Mismatch repair deficiency (Muir-Torre).",
    prognosis: "Malignant.",
    differential: "BCC, SCC.",
    pearls: ["Oil Red O stain on fresh tissue."]
  },
  "Dermatofibroma": {
    clinical: "Firm nodule, 'dimple sign'.",
    morphology: "Spindle cells, collagen trapping at periphery. Epidermal hyperplasia.",
    ihc: "Factor XIIIa+.",
    prognosis: "Benign.",
    differential: "DFSP.",
    pearls: ["Peripheral collagen trapping."]
  },
  "Seborrheic Keratosis": {
    clinical: "Stuck-on waxy papule.",
    morphology: "Basaloid proliferation, horn cysts (pseudocysts), hyperkeratosis.",
    prognosis: "Benign.",
    differential: "Melanoma (if pigmented).",
    pearls: ["Horn cysts are continuous with surface."]
  },
  "Pyogenic Granuloma": {
    clinical: "Bleeding nodule. Pregnancy/Trauma.",
    morphology: "Lobular capillary proliferation. Ulceration. Epithelial collarette.",
    prognosis: "Benign.",
    differential: "Kaposi Sarcoma, Amelanotic Melanoma.",
    pearls: ["Lobular architecture."]
  },
  "Mycosis Fungoides": {
    clinical: "Patches/Plaques/Tumors.",
    morphology: "Epidermotropism of lymphocytes (Pautrier microabscesses). Cerebriform nuclei.",
    ihc: "CD3+, CD4+, CD8-.",
    prognosis: "Indolent T-cell lymphoma.",
    differential: "Eczema, Psoriasis.",
    pearls: ["Lymphocytes tagging the basal layer."]
  },
  "Keratoacanthoma": {
    clinical: "Rapid growth, central crater.",
    morphology: "Cup-shaped, central keratin plug. Glassy cytoplasm. Liplike edges.",
    prognosis: "Can regress, but treated as SCC.",
    differential: "SCC.",
    pearls: ["Crateriform architecture."]
  },
  "Pilomatricoma": {
    clinical: "Cheek/Arm nodule in children.",
    morphology: "Basaloid cells maturing into anucleate 'Ghost cells'. Calcification/Ossification.",
    ihc: "Beta-catenin (nuclear).",
    prognosis: "Benign.",
    differential: "Pilomatrical Carcinoma.",
    pearls: ["'Ghost cells' are dead keratinocytes retaining cell borders."]
  },
  "Actinic Keratosis": {
    clinical: "Sun-exposed skin. Scaly patch.",
    morphology: "Parakeratosis, basal atypia, sparing of adnexal structures ('Flag sign').",
    prognosis: "Pre-malignant (SCC precursor).",
    differential: "SCC in situ, Seborrheic Keratosis.",
    pearls: ["Partial thickness atypia only."]
  },
  "Blue Nevus": {
    clinical: "Blue-black macule/papule.",
    morphology: "Dendritic melanocytes in dermis. Heavily pigmented. Sclerosis.",
    ihc: "HMB45+, Melan-A+.",
    molecular: "GNAQ/GNA11.",
    differential: "Melanoma, Cellular Blue Nevus.",
    pearls: ["Dendritic processes between collagen bundles."]
  },
  "Spitz Nevus": {
    clinical: "Pink/Red nodule in children.",
    morphology: "Large spindled/epithelioid melanocytes. Kamino bodies. Vertical orientation.",
    ihc: "S100+, p16 retained.",
    differential: "Spitzoid Melanoma.",
    pearls: ["Kamino bodies (eosinophilic globules)."]
  },
  "Verruca Vulgaris": {
    clinical: "Wart.",
    morphology: "Papillomatosis, hypergranulosis, koilocytes (HPV effect). Inward turning rete.",
    prognosis: "Benign.",
    differential: "Verrucous Carcinoma.",
    pearls: ["Koilocytes: perinuclear halo + nuclear irregularity."]
  },
  "Epidermal Inclusion Cyst": {
    clinical: "Mobile nodule with punctum.",
    morphology: "Cyst lined by stratified squamous epithelium with granular layer. Flaky keratin.",
    prognosis: "Benign.",
    differential: "Trichilemmal Cyst (no granular layer).",
    pearls: ["Rupture causes granulomatous reaction."]
  },
  "Trichoepithelioma": {
    clinical: "Face papules.",
    morphology: "Basaloid islands, horn cysts, papillary mesenchymal bodies.",
    ihc: "BCL2+ (peripheral), CD34+ (stroma), CK20+ (Merkel cells present).",
    differential: "BCC.",
    pearls: ["Papillary mesenchymal bodies are key."]
  },
  "Sebaceous Adenoma": {
    clinical: "Face/Scalp.",
    morphology: "Lobules of sebocytes (>50% mature).",
    ihc: "Adipophilin.",
    differential: "Sebaceous Carcinoma.",
    pearls: ["Sharply circumscribed."]
  },
  "Papillary Hidradenoma": {
    clinical: "Vulvar/Labial nodule.",
    morphology: "Complex papillary folds, two cell layers (luminal + myoepithelial).",
    ihc: "CK7+ (luminal), SMA/p63+ (myoepithelial).",
    prognosis: "Benign.",
    differential: "Adenocarcinoma.",
    pearls: ["Ectopic breast tissue (Intraductal Papilloma equivalent)."]
  },

  // GYN Detailed Expansion
  "HGSC": {
    clinical: "Pelvic mass in older women, often presents at high stage. Elevated CA-125.",
    morphology: "Complex papillary, solid, or glandular growth. High-grade cytology, prominent nucleoli, high mitotic rate. Psammoma bodies frequently present.",
    ihc: "WT1 (diffuse nuclear), p53 (mutant pattern: null or diffuse/strong), p16 (diffuse), PAX8. Negative for ER (variable).",
    molecular: "TP53 mutations (near universal), BRCA1/2 mutations (germline or somatic).",
    prognosis: "Poor; often advanced at diagnosis. High response to platinum but frequent recurrence.",
    differential: "LGSC, Endometrioid Carcinoma (FIGO 3), Clear Cell Carcinoma.",
    pearls: ["STIC in the fallopian tube is the precursor.", "WT1 is the most reliable marker to confirm serous origin."]
  },
  "Endometrioid Carcinoma": {
    clinical: "Postmenopausal bleeding. Associated with obesity, hyperestrogenism, and endometriosis.",
    morphology: "Glandular architecture resembling proliferative endometrium. Squamous differentiation (morules) is common. Cribriforming and back-to-back glands.",
    ihc: "ER/PR (strong), Vimentin, PAX8. p53 (wild-type pattern). MMR (mismatch repair) loss in subset.",
    molecular: "PTEN, PIK3CA, ARID1A, CTNNB1 mutations.",
    prognosis: "Generally good for low-grade tumors; depends on FIGO grade and depth of invasion.",
    differential: "Serous Carcinoma, Microglandular Hyperplasia.",
    pearls: ["Vimentin positivity helps distinguish from endocervical adenocarcinoma."]
  },
  "Serous Carcinoma": {
    clinical: "Postmenopausal bleeding. Aggressive.",
    morphology: "High-grade cytology, slit-like spaces, glandular/papillary.",
    ihc: "p53 mutant, p16 diffuse, WT1 variable.",
    prognosis: "Poor.",
    differential: "Endometrioid Carcinoma (FIGO 3).",
    pearls: ["Uterine serous is the prototype of Type II endometrial cancer."]
  },
  "Clear Cell Carcinoma": { clinical: "Endometriosis assoc.", morphology: "Hobnail cells, clear cyto.", ihc: "Napsin A+, HNF1b+.", pearls: ["Hyaline globules."] },
  "Clear Cell Ca (Vagina)": {
    clinical: "DES exposure (historical), young women.",
    morphology: "Tubulocystic, hobnail cells, clear cytoplasm.",
    ihc: "Napsin A+, HNF1b+.",
    prognosis: "Variable.",
    differential: "Arias-Stella Reaction.",
    pearls: ["Associated with Vaginal Adenosis."]
  },
  "Mucinous Carcinoma": { clinical: "Large ovarian mass.", morphology: "Glands with mucin, expansile invasion.", ihc: "CK7+, CK20+, CDX2+.", pearls: ["Check appendix to rule out met."] },
  "LGSC": { clinical: "Younger women.", morphology: "Micropapillary, psammoma bodies.", ihc: "WT1+, p53 wt.", pearls: ["KRAS/BRAF mutations."] },
  "Borderline Tumor": { clinical: "Adnexal mass.", morphology: "Hierarchical branching, no destructive invasion.", ihc: "WT1+, p53 wt.", pearls: ["Non-invasive implants possible."] },
  "Uterine Leiomyosarcoma": { clinical: "Rapidly enlarging uterus.", morphology: "Spindle cells, severe atypia, necrosis.", ihc: "SMA+, p16+, p53 mut.", pearls: ["Coagulative tumor cell necrosis."] },
  "Endometrial Stromal Sarcoma (LG)": { clinical: "Uterine mass.", morphology: "Tongue-like invasion, spiral arterioles.", ihc: "CD10+, ER/PR+.", pearls: ["Resembles proliferative stroma."] },
  "High-grade Endometrial Stromal Sarcoma": { clinical: "Aggressive.", morphology: "High-grade round cells.", ihc: "Cyclin D1+, CD10 neg.", pearls: ["YWHAE-NUTM2 fusion."] },
  "Adenosarcoma": { clinical: "Polypoid mass.", morphology: "Benign glands, malignant stroma.", ihc: "Stromal condensation.", pearls: ["Phyllodes-like architecture."] },
  "STUMP": { clinical: "Uterine mass.", morphology: "Ambiguous features (necrosis vs atypia vs mitoses).", ihc: "p16 patchy, p53 wt.", pearls: ["Cannot definitively rule out malignancy."] },
  "PEComa (GYN)": { clinical: "Uterine mass.", morphology: "Epithelioid/spindle, clear cytoplasm.", ihc: "HMB45+, Cathepsin K+.", pearls: ["TSC1/2 mutations."] },
  "Adult Granulosa Cell Tumor": { clinical: "Estrogenic.", morphology: "Call-Exner bodies, grooved nuclei.", ihc: "Inhibin+, FOXL2+.", pearls: ["Coffee-bean nuclei."] },
  "Sertoli-Leydig Cell Tumor": { clinical: "Virilizing.", morphology: "Tubules, Leydig cells.", ihc: "Inhibin+, Calretinin+.", pearls: ["DICER1 mutations."] },
  "Sertoli Cell Tumor": {
    clinical: "Hormonally active (estrogen).",
    morphology: "Hollow or solid tubules lined by Sertoli cells.",
    ihc: "Inhibin+, Calretinin+, WT1+.",
    prognosis: "Usually benign.",
    differential: "Endometrioid Carcinoma.",
    pearls: ["Pure Sertoli tumors are rare."]
  },
  "Leydig Cell Tumor": {
    clinical: "Virilization, androgen excess.",
    morphology: "Sheets of eosinophilic polygonal cells. Reinke crystals.",
    ihc: "Inhibin+, Calretinin+, Melan-A+.",
    prognosis: "Benign.",
    differential: "Luteoma, Steroid Cell Tumor.",
    pearls: ["Reinke crystals are pathognomonic but seen in <50%."]
  },
  "Fibroma/Thecoma": { clinical: "Meigs syndrome.", morphology: "Spindle cells with collagen (Fibroma) or lipid (Thecoma).", ihc: "Inhibin (Thecoma), SF1.", pearls: ["Ovarian stromal origin."] },
  "Dysgerminoma": { clinical: "Young women.", morphology: "Nests of large cells, lymphocytes.", ihc: "SALL4+, OCT4+, CD117+.", pearls: ["Ovarian counterpart of Seminoma."] },
  "Yolk Sac Tumor": { clinical: "Elevated AFP.", morphology: "Schiller-Duval bodies, reticular.", ihc: "SALL4+, AFP+, Glypican-3.", pearls: ["Schiller-Duval bodies are pathognomonic."] },
  "Yolk Sac Tumor (Vagina)": {
    clinical: "Infant <3 years. Elevated AFP.",
    morphology: "Reticular pattern, hyaline globules. Schiller-Duval bodies rare.",
    ihc: "SALL4+, AFP+, Glypican-3+.",
    prognosis: "Chemosensitive.",
    differential: "Botryoid RMS.",
    pearls: ["Almost exclusively in infants."]
  },
  "Choriocarcinoma": { clinical: "High HCG.", morphology: "Biphasic (cyto + syncytio).", ihc: "HCG+, Inhibin+.", pearls: ["Hemorrhagic."] },
  "Vulvar SCC": { clinical: "Vulvar mass.", morphology: "Keratinizing squamous cells.", ihc: "p16 (if HPV+), p53 (if HPV-).", pearls: ["dVIN is precursor for HPV-neg."] },
  "Extramammary Paget Disease": { clinical: "Vulvar eczema.", morphology: "Intraepithelial adenocarcinoma cells.", ihc: "CK7+, GATA3+, HER2+.", pearls: ["Underlying adnexal ca vs primary."] },
  "STIC": { clinical: "Incidental tube.", morphology: "High-grade atypia, stratification.", ihc: "p53 mut, Ki67 high.", pearls: ["Precursor to HGSC."] },
  "SCCOHT": { clinical: "Young, hypercalcemia.", morphology: "Small round cells, follicle-like spaces.", ihc: "SMARCA4 loss, WT1+.", pearls: ["Rhabdoid features."] },
  "FATWO": { clinical: "Adnexal mass.", morphology: "Sieve-like, tubules.", ihc: "CD10+, Inhibin-, Calretinin-.", pearls: ["Wolffian origin."] },
  "Aggressive Angiomyxoma": { clinical: "Deep pelvic/vulvar.", morphology: "Hypocellular, myxoid, thick vessels.", ihc: "ER/PR+, HMGA2+.", pearls: ["Infiltrative borders, no capsule."] },
  "PSTT": { clinical: "Post-pregnancy.", morphology: "Intermediate trophoblast, infiltration.", ihc: "hPL++, Ki67 10-30%.", pearls: ["Absence of villi."] },
  "ETT": { clinical: "Cervix/Uterus.", morphology: "Nests of chorionic-type intermediate trophoblast.", ihc: "p63+, Ki67 >10%.", pearls: ["Geographic necrosis."] },
  "Struma Ovarii": { clinical: "Teratoma.", morphology: "Thyroid tissue.", ihc: "TTF1+, Thyroglobulin+.", pearls: ["Can have papillary thyroid ca."] },
  "Gonadoblastoma": { clinical: "Dysgenetic gonad.", morphology: "Nests of germ cells + sex cord cells.", ihc: "OCT4+, Inhibin+.", pearls: ["Calcifications common."] },
  "UTROSCT": { clinical: "Uterine mass.", morphology: "Sex cord-like, rhabdoid features.", ihc: "Polyphenotypic (Keratin, Desmin, Sex cord markers).", pearls: ["GREB1-NCOA1 fusion."] },
  "LAMN": { clinical: "Appendix/Ovary.", morphology: "Mucin, low-grade epithelium.", ihc: "CK20+, CDX2+.", pearls: ["Pseudomyxoma peritonei risk."] },
  "Cervical SCC": { clinical: "Cervix mass.", morphology: "Invasive squamous nests.", ihc: "p16+ (usually).", pearls: ["HPV-driven."] },
  "Endocervical Adeno HPV+": { clinical: "Cervix mass.", morphology: "Apical mitoses, apoptotic bodies.", ihc: "p16+, HPV RNA+.", pearls: ["Usual type."] },
  "Gastric-type Adeno": { clinical: "Cervix mass.", morphology: "Voluminous clear/eosinophilic cytoplasm.", ihc: "MUC6+, p16-, p53 mut.", pearls: ["Aggressive behavior."] },
  "Adenoid Cystic Ca": { clinical: "Cervix/Vulva.", morphology: "Cribriform, cylinders.", ihc: "CD117+, MYB+.", pearls: ["MYB fusion."] },
  "Mesonephric-like Adeno": { clinical: "Uterus/Ovary.", morphology: "Tubules, eosinophilic colloid.", ihc: "GATA3+, TTF1+, CD10(luminal).", pearls: ["GATA3 positive."] },
  "HSIL": { clinical: "Pap smear.", morphology: "Full thickness atypia.", ihc: "p16 block.", pearls: ["CIN 3."] },
  "dVIN": { clinical: "Lichen sclerosus.", morphology: "Basal atypia, elongation.", ihc: "p53 mut, p16-.", pearls: ["Precursor to HPV-neg SCC."] },
  "Steroid Cell Tumor": { clinical: "Virilization.", morphology: "Vacuolated/Eosinophilic cytoplasm.", ihc: "Inhibin+, Calretinin+.", pearls: ["Reinke crystals in Leydig."] },
  "Endometriosis": { clinical: "Pain.", morphology: "Glands, Stroma, Hemosiderin.", ihc: "CD10+, PAX8+.", pearls: ["Must have 2 of 3 features."] },
  "Adenomyosis": { clinical: "Uterine enlargement.", morphology: "Endometrium in myometrium.", pearls: ["Associated with hypertrophy."] },
  "Massive Ovarian Edema": { clinical: "Young.", morphology: "Edema, spared follicles.", pearls: ["Preserves ovarian structure."] },
  "Luteoma of Pregnancy": { clinical: "Pregnancy.", morphology: "Solid, eosinophilic cells.", pearls: ["Regresses postpartum."] },
  "Hyperreactio Luteinalis": { clinical: "Molar pregnancy.", morphology: "Multiple cysts, luteinized.", pearls: ["hCG effect."] },
  "Placental Site Nodule": { clinical: "Incidental.", morphology: "Hyalinized nodules, intermediate trophoblast.", ihc: "p63+, Ki67 low.", pearls: ["Benign."] },
  "Lichen Sclerosus": { clinical: "Vulvar itch.", morphology: "Atrophic epidermis, homogenized collagen.", pearls: ["Risk of SCC."] },
  "Tubo-Ovarian Abscess": { clinical: "PID.", morphology: "Neutrophils, destruction.", pearls: ["Acute inflammation."] },
  "Hydrosalpinx": { clinical: "Infertility.", morphology: "Dilated tube, plicae bridging.", pearls: ["Chronic salpingitis."] },
  "MGH": { clinical: "OCP use.", morphology: "Cribriform, neutrophils.", ihc: "p16 patchy.", pearls: ["Mimics adenocarcinoma."] },
  "Tunneled Clusters": { clinical: "Multiparous.", morphology: "Cystic dilation, no atypia.", pearls: ["Involutional change."] },
  "Endocervical Polyp": { clinical: "Bleeding.", morphology: "Fibrous core, mucinous epithelium.", pearls: ["Common benign lesion."] },
  "Nabothian Cyst": { clinical: "Cervix.", morphology: "Mucin-filled cyst.", pearls: ["Blocked gland."] },
  "Condyloma": { clinical: "Wart.", morphology: "Koilocytes, papillomatosis.", pearls: ["HPV 6/11."] },
  "Lichen Planus": { clinical: "Itch.", morphology: "Saw-tooth rete, band-like inflammation.", pearls: ["Civatte bodies."] },
  "Lichen Simplex Chronicus": { clinical: "Scratching.", morphology: "Hyperkeratosis, hypergranulosis.", pearls: ["Vertical collagen streaks."] },
  "Arias-Stella": { clinical: "Pregnancy.", morphology: "Clear cells, hobnail, hyperchromasia.", ihc: "Ki67 low.", pearls: ["No mitoses."] },
  "Tubal Metaplasia": { clinical: "Cervix.", morphology: "Cilia.", ihc: "p16 patchy.", pearls: ["Benign mimic of AIS."] },
  "Walthard Cell Rest": { clinical: "Fallopian tube.", morphology: "Transitional cells.", pearls: ["Coffee-bean nuclei."] },
  "VAIN": { clinical: "HPV.", morphology: "Dysplasia.", ihc: "p16 block.", pearls: ["Post-hysterectomy."] },
  "Vaginal SCC": {
    clinical: "Vaginal bleeding, mass.",
    morphology: "Nests of squamous cells, keratin pearls.",
    ihc: "p16+ (if HPV associated), p63+, p40+.",
    prognosis: "Variable.",
    differential: "Cervical/Vulvar SCC (metastasis).",
    pearls: ["Primary Vaginal SCC is rare; exclude mets first."]
  },
  "Vaginal Adenosis": { clinical: "DES exposure.", morphology: "Glandular epithelium in vagina.", pearls: ["Precursor to Clear Cell Ca."] },
  "Vaginal Melanoma": { clinical: "Mass.", morphology: "Mucosal melanoma.", ihc: "S100+, HMB45+.", pearls: ["Poor prognosis."] },
  "Spindle Cell Epithelioma": { clinical: "Vagina.", morphology: "Mixed tumor, biphasic.", pearls: ["Low-grade recurrence."] },
  "Fibroepithelial Polyp": {
    clinical: "Vagina/Vulva/Cervix.",
    morphology: "Central fibrovascular core, stellate stromal cells.",
    ihc: "Desmin+, CD34+, ER/PR+.",
    prognosis: "Benign.",
    differential: "Botryoid RMS.",
    pearls: ["'Pseudosarcomatous' atypia can be seen."]
  },
  "Mesothelial Hyperplasia": { clinical: "Hernia sac.", morphology: "Small nodules, no invasion.", ihc: "Calretinin+.", pearls: ["Reactive."] },
  "Postoperative Spindle Cell Nodule": { clinical: "Surgery.", morphology: "Mitoses, no atypia.", ihc: "SMA+, Keratin+/-.", pearls: ["History is key."] },
  "Ligneous Cervicitis": { clinical: "Woody cervix.", morphology: "Fibrin deposition.", pearls: ["Plasminogen deficiency."] },
  "Malakoplakia": { clinical: "E. coli.", morphology: "Michaelis-Gutmann bodies.", ihc: "CD68+.", pearls: ["Von Hansemann cells."] },
  "Xanthogranulomatous Inflammation": { clinical: "Mass.", morphology: "Foamy histiocytes.", pearls: ["Mimics cancer."] },
  "Zoon's Vulvitis": { clinical: "Inflammation.", morphology: "Plasma cells.", pearls: ["Band-like."] },
  "Mesonephric Remnants": { clinical: "Cervix.", morphology: "Lateral wall, tubules.", ihc: "GATA3+.", pearls: ["No atypia."] },
  "Amputation Neuroma": { clinical: "Pain.", morphology: "Disorganized nerves.", ihc: "S100+.", pearls: ["Traumatic."] },
  "Cervical Deciduosis": { clinical: "Pregnancy.", morphology: "Decidua in cervix.", pearls: ["Eosinophilic cytoplasm."] },
  "Decidualized Endometrioma": {
    clinical: "Pregnant patient, ovarian cyst.",
    morphology: "Eosinophilic decidual cells in cyst wall.",
    ihc: "Inhibin-, Calretinin-.",
    prognosis: "Benign.",
    differential: "Malignancy (solid component).",
    pearls: ["Regresses postpartum."]
  },
  "Adenomatoid Tumor": { clinical: "Incidental.", morphology: "Gland-like, flattened.", ihc: "Calretinin+.", pearls: ["Thread-like bridging."] },
  "Cotyledonoid Dissecting Leiomyoma": { clinical: "Mass.", morphology: "Hydropic smooth muscle.", pearls: ["Benign behavior."] },
  "Intravenous Leiomyomatosis": { clinical: "Vascular invasion.", morphology: "Benign smooth muscle in veins.", pearls: ["Can reach heart."] },
  "Sclerosing Stromal Tumor": { clinical: "Young.", morphology: "Pseudolobular, hemangiopericytoma-like.", ihc: "Inhibin+.", pearls: ["Sharply demarcated."] },
  "Endosalpingiosis": { clinical: "Incidental.", morphology: "Tubal glands, psammoma.", ihc: "PAX8+.", pearls: ["No stroma."] },
  "Botryoid RMS": { clinical: "Child, grape-like.", morphology: "Cambium layer.", ihc: "Myogenin+.", pearls: ["Subepithelial condensation."] },
  "Brenner Tumor": { clinical: "Incidental.", morphology: "Transitional epithelium nests.", ihc: "p63+, GATA3+.", pearls: ["Coffee-bean nuclei."] },
  "Seromucinous Borderline Tumor": { clinical: "Mass.", morphology: "Papillary, mixed cell types.", ihc: "ER+, PR+.", pearls: ["Indolent."] },
  "Malignant PEComa": { clinical: "Mass.", morphology: "Epithelioid, clear cells.", ihc: "HMB45+, Cathepsin K+.", pearls: ["Malignant potential."] },
  "Large Cell Neuroendocrine Ca": { clinical: "Aggressive.", morphology: "Large cells, neuroendocrine features.", ihc: "Synaptophysin+, Chromogranin+.", pearls: ["High grade."] },
  "Endometrial Stromal Nodule": { clinical: "Circumscribed.", morphology: "Stromal cells.", ihc: "CD10+.", pearls: ["Non-invasive."] },

  // --- Breast ---
  "Fat Necrosis (Breast)": { clinical: "Mass, history of trauma.", morphology: "Foamy macrophages, giant cells, fibrosis.", pearls: ["Can mimic carcinoma clinically."] },
  "Granulomatous Mastitis": { clinical: "Mass, inflammation.", morphology: "Lobulocentric granulomas.", pearls: ["Exclude infection first."] },
  "Intraductal Papilloma": { clinical: "Nipple discharge.", morphology: "Fibrovascular cores within dilated duct.", ihc: "Myoepithelial markers (p63/CK5/6) intact.", pearls: ["Benign if myoepithelium present."] },
  "DCIS": { clinical: "Calcifications on mammo.", morphology: "Proliferation of malignant ductal cells in situ.", ihc: "E-cad+, Myoepithelium intact.", pearls: ["Comedo necrosis is high grade."] },
  "LCIS": { clinical: "Incidental.", morphology: "Solid proliferation of small cells, filling lobules.", ihc: "E-cad negative.", pearls: ["Risk marker, not obligate precursor."] },
  "ADH": { clinical: "Calcifications.", morphology: "Monotonous proliferation but limited extent (<2mm).", pearls: ["Low grade DCIS mimic."] },
  "Radial Scar": { clinical: "Spiculated lesion.", morphology: "Fibroelastotic core with entrapped glands.", pearls: ["Benign but can mimic carcinoma."] },
  "Paget Disease (Breast)": { clinical: "Eczematous nipple.", morphology: "Large atypical cells in epidermis.", ihc: "CK7+, HER2+.", pearls: ["Almost always associated with underlying DCIS/IDC."] },

  // --- GU ---
  "Metanephric Adenoma": { clinical: "Renal mass.", morphology: "Small blue tubules, psammoma bodies.", ihc: "WT1+, CD57+, BRAF V600E.", pearls: ["Benign mimic of Wilms/Papillary RCC."] },
  "Clear Cell Sarcoma of Kidney": { clinical: "Pediatric renal mass.", morphology: "Cord cells, clear cytoplasm.", ihc: "BCOR+, Cyclin D1+.", pearls: ["Bone metastasizing renal tumor."] },
  "Rhabdoid Tumor (Kidney)": { clinical: "Infant, aggressive.", morphology: "Rhabdoid cells, prominent nucleoli.", ihc: "INI1 (SMARCB1) Loss.", pearls: ["High grade."] },
  "Xanthogranulomatous Pyelonephritis": { clinical: "Staghorn calculus.", morphology: "Foamy histiocytes, inflammation.", pearls: ["Mimics RCC grossly."] },
  "Malakoplakia (Kidney)": { clinical: "UTI history.", morphology: "Von Hansemann cells, Michaelis-Gutmann bodies.", ihc: "CD68+, PAS-D+.", pearls: ["Defective phagosomes."] },
  "Inverted Papilloma": { clinical: "Bladder mass.", morphology: "Inverted cords of urothelium.", pearls: ["Benign."] },
  "Nephrogenic Adenoma": { clinical: "Bladder/Ureter lesion.", morphology: "Tubules, hobnail cells.", ihc: "PAX8+, NKX3.1+.", pearls: ["Mimics carcinoma."] },
  "Cystitis Cystica": { clinical: "Bladder inflammation.", morphology: "Von Brunn nests with cysts.", pearls: ["Benign."] },
  "PIN": { clinical: "Biopsy finding.", morphology: "Atypical cells in preexisting ducts.", ihc: "Basal cells intact.", pearls: ["High grade PIN warrants follow-up."] },
  "ASAP": { clinical: "Biopsy finding.", morphology: "Small atypical glands, suspicious but not diagnostic.", pearls: ["Re-biopsy recommended."] },
  "Teratoma (Testis)": { clinical: "Testicular mass.", morphology: "Mature/Immature tissues.", pearls: ["Post-pubertal is malignant."] },
  "Adenomatoid Tumor (Epididymis)": { clinical: "Paratesticular mass.", morphology: "Mesothelial origin.", ihc: "Calretinin+.", pearls: ["Most common paratesticular tumor."] },

  // --- Thoracic ---
  "Large Cell Neuroendocrine Ca (Lung)": { clinical: "Lung mass.", morphology: "Large cells, NE morphology, mitoses.", ihc: "NE markers positive.", pearls: ["High grade, excludes Small Cell."] },
  "Lung Carcinoid": { clinical: "Endobronchial mass.", morphology: "Nests, salt-and-pepper chromatin.", ihc: "Synapto+, Chromo+.", pearls: ["Typical (<2 mitoses) vs Atypical."] },
  "Hamartoma (Lung)": { clinical: "Coin lesion.", morphology: "Cartilage, fat, clefts.", pearls: ["Benign."] },
  "Solitary Fibrous Tumor (Pleura)": { clinical: "Pleural mass.", morphology: "Patternless spindle cells.", ihc: "STAT6+.", pearls: ["Previously localized mesothelioma."] },
  "Organizing Pneumonia": { clinical: "Consolidation.", morphology: "Fibroblast plugs (Masson bodies).", pearls: ["Response to injury."] },
  "Sarcoidosis": { clinical: "Hilar adenopathy.", morphology: "Non-necrotizing granulomas.", pearls: ["Diagnosis of exclusion."] },
  "Mediastinal Germ Cell Tumor": { clinical: "Mediastinal mass.", morphology: "Seminoma/Teratoma/Yolk Sac.", ihc: "SALL4+, OCT4+ (Seminoma).", pearls: ["Young males."] },

  // --- GI ---
  "Barrett Esophagus": { clinical: "GERD.", morphology: "Intestinal metaplasia (goblet cells).", pearls: ["Risk of adenocarcinoma."] },
  "Esophageal Adenocarcinoma": { clinical: "Dysphagia.", morphology: "Glandular dysplasia/invasion.", ihc: "CK7+, CK20-.", pearls: ["Arises from Barrett's."] },
  "Gastric Adenocarcinoma": { clinical: "Weight loss.", morphology: "Intestinal or Diffuse (Signet ring).", ihc: "Keratin+, E-cad loss (diffuse).", pearls: ["Linitis plastica."] },
  "Chronic Gastritis": { clinical: "Dyspepsia.", morphology: "Lymphoplasmacytic infiltrate.", ihc: "H. pylori stain.", pearls: ["Atrophy/Metaplasia risk."] },
  "Fundic Gland Polyp": { clinical: "PPI use.", morphology: "Dilated oxyntic glands.", pearls: ["Benign."] },
  "Hyperplastic Polyp": { clinical: "Gastric/Colon.", morphology: "Foveolar hyperplasia, serrated surface.", pearls: ["Benign."] },
  "Tubular Adenoma": { clinical: "Screening.", morphology: "Dysplastic epithelium, tubular.", pearls: ["Precursor to CRC."] },
  "Sessile Serrated Lesion": { clinical: "Right colon.", morphology: "Boot-shaped crypts, serration to base.", molecular: "BRAF mutation.", pearls: ["MMR pathway precursor."] },
  "Neuroendocrine Tumor (GI)": { clinical: "Carcinoid syndrome.", morphology: "Nests/Trabeculae, salt-and-pepper.", ihc: "Synapto+, Chromo+.", pearls: ["Grade by Ki67."] },
  "IBD": { clinical: "Diarrhea/Pain.", morphology: "Crypt abscesses, distortion (UC) vs Granulomas (Crohn's).", pearls: ["Chronic active colitis."] },
  "Peutz-Jeghers Polyp": { clinical: "Hamartoma.", morphology: "Arborizing smooth muscle.", pearls: ["STK11 mutation."] },
  "Hepatic Adenoma": { clinical: "OCP use.", morphology: "Hepatocytes without portal tracts.", pearls: ["Subtypes: HNF1a, Inflammatory, Beta-catenin."] },
  "Focal Nodular Hyperplasia": { clinical: "Liver mass.", morphology: "Central scar, nodular hepatocytes.", ihc: "Glutamine Synthetase (Map-like).", pearls: ["Benign."] },
  "Solid Pseudopapillary Neoplasm": { clinical: "Young women, pancreas.", morphology: "Pseudopapillae, grooves.", ihc: "Beta-catenin (nuclear), CD10+.", pearls: ["Low grade malignancy."] },
  "IPMN": { clinical: "Cystic pancreas.", morphology: "Mucinous papillary epithelium.", pearls: ["Main duct vs Side branch."] },

  // --- Neuro ---
  "Oligodendroglioma": { clinical: "Seizures.", morphology: "Fried egg cells, chicken-wire vessels.", ihc: "IDH1+, ATRX retained.", molecular: "1p/19q codeletion.", pearls: ["Calcifications common."] },
  "Ependymoma": { clinical: "Ventricle/Spine.", morphology: "Perivascular pseudorosettes.", ihc: "GFAP+, EMA (dot).", pearls: ["ZFTA fusion in supratentorial."] },
  "Pilocytic Astrocytoma": { clinical: "Cerebellum (child).", morphology: "Biphasic, Rosenthal fibers.", molecular: "BRAF fusion.", pearls: ["WHO Grade 1."] },
  "Hemangioblastoma": { clinical: "Cerebellum/Spine.", morphology: "Stromal cells + capillaries.", ihc: "Inhibin+, CA9+.", pearls: ["VHL association."] },
  "Craniopharyngioma": { clinical: "Suprasellar.", morphology: "Adamantinomatous (wet keratin) or Papillary.", molecular: "CTNNB1 (Adamantinomatous) or BRAF (Papillary).", pearls: ["Machine oil fluid."] },
  "Pituitary Adenoma": { clinical: "Hormonal excess.", morphology: "Monomorphic cells, loss of reticulin.", ihc: "Pituitary hormones, Transcription factors (PIT1, TPIT, SF1).", pearls: ["Neuroendocrine."] },
  "Primary CNS Lymphoma": { clinical: "Mass, HIV.", morphology: "Perivascular lymphocytes.", ihc: "CD20+.", pearls: ["DLBCL type usually."] },

  // --- Head & Neck ---
  "Warthin Tumor": { clinical: "Parotid tail.", morphology: "Papillary, oncocytic + lymphoid stroma.", pearls: ["Smokers, benign."] },
  "Mucoepidermoid Carcinoma": { clinical: "Salivary mass.", morphology: "Mucous + Squamous + Intermediate cells.", molecular: "MAML2 fusion.", pearls: ["Most common malignant salivary."] },
  "Adenoid Cystic Ca (Salivary)": { clinical: "Painful mass.", morphology: "Cribriform, tubular.", ihc: "CD117+, MYB+.", pearls: ["Perineural invasion."] },
  "Acinic Cell Carcinoma": { clinical: "Parotid.", morphology: "Serous acinar cells (zymogen granules).", ihc: "DOG1+.", pearls: ["Low grade."] },
  "Follicular Adenoma": { clinical: "Thyroid nodule.", morphology: "Encapsulated follicles.", pearls: ["Diagnosis requires full capsule eval."] },
  "Hashimoto Thyroiditis": { clinical: "Hypothyroid.", morphology: "Lymphoid follicles, Hurthle cells.", pearls: ["Autoimmune."] },
  "Olfactory Neuroblastoma": { clinical: "Nasal mass.", morphology: "Lobules, neuropil.", ihc: "Synapto+, S100 (sustentacular).", pearls: ["Hyams grading."] },
  "Paraganglioma": { clinical: "Neck mass.", morphology: "Zellballen.", ihc: "Synapto+, S100 (sustentacular).", pearls: ["Carotid body."] }
};