// Generated by scripts/generate_lecture_abpath_spec_seeds.cjs.
// Keep this file small: it gives the browser lecture-specific ABPath crosswalks
// without importing the full syllabus.normalized.json into the runtime bundle.

export interface LectureAbpathSpecTopicSeed {
  title: string;
  category: string;
  designation: 'C' | 'AR' | string;
  path: string;
  sourceLine?: number;
}

export const lectureAbpathSpecSeeds: Record<string, LectureAbpathSpecTopicSeed[]> = {
  "renal_mass_eval": [
    {
      "title": "Tissue processing of renal biopsies",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > Kidney > Medical Kidney Disease > Tissue processing of renal biopsies",
      "sourceLine": 741
    },
    {
      "title": "End Stage Renal Disease",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > Kidney > Medical Kidney Disease > End Stage Renal Disease",
      "sourceLine": 653
    },
    {
      "title": "Monoclonal gammopathy associated renal disease",
      "category": "ap_gu",
      "designation": "AR",
      "path": "The Genitourinary System > Kidney > Medical Kidney Disease > Monoclonal gammopathy associated renal disease",
      "sourceLine": 625
    },
    {
      "title": "Renal transplantation, donor assessment",
      "category": "ap_gu",
      "designation": "AR",
      "path": "The Genitourinary System > Kidney > Medical Kidney Disease > Renal transplantation, donor assessment",
      "sourceLine": 655
    },
    {
      "title": "Diseases associated with acellular closure of glomerular capillaries",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > Kidney > Medical Kidney Disease > Diseases associated with acellular closure of glomerular capillaries",
      "sourceLine": 608
    },
    {
      "title": "Non-proliferative glomerulonephropathies",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > Kidney > Medical Kidney Disease > Non-proliferative glomerulonephropathies",
      "sourceLine": 576
    },
    {
      "title": "Pyelonephritis",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > Kidney > Medical Kidney Disease > Pyelonephritis",
      "sourceLine": 662
    },
    {
      "title": "Tubulointerstitial Disease",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > Kidney > Medical Kidney Disease > Tubulointerstitial Disease",
      "sourceLine": 627
    },
    {
      "title": "Vascular lesions",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > Kidney > Medical Kidney Disease > Vascular lesions",
      "sourceLine": 640
    },
    {
      "title": "Acute diffuse intracapillary proliferative glomerulonephritis",
      "category": "ap_gu",
      "designation": "AR",
      "path": "The Genitourinary System > Kidney > Medical Kidney Disease > Acute diffuse intracapillary proliferative glomerulonephritis",
      "sourceLine": 504
    }
  ],
  "testicular_mass_eval": [
    {
      "title": "Intratubular germ cell neoplasia",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Testis > Intratubular germ cell neoplasia",
      "sourceLine": 1051
    },
    {
      "title": "Seminoma",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Testis > Seminoma",
      "sourceLine": 1052
    },
    {
      "title": "Spermatocytic seminoma",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Testis > Spermatocytic seminoma",
      "sourceLine": 1055
    },
    {
      "title": "Teratoma",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Testis > Teratoma",
      "sourceLine": 1053
    },
    {
      "title": "Spermatic cord/paratesticular tumors",
      "category": "ap_male_repro",
      "designation": "AR",
      "path": "Male Reproductive System > Testis > Plasmacytoma > Tumors of the tunica albuginea and mesothelium > Spermatic cord/paratesticular tumors",
      "sourceLine": 1078
    },
    {
      "title": "Embryonal carcinoma",
      "category": "ap_male_repro",
      "designation": "AR",
      "path": "Male Reproductive System > Testis > Embryonal carcinoma",
      "sourceLine": 1056
    },
    {
      "title": "Mixed germ cell tumor",
      "category": "ap_male_repro",
      "designation": "AR",
      "path": "Male Reproductive System > Testis > Mixed germ cell tumor",
      "sourceLine": 1059
    },
    {
      "title": "Other germ cell tumors",
      "category": "ap_male_repro",
      "designation": "AR",
      "path": "Male Reproductive System > Testis > Other germ cell tumors",
      "sourceLine": 1061
    },
    {
      "title": "Yolk sac tumor",
      "category": "ap_male_repro",
      "designation": "AR",
      "path": "Male Reproductive System > Testis > Yolk sac tumor",
      "sourceLine": 1057
    },
    {
      "title": "Cryptorchidism",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Testis > Cryptorchidism",
      "sourceLine": 982
    }
  ],
  "bladder_path_core_principles": [
    {
      "title": "BCG effects",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > BCG effects",
      "sourceLine": 762
    },
    {
      "title": "Nephrogenic metaplasia",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Nephrogenic metaplasia",
      "sourceLine": 755
    },
    {
      "title": "Radiation Changes",
      "category": "ap_gu",
      "designation": "AR",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Radiation Changes",
      "sourceLine": 754
    },
    {
      "title": "Diverticula",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Diverticula",
      "sourceLine": 757
    },
    {
      "title": "Other Congenital, Developmental, and Familial Conditions",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Other Congenital, Developmental, and Familial Conditions",
      "sourceLine": 759
    },
    {
      "title": "Urethral polyp",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Urethral polyp",
      "sourceLine": 761
    },
    {
      "title": "Normal Anatomy and Histology",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Normal Anatomy and Histology",
      "sourceLine": 752
    },
    {
      "title": "The Urothelial Tract and Bladder",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder",
      "sourceLine": 751
    },
    {
      "title": "Cystitis glandularis",
      "category": "ap_gu",
      "designation": "AR",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Cystitis glandularis",
      "sourceLine": 758
    },
    {
      "title": "Physiologic Changes, Metabolic Conditions & Trauma/Infarct",
      "category": "ap_gu",
      "designation": "AR",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct",
      "sourceLine": 753
    }
  ],
  "penile_who_complete_pathology": [
    {
      "title": "Penile intraepithelial neoplasia",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Penis > Lichen schlerosis > Penile intraepithelial neoplasia",
      "sourceLine": 1195
    },
    {
      "title": "Squamous cell carcinoma",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Penis > Lichen schlerosis > Bowenoid papulosis > Squamous cell carcinoma",
      "sourceLine": 1197
    },
    {
      "title": "Paget Disease",
      "category": "ap_male_repro",
      "designation": "AR",
      "path": "Male Reproductive System > Penis > Lichen schlerosis > Paget Disease",
      "sourceLine": 1198
    },
    {
      "title": "Bowenoid papulosis",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Penis > Lichen schlerosis > Bowenoid papulosis",
      "sourceLine": 1196
    },
    {
      "title": "Lichen schlerosis",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Penis > Lichen schlerosis",
      "sourceLine": 1135
    },
    {
      "title": "Penis",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Penis",
      "sourceLine": 1125
    }
  ],
  "testicular_who_complete_pathology": [
    {
      "title": "Seminoma",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Testis > Seminoma",
      "sourceLine": 1052
    },
    {
      "title": "Spermatocytic seminoma",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Testis > Spermatocytic seminoma",
      "sourceLine": 1055
    },
    {
      "title": "Teratoma",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Testis > Teratoma",
      "sourceLine": 1053
    },
    {
      "title": "Embryonal carcinoma",
      "category": "ap_male_repro",
      "designation": "AR",
      "path": "Male Reproductive System > Testis > Embryonal carcinoma",
      "sourceLine": 1056
    },
    {
      "title": "Mixed germ cell tumor",
      "category": "ap_male_repro",
      "designation": "AR",
      "path": "Male Reproductive System > Testis > Mixed germ cell tumor",
      "sourceLine": 1059
    },
    {
      "title": "Yolk sac tumor",
      "category": "ap_male_repro",
      "designation": "AR",
      "path": "Male Reproductive System > Testis > Yolk sac tumor",
      "sourceLine": 1057
    },
    {
      "title": "Cryptorchidism",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Testis > Cryptorchidism",
      "sourceLine": 982
    },
    {
      "title": "Duct obstruction, vasitis nodosum",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Testis > Duct obstruction, vasitis nodosum",
      "sourceLine": 1088
    },
    {
      "title": "Epidermoid cyst and dermoid cyst",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Testis > Epidermoid cyst and dermoid cyst",
      "sourceLine": 1054
    },
    {
      "title": "Intratubular germ cell neoplasia",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > Testis > Intratubular germ cell neoplasia",
      "sourceLine": 1051
    }
  ],
  "ioc-overview-breast-surgery": [
    {
      "title": "Ductal carcinoma in situ (DCIS)",
      "category": "ap_breast",
      "designation": "C",
      "path": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Ductal carcinoma in situ (DCIS)",
      "sourceLine": 346
    },
    {
      "title": "Invasive ductal carcinoma, NOS",
      "category": "ap_breast",
      "designation": "C",
      "path": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Invasive ductal carcinoma, NOS",
      "sourceLine": 347
    },
    {
      "title": "Invasive lobular carcinoma",
      "category": "ap_breast",
      "designation": "C",
      "path": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Invasive lobular carcinoma",
      "sourceLine": 419
    },
    {
      "title": "Lobular carcinoma in situ (LCIS)",
      "category": "ap_breast",
      "designation": "C",
      "path": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Lobular carcinoma in situ (LCIS)",
      "sourceLine": 418
    },
    {
      "title": "Radial Scar",
      "category": "ap_breast",
      "designation": "C",
      "path": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Radial Scar",
      "sourceLine": 328
    },
    {
      "title": "Invasive micropapillary carcinoma",
      "category": "ap_breast",
      "designation": "AR",
      "path": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Invasive micropapillary carcinoma",
      "sourceLine": 425
    },
    {
      "title": "Sentinel Node Sampling",
      "category": "ap_breast",
      "designation": "AR",
      "path": "Breast > Normal Cytology > Pregnancy and Lactational Changes > Sentinel Node Sampling",
      "sourceLine": 5728
    },
    {
      "title": "Adenosis",
      "category": "ap_breast",
      "designation": "C",
      "path": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Adenosis",
      "sourceLine": 325
    },
    {
      "title": "Apocrine Metaplasia",
      "category": "ap_breast",
      "designation": "C",
      "path": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Apocrine Metaplasia",
      "sourceLine": 323
    },
    {
      "title": "Cysts",
      "category": "ap_breast",
      "designation": "C",
      "path": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Cysts",
      "sourceLine": 324
    }
  ],
  "ioc-overview-endocrine-surgery": [
    {
      "title": "Medullary carcinoma",
      "category": "ap_endo",
      "designation": "AR",
      "path": "The Endocrine System > The Thyroid > Inflammatory, Metabolic, Non-Infectious & Infectious > Follicular carcinoma > Medullary carcinoma",
      "sourceLine": 2704
    },
    {
      "title": "Follicular carcinoma",
      "category": "ap_endo",
      "designation": "C",
      "path": "The Endocrine System > The Thyroid > Inflammatory, Metabolic, Non-Infectious & Infectious > Follicular carcinoma",
      "sourceLine": 2703
    },
    {
      "title": "Papillary carcinoma",
      "category": "ap_endo",
      "designation": "C",
      "path": "The Endocrine System > The Thyroid > Inflammatory, Metabolic, Non-Infectious & Infectious > Papillary carcinoma",
      "sourceLine": 2702
    },
    {
      "title": "Anaplastic carcinoma",
      "category": "ap_endo",
      "designation": "AR",
      "path": "The Endocrine System > The Thyroid > Inflammatory, Metabolic, Non-Infectious & Infectious > Anaplastic carcinoma",
      "sourceLine": 2706
    },
    {
      "title": "Follicular adenoma",
      "category": "ap_endo",
      "designation": "AR",
      "path": "The Endocrine System > The Thyroid > Inflammatory, Metabolic, Non-Infectious & Infectious > Follicular adenoma",
      "sourceLine": 2699
    },
    {
      "title": "Graves Disease",
      "category": "ap_endo",
      "designation": "AR",
      "path": "The Endocrine System > The Thyroid > Inflammatory, Metabolic, Non-Infectious & Infectious > Graves Disease",
      "sourceLine": 2694
    },
    {
      "title": "Other malignancies involving the thyroid",
      "category": "ap_endo",
      "designation": "C",
      "path": "The Endocrine System > The Thyroid > Inflammatory, Metabolic, Non-Infectious & Infectious > Lymphoma > Other malignancies involving the thyroid",
      "sourceLine": 2708
    },
    {
      "title": "Infections",
      "category": "ap_endo",
      "designation": "C",
      "path": "The Endocrine System > The Thyroid > Inflammatory, Metabolic, Non-Infectious & Infectious > Infections",
      "sourceLine": 2696
    },
    {
      "title": "Infectious",
      "category": "ap_endo",
      "designation": "C",
      "path": "The Endocrine System > The Thyroid > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Infectious",
      "sourceLine": 2676
    },
    {
      "title": "Oncocytic neoplasms",
      "category": "ap_endo",
      "designation": "C",
      "path": "The Endocrine System > The Thyroid > Inflammatory, Metabolic, Non-Infectious & Infectious > Oncocytic neoplasms",
      "sourceLine": 2700
    }
  ],
  "ioc-overview-gynecologic-oncology": [
    {
      "title": "Adenocarcinoma in situ",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > The Uterine Cervix > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Squamous cell carcinoma > Adenocarcinoma in situ",
      "sourceLine": 2988
    },
    {
      "title": "Clear cell carcinoma",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > The Uterine Cervix > Physiologic Changes, Metabolic Conditions, & Trauma/Infarct > Squamous cell carcinoma > Clear cell carcinoma",
      "sourceLine": 2970
    },
    {
      "title": "Adenosis",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > The Uterine Cervix > Physiologic Changes, Metabolic Conditions, & Trauma/Infarct > Adenosis",
      "sourceLine": 2961
    },
    {
      "title": "Endometriosis",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > The Uterine Cervix > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Endometriosis",
      "sourceLine": 2980
    },
    {
      "title": "Mesonephric rests and hyperplasia",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > The Uterine Cervix > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Mesonephric rests and hyperplasia",
      "sourceLine": 2978
    },
    {
      "title": "Microglandular hyperplasia",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > The Uterine Cervix > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Microglandular hyperplasia",
      "sourceLine": 2976
    },
    {
      "title": "Polyps",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > The Uterine Cervix > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Polyps",
      "sourceLine": 2984
    },
    {
      "title": "Squamous cell carcinoma",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > The Uterine Cervix > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Squamous cell carcinoma",
      "sourceLine": 2987
    },
    {
      "title": "Squamous intraepithelial lesions",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > The Uterine Cervix > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Squamous intraepithelial lesions",
      "sourceLine": 2986
    },
    {
      "title": "Stromal polyp",
      "category": "ap_male_repro",
      "designation": "C",
      "path": "Male Reproductive System > The Uterine Cervix > Physiologic Changes, Metabolic Conditions, & Trauma/Infarct > Stromal polyp",
      "sourceLine": 2966
    }
  ],
  "ioc-overview-head-neck-surgery": [
    {
      "title": "Infections of the Jaws & Oral Cavity",
      "category": "ap_hn",
      "designation": "C",
      "path": "Head and Neck > Jaws, Oral Cavity, and Oropharynx > Pyogenic granuloma > Infections of the Jaws & Oral Cavity",
      "sourceLine": 1459
    },
    {
      "title": "Pyogenic granuloma",
      "category": "ap_hn",
      "designation": "C",
      "path": "Head and Neck > Jaws, Oral Cavity, and Oropharynx > Pyogenic granuloma",
      "sourceLine": 1403
    },
    {
      "title": "Jaws, Oral Cavity, and Oropharynx",
      "category": "ap_hn",
      "designation": "C",
      "path": "Head and Neck > Jaws, Oral Cavity, and Oropharynx",
      "sourceLine": 1393
    },
    {
      "title": "Lichen planus",
      "category": "ap_hn",
      "designation": "AR",
      "path": "Head and Neck > Jaws, Oral Cavity, and Oropharynx > Pyogenic granuloma > Lichen planus",
      "sourceLine": 1460
    },
    {
      "title": "Peripheral giant cell granuloma",
      "category": "ap_hn",
      "designation": "AR",
      "path": "Head and Neck > Jaws, Oral Cavity, and Oropharynx > Pyogenic granuloma > Peripheral giant cell granuloma",
      "sourceLine": 1461
    },
    {
      "title": "Sinonasal undifferentiated carcinoma",
      "category": "ap_hn",
      "designation": "AR",
      "path": "Head and Neck > Larynx > Sinonasal undifferentiated carcinoma",
      "sourceLine": 1673
    },
    {
      "title": "Schneiderian papilloma",
      "category": "ap_hn",
      "designation": "C",
      "path": "Head and Neck > Larynx > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Squamous papilloma > Schneiderian papilloma",
      "sourceLine": 1651
    },
    {
      "title": "Angiofibroma",
      "category": "ap_hn",
      "designation": "C",
      "path": "Head and Neck > Larynx > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Angiofibroma",
      "sourceLine": 1653
    },
    {
      "title": "Contact ulcer",
      "category": "ap_hn",
      "designation": "C",
      "path": "Head and Neck > Larynx > Paraganglioma > Contact ulcer",
      "sourceLine": 1695
    },
    {
      "title": "Cysts",
      "category": "ap_hn",
      "designation": "C",
      "path": "Head and Neck > Larynx > Paraganglioma > Cysts",
      "sourceLine": 1696
    }
  ],
  "ioc-overview-hepatobiliary-surgery": [
    {
      "title": "Cirrhosis",
      "category": "ap_gi",
      "designation": "C",
      "path": "The Digestive System > The Liver and Biliary Tract > Physiologic Changes, Metabolic Conditions, & Trauma/Infarct > Cirrhosis",
      "sourceLine": 2388
    },
    {
      "title": "Hepatocellular adenoma",
      "category": "ap_gi",
      "designation": "AR",
      "path": "The Digestive System > The Liver and Biliary Tract > Physiologic Changes, Metabolic Conditions, & Trauma/Infarct > Hepatocellular adenoma",
      "sourceLine": 2408
    },
    {
      "title": "Hepatocellular carcinoma",
      "category": "ap_gi",
      "designation": "AR",
      "path": "The Digestive System > The Liver and Biliary Tract > Physiologic Changes, Metabolic Conditions, & Trauma/Infarct > Hepatocellular carcinoma",
      "sourceLine": 2411
    },
    {
      "title": "Macroregenerative nodules in cirrhosis",
      "category": "ap_gi",
      "designation": "AR",
      "path": "The Digestive System > The Liver and Biliary Tract > Physiologic Changes, Metabolic Conditions, & Trauma/Infarct > Macroregenerative nodules in cirrhosis",
      "sourceLine": 2376
    },
    {
      "title": "Polycystic liver disease and congenital hepatic fibrosis",
      "category": "ap_gi",
      "designation": "AR",
      "path": "The Digestive System > The Liver and Biliary Tract > Physiologic Changes, Metabolic Conditions, & Trauma/Infarct > Polycystic liver disease and congenital hepatic fibrosis",
      "sourceLine": 2382
    },
    {
      "title": "Alcoholic liver disease",
      "category": "ap_gi",
      "designation": "C",
      "path": "The Digestive System > The Liver and Biliary Tract > Physiologic Changes, Metabolic Conditions, & Trauma/Infarct > Alcoholic liver disease",
      "sourceLine": 2386
    },
    {
      "title": "Amebic abscess",
      "category": "ap_gi",
      "designation": "C",
      "path": "The Digestive System > The Liver and Biliary Tract > Physiologic Changes, Metabolic Conditions, & Trauma/Infarct > Amebic abscess",
      "sourceLine": 2389
    },
    {
      "title": "Cholecystitis and cholelithiasis",
      "category": "ap_gi",
      "designation": "C",
      "path": "The Digestive System > The Liver and Biliary Tract > Physiologic Changes, Metabolic Conditions, & Trauma/Infarct > Cholecystitis and cholelithiasis",
      "sourceLine": 2536
    },
    {
      "title": "Echinococcosis",
      "category": "ap_gi",
      "designation": "C",
      "path": "The Digestive System > The Liver and Biliary Tract > Physiologic Changes, Metabolic Conditions, & Trauma/Infarct > Echinococcosis",
      "sourceLine": 2391
    },
    {
      "title": "Focal nodular hyperplasia",
      "category": "ap_gi",
      "designation": "C",
      "path": "The Digestive System > The Liver and Biliary Tract > Physiologic Changes, Metabolic Conditions, & Trauma/Infarct > Focal nodular hyperplasia",
      "sourceLine": 2405
    }
  ],
  "ioc-overview-neuropathology": [
    {
      "title": "Spinal Cord and Vascular Supply",
      "category": "ap_neuro",
      "designation": "C",
      "path": "Neuropathology Topics for Anatomic Pathology Residents > General: Neuroanatomy, Histology, Pathologic Responses, and Diagnostic Considerations > Neuroanatomy > Deep (Basal) Nuclei, Brain Stem, and Cerebellum > Spinal Cord and Vascular Supply",
      "sourceLine": 12817
    },
    {
      "title": "A-beta-related Angiitis (ABRA)",
      "category": "ap_neuro",
      "designation": "AR",
      "path": "Neuropathology Topics for Anatomic Pathology Residents > General: Neuroanatomy, Histology, Pathologic Responses, and Diagnostic Considerations > Vascular Disorders > Brain Hemorrhage > A-beta-related Angiitis (ABRA)",
      "sourceLine": 13454
    },
    {
      "title": "Anaplastic Meningioma",
      "category": "ap_neuro",
      "designation": "AR",
      "path": "Neuropathology Topics for Anatomic Pathology Residents > General: Neuroanatomy, Histology, Pathologic Responses, and Diagnostic Considerations > Atypical Neurofibromatous Neoplasm of Uncertain Biologic > Atypical Meningioma > Anaplastic Meningioma",
      "sourceLine": 14460
    },
    {
      "title": "Epithelioid Malignant Peripheral Nerve Sheath Tumor",
      "category": "ap_neuro",
      "designation": "AR",
      "path": "Neuropathology Topics for Anatomic Pathology Residents > General: Neuroanatomy, Histology, Pathologic Responses, and Diagnostic Considerations > Atypical Neurofibromatous Neoplasm of Uncertain Biologic > Hybrid Nerve Sheath Tumors > Epithelioid Malignant Peripheral Nerve Sheath Tumor",
      "sourceLine": 14454
    },
    {
      "title": "Meningioma, Angiomatous",
      "category": "ap_neuro",
      "designation": "AR",
      "path": "Neuropathology Topics for Anatomic Pathology Residents > General: Neuroanatomy, Histology, Pathologic Responses, and Diagnostic Considerations > Atypical Neurofibromatous Neoplasm of Uncertain Biologic > Meningioma, Transitional (Mixed) > Meningioma, Angiomatous",
      "sourceLine": 14465
    },
    {
      "title": "Meningioma, Chordoid Type",
      "category": "ap_neuro",
      "designation": "AR",
      "path": "Neuropathology Topics for Anatomic Pathology Residents > General: Neuroanatomy, Histology, Pathologic Responses, and Diagnostic Considerations > Atypical Neurofibromatous Neoplasm of Uncertain Biologic > Meningioma, Lymphoplasmacyte-Rich > Meningioma, Chordoid Type",
      "sourceLine": 14560
    },
    {
      "title": "Meningioma, Clear Cell Type",
      "category": "ap_neuro",
      "designation": "AR",
      "path": "Neuropathology Topics for Anatomic Pathology Residents > General: Neuroanatomy, Histology, Pathologic Responses, and Diagnostic Considerations > Atypical Neurofibromatous Neoplasm of Uncertain Biologic > Meningioma, Lymphoplasmacyte-Rich > Meningioma, Clear Cell Type",
      "sourceLine": 14559
    },
    {
      "title": "Meningioma, Metaplastic",
      "category": "ap_neuro",
      "designation": "AR",
      "path": "Neuropathology Topics for Anatomic Pathology Residents > General: Neuroanatomy, Histology, Pathologic Responses, and Diagnostic Considerations > Atypical Neurofibromatous Neoplasm of Uncertain Biologic > Meningioma, Lymphoplasmacyte-Rich > Meningioma, Metaplastic",
      "sourceLine": 14469
    },
    {
      "title": "Meningioma, Other Types",
      "category": "ap_neuro",
      "designation": "AR",
      "path": "Neuropathology Topics for Anatomic Pathology Residents > General: Neuroanatomy, Histology, Pathologic Responses, and Diagnostic Considerations > Atypical Neurofibromatous Neoplasm of Uncertain Biologic > Meningioma, Papillary Type > Meningioma, Other Types",
      "sourceLine": 14563
    },
    {
      "title": "Meningioma, Psammomatous",
      "category": "ap_neuro",
      "designation": "AR",
      "path": "Neuropathology Topics for Anatomic Pathology Residents > General: Neuroanatomy, Histology, Pathologic Responses, and Diagnostic Considerations > Atypical Neurofibromatous Neoplasm of Uncertain Biologic > Meningioma, Transitional (Mixed) > Meningioma, Psammomatous",
      "sourceLine": 14464
    }
  ],
  "ioc-overview-pancreatic-surgery": [
    {
      "title": "Pancreatic neuroendocrine tumors",
      "category": "ap_gi",
      "designation": "AR",
      "path": "The Digestive System > The Pancreas > Acute and chronic pancreatitis > Solid pseudopapillary neoplasm > Pancreatic neuroendocrine tumors",
      "sourceLine": 2592
    },
    {
      "title": "Intraductal papillary mucinous neoplasia (PanIN)",
      "category": "ap_gi",
      "designation": "C",
      "path": "The Digestive System > The Pancreas > Acute and chronic pancreatitis > Mucinous cystic neoplasm > Intraductal papillary mucinous neoplasia (PanIN)",
      "sourceLine": 2588
    },
    {
      "title": "Ductal adenocarcinoma",
      "category": "ap_gi",
      "designation": "AR",
      "path": "The Digestive System > The Pancreas > Acute and chronic pancreatitis > Ductal adenocarcinoma",
      "sourceLine": 2586
    },
    {
      "title": "Mucinous cystic neoplasm",
      "category": "ap_gi",
      "designation": "AR",
      "path": "The Digestive System > The Pancreas > Acute and chronic pancreatitis > Mucinous cystic neoplasm",
      "sourceLine": 2587
    },
    {
      "title": "Acinar cell carcinoma",
      "category": "ap_gi",
      "designation": "C",
      "path": "The Digestive System > The Pancreas > Acute and chronic pancreatitis > Acinar cell carcinoma",
      "sourceLine": 2589
    },
    {
      "title": "Autoimmune pancreatitis",
      "category": "ap_gi",
      "designation": "C",
      "path": "The Digestive System > The Pancreas > Acute and chronic pancreatitis > Autoimmune pancreatitis",
      "sourceLine": 2579
    },
    {
      "title": "Infections",
      "category": "ap_gi",
      "designation": "C",
      "path": "The Digestive System > The Pancreas > Acute and chronic pancreatitis > Infections",
      "sourceLine": 2580
    },
    {
      "title": "Acute and chronic pancreatitis",
      "category": "ap_gi",
      "designation": "C",
      "path": "The Digestive System > The Pancreas > Acute and chronic pancreatitis",
      "sourceLine": 2577
    },
    {
      "title": "Other malignancies of the pancreas",
      "category": "ap_gi",
      "designation": "AR",
      "path": "The Digestive System > The Pancreas > Acute and chronic pancreatitis > Solid pseudopapillary neoplasm > Other malignancies of the pancreas",
      "sourceLine": 2593
    },
    {
      "title": "The Pancreas",
      "category": "ap_gi",
      "designation": "C",
      "path": "The Digestive System > The Pancreas",
      "sourceLine": 2567
    }
  ],
  "ioc-overview-thoracic-surgery": [
    {
      "title": "Small cell carcinoma",
      "category": "ap_resp",
      "designation": "C",
      "path": "The Respiratory Tract, Pleura, and Mediastinum > The Respiratory Tract > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Adenocarcinoma > Small cell carcinoma",
      "sourceLine": 3601
    },
    {
      "title": "Adenocarcinoma",
      "category": "ap_resp",
      "designation": "C",
      "path": "The Respiratory Tract, Pleura, and Mediastinum > The Respiratory Tract > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Adenocarcinoma",
      "sourceLine": 3599
    },
    {
      "title": "Bronchiolocentric interstitial lung disease",
      "category": "ap_resp",
      "designation": "C",
      "path": "The Respiratory Tract, Pleura, and Mediastinum > The Respiratory Tract > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Bronchiolocentric interstitial lung disease",
      "sourceLine": 3520
    },
    {
      "title": "Metastatic tumor, lung",
      "category": "ap_resp",
      "designation": "C",
      "path": "The Respiratory Tract, Pleura, and Mediastinum > The Respiratory Tract > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Metastatic tumor, lung",
      "sourceLine": 3607
    },
    {
      "title": "Squamous cell carcinoma",
      "category": "ap_resp",
      "designation": "C",
      "path": "The Respiratory Tract, Pleura, and Mediastinum > The Respiratory Tract > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Squamous cell carcinoma",
      "sourceLine": 3597
    },
    {
      "title": "Constrictive bronchiolitis",
      "category": "ap_resp",
      "designation": "AR",
      "path": "The Respiratory Tract, Pleura, and Mediastinum > The Respiratory Tract > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Bronchiolocentric interstitial lung disease > Constrictive bronchiolitis",
      "sourceLine": 3521
    },
    {
      "title": "Large cell carcinoma (Other than neuroendocrine)",
      "category": "ap_resp",
      "designation": "AR",
      "path": "The Respiratory Tract, Pleura, and Mediastinum > The Respiratory Tract > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Metastatic tumor, lung > Large cell carcinoma (Other than neuroendocrine)",
      "sourceLine": 3609
    },
    {
      "title": "Sarcomatoid carcinoma",
      "category": "ap_resp",
      "designation": "AR",
      "path": "The Respiratory Tract, Pleura, and Mediastinum > The Respiratory Tract > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Metastatic tumor, lung > Sarcomatoid carcinoma",
      "sourceLine": 3611
    },
    {
      "title": "Sclerosing pneumocytoma",
      "category": "ap_resp",
      "designation": "C",
      "path": "The Respiratory Tract, Pleura, and Mediastinum > The Respiratory Tract > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Meningothelial-like nodule > Sclerosing pneumocytoma",
      "sourceLine": 3536
    },
    {
      "title": "Atypical Carcinoid",
      "category": "ap_resp",
      "designation": "C",
      "path": "The Respiratory Tract, Pleura, and Mediastinum > The Respiratory Tract > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Atypical Carcinoid",
      "sourceLine": 3605
    }
  ],
  "ioc-overview-urologic-oncology": [
    {
      "title": "Tissue processing of renal biopsies",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > Kidney > Medical Kidney Disease > Tissue processing of renal biopsies",
      "sourceLine": 741
    },
    {
      "title": "BCG effects",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > BCG effects",
      "sourceLine": 762
    },
    {
      "title": "Diverticula",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Diverticula",
      "sourceLine": 757
    },
    {
      "title": "End Stage Renal Disease",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > Kidney > Medical Kidney Disease > End Stage Renal Disease",
      "sourceLine": 653
    },
    {
      "title": "Nephrogenic metaplasia",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Nephrogenic metaplasia",
      "sourceLine": 755
    },
    {
      "title": "Other Congenital, Developmental, and Familial Conditions",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Other Congenital, Developmental, and Familial Conditions",
      "sourceLine": 759
    },
    {
      "title": "Urethral polyp",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Urethral polyp",
      "sourceLine": 761
    },
    {
      "title": "Normal Anatomy and Histology",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Normal Anatomy and Histology",
      "sourceLine": 752
    },
    {
      "title": "The Urothelial Tract and Bladder",
      "category": "ap_gu",
      "designation": "C",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder",
      "sourceLine": 751
    },
    {
      "title": "Cystitis glandularis",
      "category": "ap_gu",
      "designation": "AR",
      "path": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Cystitis glandularis",
      "sourceLine": 758
    }
  ]
} as const;
