const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();
const OUT_DIR = path.join(ROOT, 'src', 'content', 'ap_signout');
const CONTRACT_PATH = path.join(OUT_DIR, 'ap_signout_masterclass_contract.json');
const REQUIREMENTS_PATH = path.join(OUT_DIR, 'ap_signout_image_requirements.json');

const subspecialties = [
  {
    id: 'gastrointestinal',
    title: 'Gastrointestinal Pathology',
    protocols: ['Colorectal carcinoma resection', 'Appendix tumors', 'Esophagus and stomach resections'],
    topics: [
      'Barrett esophagus dysplasia biopsy',
      'Eosinophilic esophagitis biopsy',
      'Gastric chronic active gastritis biopsy',
      'Gastric intestinal metaplasia and dysplasia biopsy',
      'Celiac disease duodenal biopsy',
      'Microscopic colitis biopsy',
      'Inflammatory bowel disease activity biopsy',
      'CMV colitis biopsy',
      'Adenoma with high-grade dysplasia biopsy',
      'Sessile serrated lesion biopsy',
      'Rectal neuroendocrine tumor biopsy',
      'Anal squamous intraepithelial lesion biopsy',
      'Colectomy for colon adenocarcinoma',
      'Low anterior resection for rectal adenocarcinoma after therapy',
      'Right hemicolectomy for mucinous adenocarcinoma',
      'Appendectomy with goblet cell adenocarcinoma',
      'GIST segmental resection',
      'Gastrectomy for diffuse-type adenocarcinoma',
      'Esophagectomy after neoadjuvant therapy',
      'Ileocolic resection for Crohn disease',
      'Colectomy for ulcerative colitis with dysplasia',
      'Small bowel ischemic resection',
      'Diverticulitis sigmoid resection',
      'Hemorrhoidectomy with incidental dysplasia',
      'Anal excision for squamous cell carcinoma',
      'Peritoneal metastasis debulking',
      'Appendix gross-only acute appendicitis',
      'Colon gross-only diverticulosis',
      'Ileostomy gross-only stoma takedown',
      'Benign gallstone ileus specimen gross-only',
    ],
  },
  {
    id: 'hepatopancreatobiliary',
    title: 'Hepatopancreatobiliary Pathology',
    protocols: ['Pancreas carcinoma resection', 'Intrahepatic bile duct carcinoma', 'Hepatocellular carcinoma'],
    topics: [
      'Medical liver biopsy chronic hepatitis',
      'Medical liver biopsy steatohepatitis',
      'Medical liver biopsy biliary pattern injury',
      'Medical liver biopsy rejection',
      'Liver mass biopsy hepatocellular carcinoma',
      'Liver mass biopsy cholangiocarcinoma',
      'Metastatic carcinoma to liver biopsy',
      'Pancreas core biopsy adenocarcinoma',
      'Pancreas cyst biopsy mucinous lesion',
      'Bile duct biopsy dysplasia',
      'Gallbladder polyp biopsy adenoma',
      'Ampullary biopsy adenoma',
      'Whipple for pancreatic ductal adenocarcinoma',
      'Distal pancreatectomy neuroendocrine tumor',
      'Whipple for ampullary carcinoma',
      'Hepatectomy for hepatocellular carcinoma',
      'Hepatectomy for intrahepatic cholangiocarcinoma',
      'Liver explant for cirrhosis and incidental tumor',
      'Cholecystectomy for invasive carcinoma',
      'Cholecystectomy for high-grade dysplasia',
      'Bile duct resection for cholangiocarcinoma',
      'Pancreatic cyst resection IPMN',
      'Metastatic tumor liver wedge resection',
      'Portal lymphadenectomy with carcinoma',
      'Post-neoadjuvant pancreatic resection treatment response',
      'Liver donor biopsy frozen section',
      'Cholecystectomy gross-only cholelithiasis',
      'Native liver explant gross-only cirrhosis description',
      'Pancreas cyst gross-only benign pseudocyst',
      'Gallbladder gross-only cholesterolosis',
    ],
  },
  {
    id: 'pulmonary_mediastinal',
    title: 'Pulmonary and Mediastinal Pathology',
    protocols: ['Lung carcinoma resection', 'Thymic epithelial tumors', 'Pleural mesothelioma'],
    topics: [
      'Lung transbronchial biopsy infection',
      'Lung biopsy organizing pneumonia',
      'Lung biopsy interstitial lung disease',
      'Lung biopsy adenocarcinoma',
      'Lung biopsy squamous cell carcinoma',
      'Small cell carcinoma biopsy',
      'EBUS lymph node metastatic carcinoma',
      'Pleural biopsy mesothelioma',
      'Mediastinal mass biopsy thymoma',
      'Granulomatous disease lung biopsy',
      'Pneumocystis lung biopsy',
      'Acute rejection transplant biopsy',
      'Lobectomy adenocarcinoma',
      'Lobectomy squamous cell carcinoma',
      'Lobectomy small cell carcinoma',
      'Pneumonectomy carcinoma',
      'Wedge resection carcinoid tumor',
      'Wedge resection metastasis',
      'Pleurectomy mesothelioma',
      'Thymectomy thymoma',
      'Thymectomy thymic carcinoma',
      'Lung transplant explant',
      'Post-neoadjuvant lung resection treatment response',
      'Lobectomy with multiple tumor nodules',
      'Lung resection with visceral pleural invasion',
      'Mediastinal lymph node dissection',
      'Lung bleb gross-only pneumothorax',
      'Lung wedge gross-only emphysematous change',
      'Thymic cyst gross-only',
      'Pleural plaque gross-only',
    ],
  },
  {
    id: 'gynecologic',
    title: 'Gynecologic Pathology',
    protocols: ['Endometrial carcinoma', 'Ovary/fallopian tube/peritoneum', 'Cervix carcinoma'],
    topics: [
      'Endometrial biopsy hyperplasia',
      'Endometrial biopsy carcinoma',
      'Cervical biopsy HSIL',
      'Cervical biopsy adenocarcinoma in situ',
      'Vulvar biopsy differentiated VIN',
      'Vulvar biopsy lichen sclerosus',
      'Ovarian mass biopsy serous carcinoma',
      'Peritoneal biopsy high-grade serous carcinoma',
      'Products of conception biopsy molar pregnancy',
      'Endocervical curettage dysplasia',
      'Myometrial biopsy leiomyosarcoma concern',
      'Vaginal biopsy squamous carcinoma',
      'Hysterectomy endometrioid carcinoma',
      'Hysterectomy serous carcinoma',
      'Radical hysterectomy cervical carcinoma',
      'Oophorectomy borderline serous tumor',
      'Oophorectomy high-grade serous carcinoma',
      'Staging debulking ovarian carcinoma',
      'Risk-reducing salpingo-oophorectomy SEE-FIM',
      'Myomectomy smooth muscle tumor',
      'Vulvectomy squamous carcinoma',
      'Placenta-accreta hysterectomy',
      'Post-neoadjuvant tubo-ovarian carcinoma response',
      'Sentinel lymph nodes endometrial carcinoma',
      'Gestational trophoblastic neoplasia resection',
      'Cervical cone excision margins',
      'Fallopian tube gross-only paratubal cyst',
      'Uterus gross-only leiomyomas',
      'Ovary gross-only simple cyst',
      'Products of conception gross-only early pregnancy loss',
    ],
  },
  {
    id: 'genitourinary',
    title: 'Genitourinary Pathology',
    protocols: ['Prostate cancer', 'Kidney tumors', 'Bladder and ureter carcinomas', 'Testis tumors'],
    topics: [
      'Prostate needle biopsy adenocarcinoma grading',
      'Prostate biopsy atypical glands',
      'Bladder biopsy CIS',
      'Bladder biopsy invasive urothelial carcinoma',
      'Kidney biopsy renal cell carcinoma',
      'Renal pelvis biopsy urothelial carcinoma',
      'Testis biopsy germ cell neoplasia in situ',
      'Penile biopsy squamous intraepithelial lesion',
      'Ureter biopsy high-grade urothelial carcinoma',
      'Adrenal biopsy metastatic carcinoma',
      'Prostate biopsy intraductal carcinoma',
      'Bladder biopsy muscularis propria adequacy',
      'Radical prostatectomy acinar adenocarcinoma',
      'Radical cystectomy urothelial carcinoma',
      'Nephrectomy clear cell renal cell carcinoma',
      'Partial nephrectomy papillary renal cell carcinoma',
      'Radical orchiectomy seminoma',
      'Radical orchiectomy mixed germ cell tumor',
      'Penectomy squamous cell carcinoma',
      'Nephroureterectomy urothelial carcinoma',
      'Cystoprostatectomy incidental prostate cancer',
      'Post-neoadjuvant cystectomy treatment effect',
      'Adrenalectomy cortical carcinoma',
      'Retroperitoneal lymph node dissection germ cell tumor',
      'TURBT resection staging adequacy',
      'Urethrectomy carcinoma',
      'Hydrocele sac gross-only',
      'Vas deferens gross-only vasectomy',
      'Kidney gross-only end-stage kidney',
      'Prostate chips gross-only benign hyperplasia',
    ],
  },
  {
    id: 'dermatopathology',
    title: 'Dermatopathology',
    protocols: ['Melanoma excision', 'Cutaneous squamous cell carcinoma', 'Merkel cell carcinoma'],
    topics: [
      'Shave biopsy basal cell carcinoma',
      'Shave biopsy squamous cell carcinoma',
      'Punch biopsy melanoma',
      'Punch biopsy dermatitis pattern',
      'Punch biopsy vasculitis',
      'Punch biopsy panniculitis',
      'Nail unit biopsy melanoma',
      'Scalp biopsy alopecia',
      'Mucosal biopsy lichen planus',
      'Skin biopsy infection',
      'Adnexal neoplasm biopsy',
      'Merkel cell carcinoma biopsy',
      'Wide excision melanoma',
      'Wide excision squamous cell carcinoma',
      'Mohs debulk basal cell carcinoma',
      'Sentinel lymph node melanoma',
      'Re-excision dysplastic nevus',
      'Excision dermatofibrosarcoma protuberans',
      'Excision adnexal carcinoma',
      'Excision sebaceous carcinoma',
      'Excision Merkel cell carcinoma',
      'Amputation digit melanoma',
      'Vulvar skin excision melanoma',
      'Post-treatment melanoma excision',
      'Lymphadenectomy melanoma metastasis',
      'Excision epidermal inclusion cyst',
      'Skin tag gross-only',
      'Lipoma gross-only subcutis',
      'Pilar cyst gross-only',
      'Scar revision gross-only',
    ],
  },
  {
    id: 'bone_soft_tissue',
    title: 'Bone and Soft Tissue Pathology',
    protocols: ['Soft tissue sarcoma', 'Bone sarcoma', 'GIST if site-appropriate'],
    topics: [
      'Core biopsy spindle cell neoplasm',
      'Core biopsy lipomatous tumor',
      'Core biopsy small round blue cell tumor',
      'Core biopsy bone-forming tumor',
      'Core biopsy cartilage tumor',
      'Core biopsy pleomorphic sarcoma',
      'Core biopsy myxoid neoplasm',
      'Core biopsy nerve sheath tumor',
      'Core biopsy desmoid fibromatosis',
      'Core biopsy metastatic carcinoma to bone',
      'Core biopsy giant cell tumor of bone',
      'Core biopsy inflammatory myofibroblastic tumor',
      'Wide excision undifferentiated pleomorphic sarcoma',
      'Wide excision liposarcoma',
      'Wide excision synovial sarcoma',
      'Wide excision leiomyosarcoma',
      'Resection gastrointestinal stromal tumor',
      'Amputation osteosarcoma after chemotherapy',
      'Curettage giant cell tumor',
      'Wide excision dermatofibrosarcoma protuberans',
      'Resection malignant peripheral nerve sheath tumor',
      'Re-excision positive margin sarcoma',
      'Limb salvage bone sarcoma',
      'Soft tissue metastasectomy',
      'Excision desmoid fibromatosis',
      'Pelvic bone tumor resection',
      'Hardware gross-only explant',
      'Femoral head gross-only osteoarthritis',
      'Ganglion cyst gross-only',
      'Lipoma gross-only extremity',
    ],
  },
  {
    id: 'head_neck',
    title: 'Head and Neck Pathology',
    protocols: ['Oral cavity carcinoma', 'Larynx carcinoma', 'Salivary gland tumors', 'Thyroid if local grouping uses HN'],
    topics: [
      'Oral biopsy dysplasia',
      'Oral biopsy squamous cell carcinoma',
      'Sinonasal biopsy inverted papilloma',
      'Sinonasal biopsy carcinoma',
      'Nasopharyngeal biopsy carcinoma',
      'Laryngeal biopsy dysplasia',
      'Salivary gland FNA/core pleomorphic adenoma',
      'Salivary gland biopsy mucoepidermoid carcinoma',
      'Thyroid core biopsy anaplastic carcinoma',
      'Parathyroid biopsy frozen section',
      'Tonsil biopsy HPV-associated carcinoma',
      'Jaw lesion biopsy odontogenic tumor',
      'Oral cavity resection squamous carcinoma',
      'Mandibulectomy carcinoma',
      'Laryngectomy squamous carcinoma',
      'Neck dissection metastatic carcinoma',
      'Parotidectomy mucoepidermoid carcinoma',
      'Parotidectomy acinic cell carcinoma',
      'Submandibular gland carcinoma',
      'Sinonasal resection carcinoma',
      'Maxillectomy squamous carcinoma',
      'Thyroidectomy carcinoma when HN service covers it',
      'Post-neoadjuvant head neck resection treatment effect',
      'Margin re-excision oral carcinoma',
      'Composite resection with bone invasion',
      'Neck dissection unknown primary',
      'Tonsil gross-only chronic tonsillitis',
      'Nasal polyp gross-only',
      'Thyroglossal duct cyst gross-only',
      'Parathyroid gross-only hypercellular gland',
    ],
  },
  {
    id: 'endocrine',
    title: 'Endocrine Pathology',
    protocols: ['Thyroid carcinoma', 'Adrenal cortical carcinoma', 'Paraganglioma/pheochromocytoma'],
    topics: [
      'Thyroid FNA/core papillary carcinoma correlation',
      'Thyroid biopsy medullary carcinoma',
      'Parathyroid biopsy hypercellular parathyroid',
      'Adrenal biopsy metastatic carcinoma',
      'Pituitary biopsy adenoma',
      'Neuroendocrine tumor biopsy',
      'Thyroid biopsy anaplastic carcinoma',
      'Adrenal biopsy cortical neoplasm',
      'Paraganglioma biopsy',
      'Thyroid frozen section follicular lesion',
      'Parathyroid frozen section tissue confirmation',
      'Pituitary biopsy inflammatory lesion',
      'Thyroidectomy papillary thyroid carcinoma',
      'Thyroidectomy follicular carcinoma',
      'Thyroidectomy medullary carcinoma',
      'Thyroidectomy poorly differentiated carcinoma',
      'Adrenalectomy cortical carcinoma',
      'Adrenalectomy pheochromocytoma',
      'Parathyroidectomy adenoma',
      'Parathyroidectomy hyperplasia',
      'Pituitary resection PitNET',
      'Neck dissection thyroid carcinoma',
      'Completion thyroidectomy carcinoma',
      'Post-treatment thyroid carcinoma resection',
      'MEN-associated endocrine resection',
      'Adrenalectomy myelolipoma',
      'Thyroid gross-only multinodular goiter',
      'Parathyroid gross-only weight documentation',
      'Adrenal gross-only cortical adenoma',
      'Thyroid cyst gross-only',
    ],
  },
  {
    id: 'neuropathology',
    title: 'Neuropathology',
    protocols: ['CNS tumors WHO integrated diagnosis', 'Peripheral nerve and muscle biopsy'],
    topics: [
      'Brain biopsy glioblastoma',
      'Brain biopsy astrocytoma IDH-mutant',
      'Brain biopsy oligodendroglioma',
      'Brain biopsy lymphoma',
      'Brain biopsy metastasis',
      'Meningeal biopsy meningioma',
      'Pituitary biopsy PitNET',
      'Peripheral nerve biopsy vasculitic neuropathy',
      'Muscle biopsy inflammatory myopathy',
      'Temporal artery biopsy arteritis',
      'Brain biopsy demyelinating lesion',
      'Brain biopsy infection',
      'Craniotomy glioblastoma',
      'Craniotomy meningioma',
      'Craniotomy metastasis',
      'Craniotomy schwannoma',
      'Epilepsy lobectomy cortical dysplasia',
      'Spinal cord tumor resection',
      'Pituitary transsphenoidal resection',
      'Peripheral nerve sheath tumor resection',
      'Medulloblastoma resection',
      'Ependymoma resection',
      'Post-treatment glioma resection',
      'CNS lymphoma resection/biopsy follow-up',
      'Dura-based tumor resection',
      'Skull base tumor resection',
      'Hardware gross-only cranial plate',
      'Hematoma gross-only subdural clot',
      'Intervertebral disc gross-only',
      'Temporal artery gross-only negative screen',
    ],
  },
  {
    id: 'renal_medical',
    title: 'Medical Renal Pathology',
    protocols: ['Native kidney biopsy', 'Transplant kidney biopsy', 'Nephrectomy correlation when applicable'],
    topics: [
      'Native kidney biopsy IgA nephropathy',
      'Native kidney biopsy membranous nephropathy',
      'Native kidney biopsy diabetic nephropathy',
      'Native kidney biopsy lupus nephritis',
      'Native kidney biopsy ANCA-associated GN',
      'Native kidney biopsy minimal change disease',
      'Native kidney biopsy FSGS',
      'Native kidney biopsy amyloidosis',
      'Native kidney biopsy infection-related GN',
      'Transplant kidney biopsy rejection',
      'Transplant kidney biopsy BK nephropathy',
      'Transplant kidney biopsy recurrent disease',
      'Nephrectomy end-stage kidney correlation',
      'Nephrectomy diabetic nephropathy correlation',
      'Nephrectomy chronic pyelonephritis',
      'Transplant nephrectomy rejection',
      'Kidney explant thrombotic microangiopathy',
      'Kidney resection vasculitis correlation',
      'Nephrectomy medical renal tumor-adjacent kidney',
      'Kidney biopsy complication nephrectomy',
      'Renal artery specimen vasculitis',
      'Transplant explant chronic allograft injury',
      'Medical renal autopsy block correlation',
      'Kidney wedge resection non-neoplastic parenchyma',
      'Donor wedge biopsy frozen section',
      'Renal cyst wall with medical renal background',
      'Kidney gross-only end-stage kidney',
      'Transplant kidney gross-only explant',
      'Renal calculus gross-only',
      'Peritoneal dialysis catheter gross-only',
    ],
  },
  {
    id: 'placental_perinatal',
    title: 'Placental and Perinatal Pathology',
    protocols: ['Placental examination', 'Products of conception', 'Perinatal autopsy interface'],
    topics: [
      'Placental biopsy acute chorioamnionitis',
      'Placental biopsy chronic villitis',
      'Placental biopsy maternal vascular malperfusion',
      'Placental biopsy fetal vascular malperfusion',
      'Placental biopsy massive perivillous fibrin deposition',
      'Placental biopsy chronic histiocytic intervillositis',
      'Products of conception hydropic villi',
      'Products of conception molar pregnancy',
      'Fetal tissue biopsy infection',
      'Umbilical cord biopsy funisitis',
      'Placental disc sections accreta concern',
      'Twin placenta biopsy vascular anastomoses',
      'Placenta third trimester examination',
      'Placenta preterm delivery examination',
      'Placenta fetal demise examination',
      'Placenta twin gestation examination',
      'Placenta accreta spectrum hysterectomy',
      'Products of conception evacuation',
      'Perinatal autopsy placenta correlation',
      'Placenta with fetal thrombotic vasculopathy',
      'Placenta with maternal floor infarction',
      'Placenta with villous edema',
      'Placenta with meconium-associated changes',
      'Placenta with delayed villous maturation',
      'Placenta with infection and fetal response',
      'Placenta with cord abnormality',
      'Placenta gross-only term uncomplicated',
      'Umbilical cord gross-only true knot',
      'Fetal membranes gross-only rupture sequence',
      'Products of conception gross-only early loss',
    ],
  },
  {
    id: 'cardiovascular',
    title: 'Cardiovascular Pathology',
    protocols: ['Heart explant', 'Valve pathology', 'Vascular resections'],
    topics: [
      'Endomyocardial biopsy rejection',
      'Endomyocardial biopsy myocarditis',
      'Endomyocardial biopsy amyloid',
      'Temporal artery biopsy giant cell arteritis',
      'Vascular biopsy vasculitis',
      'Cardiac mass biopsy myxoma',
      'Valve biopsy endocarditis',
      'Aortic biopsy aortitis',
      'Pericardial biopsy malignancy',
      'Pulmonary artery biopsy thrombus',
      'Endomyocardial biopsy drug toxicity',
      'Vascular graft biopsy infection',
      'Heart explant cardiomyopathy',
      'Heart explant ischemic cardiomyopathy',
      'Heart explant congenital disease',
      'Valve replacement calcific stenosis',
      'Valve replacement infective endocarditis',
      'Aortic aneurysm resection',
      'Carotid endarterectomy plaque',
      'Vascular graft excision infection',
      'Cardiac myxoma resection',
      'Pericardiectomy constrictive pericarditis',
      'Heart transplant explant rejection',
      'Left atrial appendage excision',
      'Pulmonary thromboendarterectomy',
      'Aortic dissection repair specimen',
      'Valve gross-only degenerative calcification',
      'Atheroma gross-only endarterectomy',
      'Thrombus gross-only',
      'Pacemaker lead gross-only',
    ],
  },
  {
    id: 'lymph_node_spleen',
    title: 'Lymph Node and Spleen Pathology',
    protocols: ['Lymphoma workup', 'Spleen neoplasms and non-neoplastic disease'],
    topics: [
      'Lymph node core biopsy metastatic carcinoma',
      'Lymph node core biopsy lymphoma',
      'Lymph node biopsy granulomatous lymphadenitis',
      'Lymph node biopsy Castleman disease',
      'Lymph node biopsy reactive hyperplasia',
      'Lymph node biopsy melanoma metastasis',
      'Lymph node biopsy Hodgkin lymphoma',
      'Lymph node biopsy diffuse large B-cell lymphoma',
      'Lymph node biopsy follicular lymphoma',
      'Lymph node biopsy T-cell lymphoma',
      'Bone marrow clot lymphoid infiltrate correlation',
      'Spleen biopsy vascular lesion',
      'Excisional lymph node lymphoma workup',
      'Sentinel lymph node carcinoma',
      'Lymphadenectomy metastatic carcinoma',
      'Neck dissection lymphoma versus carcinoma',
      'Axillary dissection metastatic carcinoma',
      'Inguinal dissection melanoma',
      'Splenectomy lymphoma',
      'Splenectomy hypersplenism',
      'Splenectomy trauma with incidental lesion',
      'Splenectomy hairy cell leukemia',
      'Lymph node excision Kikuchi disease',
      'Lymph node excision Rosai-Dorfman disease',
      'Lymph node excision IgG4-related disease',
      'Lymph node excision infectious lymphadenitis',
      'Lymph node gross-only benign node',
      'Spleen gross-only traumatic rupture',
      'Accessory spleen gross-only',
      'Thymic tissue gross-only involution',
    ],
  },
];

const workflowForIndex = (index) => {
  if (index < 12) return 'biopsy';
  if (index < 26) return 'resection';
  return 'gross-only';
};

const modalityForWorkflow = (workflow) => {
  if (workflow === 'gross-only') return 'gross-photography';
  if (workflow === 'resection') return 'histology-and-gross-correlation';
  return 'diagnostic-histology';
};

const uxJourneyForWorkflow = (workflow, subspecialtyId, caseId) => {
  const workflowPanel =
    workflow === 'gross-only' ? 'gross-only-checklist' : workflow === 'resection' ? 'synoptic-field-practice' : 'report-language';
  return {
    targetStandard: 'commercial-grade-training-product',
    entryPath: ['persistent navigation', 'subspecialty selector', 'case rail', 'focused case workspace'],
    maxClicksToImage: 3,
    maxClicksToFinalReport: 7,
    requiredStates: [
      'case-selected',
      'image-visible-before-diagnosis',
      'clinical-header-visible',
      'observation-prompts-visible',
      'diagnostic-reasoning-hidden-until-reveal',
      'final-report-hidden-until-reveal',
      workflowPanel,
    ],
    primaryActions: [
      { label: 'Select case', result: 'focused case workspace opens without page-length search' },
      { label: 'Reveal next step', result: 'only the next diagnostic reasoning step appears' },
      { label: 'Reveal final diagnosis', result: 'report-ready language appears after observation sequence' },
    ],
    secondaryActions: [
      { label: 'Reset case', result: 'case returns to image-first state' },
      { label: 'Open source/provenance', result: 'source opens without interrupting the case state' },
    ],
    accessibilityAndPolish: {
      stableTestIds: [
        `case-button-${caseId}`,
        `image-stage-${caseId}`,
        `observation-sequence-${caseId}`,
        `report-panel-${caseId}`,
      ],
      keyboardReachable: true,
      visibleFocusRequired: true,
      mobileNoOverlapRequired: true,
      noNestedCards: true,
      noDecorativeNoise: true,
      clinicalLanguageOnly: true,
    },
    telemetryEvents: [
      `ap_signout_${subspecialtyId}_case_opened`,
      `ap_signout_${subspecialtyId}_step_revealed`,
      `ap_signout_${subspecialtyId}_report_revealed`,
    ],
  };
};

const caseForTopic = (subspecialty, topic, index) => {
  const workflow = workflowForIndex(index);
  const caseNumber = String(index + 1).padStart(2, '0');
  const id = `ap-${subspecialty.id}-${caseNumber}`;
  const isGrossOnly = workflow === 'gross-only';
  const isResection = workflow === 'resection';
  return {
    id,
    subspecialtyId: subspecialty.id,
    title: topic,
    workflow,
    specimenType: isGrossOnly ? 'Gross-only specimen' : isResection ? 'Resection specimen' : 'Biopsy specimen',
    diagnosticTask: isGrossOnly
      ? `Conduct a gross-only sign-out for ${topic}, including specimen identity, measurements, lesion description, submission decision, and final gross diagnosis.`
      : isResection
        ? `Conduct an image-first resection sign-out for ${topic}, including gross correlation, histologic diagnosis, margins/stage or protocol fields, lymph nodes when applicable, and final report language.`
        : `Conduct an image-first biopsy sign-out for ${topic}, including the key microscopic observation, differential diagnosis, ancillary decision, and exact diagnostic line.`,
    displayFormatting: {
      firstPanel: isGrossOnly ? 'gross-image-first' : 'histology-image-first',
      secondPanel: 'observation-sequence',
      thirdPanel: isResection ? 'synoptic-field-practice' : 'report-language',
      revealOrder: ['image', 'clinical header', 'learner observation', 'diagnostic reasoning', 'ancillary studies if indicated', 'final report language'],
      imageSizing: 'uniform-large-contain',
      requiredNavigation: 'case-list-to-single-case-page-or-panel',
    },
    uxJourney: uxJourneyForWorkflow(workflow, subspecialty.id, id),
    imageAcquisition: {
      library: `ap-signout/${subspecialty.id}`,
      acceptedSourceKinds: ['image_url', 'local_image', 'pdf_page'],
      minimumImages: isGrossOnly ? 1 : isResection ? 2 : 1,
      requiredEvidence: [
        {
          slot: `${id}-primary-${modalityForWorkflow(workflow)}`,
          role: modalityForWorkflow(workflow),
          sourceStatus: 'required-before-release',
          captionMustName: isGrossOnly ? ['specimen identity', 'measurements', 'gross abnormality'] : ['diagnostic feature', 'stain or marker', 'entity'],
        },
        ...(isResection
          ? [
              {
                slot: `${id}-gross-correlation`,
                role: 'gross-photography-or-diagram',
                sourceStatus: 'required-before-release',
                captionMustName: ['specimen orientation', 'tumor or lesion site', 'margin or sampling relevance'],
              },
            ]
          : []),
      ],
    },
    diagnosticSteps: [
      {
        step: 1,
        prompt: isGrossOnly ? 'Describe the gross specimen before assigning a diagnosis.' : 'Name the first visual finding that drives the differential.',
        expectedObservation: isGrossOnly
          ? 'Specimen type, dimensions, orientation, lesion description, and whether histologic submission is required are stated explicitly.'
          : 'The learner states the dominant histologic pattern and the compartment involved before naming a diagnosis.',
      },
      {
        step: 2,
        prompt: 'State the highest-risk diagnostic or reporting decision.',
        expectedObservation: isResection
          ? 'The learner identifies the protocol-critical elements, including margins, lymph nodes, treatment effect, grade, or stage when applicable.'
          : isGrossOnly
            ? 'The learner states why gross-only handling is sufficient or why histology must be triggered.'
            : 'The learner states the entity, key mimic, and whether ancillary testing is necessary.',
      },
      {
        step: 3,
        prompt: 'Dictate the final report line.',
        expectedObservation: 'The final line is concise, clinically usable, and report-ready.',
      },
    ],
    synopticChecklist: isResection
      ? [
          {
            group: 'Resection essentials',
            items: ['procedure and site', 'tumor or lesion size', 'histologic type', 'grade if applicable', 'margins', 'lymph nodes if submitted', 'stage/protocol fields if applicable'],
          },
        ]
      : [],
    grossOnlyChecklist: isGrossOnly
      ? ['specimen identity', 'dimensions', 'orientation', 'lesion or no lesion', 'representative photo or diagram', 'submission decision', 'gross diagnosis']
      : [],
    reportingTarget: isGrossOnly
      ? `${topic}: gross diagnosis with specimen identity, measurements, and submission decision.`
      : `${topic}: final diagnostic line plus all clinically required qualifiers and ancillary/protocol fields.`,
    pitfalls: [
      isGrossOnly ? 'Treating a gross-only specimen as exempt from documentation.' : 'Letting the diagnosis appear before the learner has described the image.',
      isResection ? 'Omitting synoptic-critical elements after naming the diagnosis.' : 'Using vague teaching language instead of exact report language.',
    ],
  };
};

const buildContract = () => {
  const generatedAt = new Date().toISOString();
  const subspecialtyContracts = subspecialties.map((subspecialty) => {
    const cases = subspecialty.topics.map((topic, index) => caseForTopic(subspecialty, topic, index));
    return {
      id: subspecialty.id,
      title: subspecialty.title,
      minimumCaseCount: 30,
      requiredWorkflowCoverage: ['biopsy', 'resection', 'gross-only'],
      protocolAnchors: subspecialty.protocols,
      cases,
    };
  });

  return {
    version: '2026-05-01',
    generatedAt,
    purpose: 'AP-wide sign-out masterclass contract modeled after the Breast Sign-Out Masterclass: image-first, case-list navigation, staged reveal, exact report language, synoptic practice, and governed local image acquisition.',
    excludes: ['breast'],
    globalRequirements: {
      minimumCasesPerSubspecialty: 30,
      requiredWorkflows: ['biopsy', 'resection', 'gross-only'],
      requiredTeachingMechanisms: ['image-first observation', 'diagnostic commitment', 'synoptic field practice', 'gross-only documentation', 'final report reveal'],
      requiredAssetKinds: ['histology', 'immunohistochemistry/ancillary when indicated', 'gross image or diagram', 'PDF page capture when source is a document'],
      displayFormat: {
        layout: 'left case rail, large uniform image stage, right observation/reveal panel, lower synoptic/report panels',
        imageSizing: 'uniform large object-contain with stable dimensions',
        navigation: 'clicking a case opens a single focused case, not infinite scroll',
        learnerLanguage: 'clinical sign-out language only; no web-development annotations',
      },
      releaseGate: [
        'Every case has at least one visual evidence slot.',
        'Every resection case has synoptic field practice.',
        'Every gross-only case has gross documentation fields.',
        'Every acquired image is stored locally with source provenance.',
        'Strict source and file validation must pass before release.',
      ],
    },
    subspecialties: subspecialtyContracts,
  };
};

const writeOutputs = () => {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const contract = buildContract();
  const requirements = {
    version: contract.version,
    generatedAt: contract.generatedAt,
    purpose: 'Derived image acquisition requirements for AP sign-out masterclass cases.',
    sourcesRequiredBeforeRelease: contract.subspecialties.flatMap((subspecialty) =>
      subspecialty.cases.flatMap((item) =>
        item.imageAcquisition.requiredEvidence.map((requirement) => ({
          id: requirement.slot,
          subspecialtyId: subspecialty.id,
          caseId: item.id,
          caseTitle: item.title,
          workflow: item.workflow,
          role: requirement.role,
          sourceStatus: requirement.sourceStatus,
          acceptedSourceKinds: item.imageAcquisition.acceptedSourceKinds,
          library: item.imageAcquisition.library,
          captionMustName: requirement.captionMustName,
        }))
      )
    ),
  };
  fs.writeFileSync(CONTRACT_PATH, `${JSON.stringify(contract, null, 2)}\n`);
  fs.writeFileSync(REQUIREMENTS_PATH, `${JSON.stringify(requirements, null, 2)}\n`);
  console.log(JSON.stringify({
    contract: path.relative(ROOT, CONTRACT_PATH),
    requirements: path.relative(ROOT, REQUIREMENTS_PATH),
    subspecialties: contract.subspecialties.length,
    cases: contract.subspecialties.reduce((sum, item) => sum + item.cases.length, 0),
    imageRequirements: requirements.sourcesRequiredBeforeRelease.length,
  }, null, 2));
};

writeOutputs();
