// Generated by scripts/generate_ap_p0_cv_taxonomy_review_cards.cjs. Do not edit by hand.

export const apP0CvTaxonomyReviewCardBatch = {
  "generatedAt": "2026-05-15T22:40:30.395Z",
  "sourcePlan": "reports/ap_gap_closure_plan.json",
  "sourceQueue": "src/content/competency/apGapClosureQueue.ts",
  "facultyPacketPath": "reports/ap_p0_cv_taxonomy_review_card_batch_faculty_packet.md",
  "facultyPacketCsvPath": "reports/ap_p0_cv_taxonomy_review_card_batch_faculty_packet.csv",
  "batchName": "P0 cardiovascular/autopsy taxonomy review completion batch",
  "batchStrategy": "Final unassigned P0 cardiovascular/autopsy-adjacent rows captured as taxonomy-review scaffolds so all P0 rows are tracked while faculty decides keep, reassign, or retire.",
  "status": "draft taxonomy-review scaffolds awaiting faculty keep/reassign decision before canonical promotion",
  "categoryCoverage": {
    "categoryId": "ap_cv",
    "category": "Cardiovascular / Autopsy-adjacent",
    "selectedCards": 3
  },
  "batchReadiness": {
    "completedGates": 0,
    "reviewReadyGates": 3,
    "missingGates": 12,
    "totalGates": 15,
    "percentComplete": 0,
    "percentReviewReady": 20
  },
  "readinessLegend": {
    "complete": "Evidence is present and reviewed.",
    "ready-for-review": "Structured taxonomy scaffold exists and needs faculty decision.",
    "missing": "Required taxonomy decision, content, asset, source, answer key, or reviewer evidence is not yet attached."
  },
  "cards": [
    {
      "id": "p0-cv-taxonomy-review-card-01-475eb4ab-3238-429b-b48e-ca4d66a541dd",
      "sourceQueueId": "ap_cv-475eb4ab-3238-429b-b48e-ca4d66a541dd",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Steatosis, Steatohepatitis, Metabolic Syndrome",
      "category": "Cardiovascular / Autopsy-adjacent",
      "rotation": "Autopsy, cardiovascular, and pulmonary pathology",
      "apSpecPath": "Cardiovascular > Normal Development, Structure, and Function > The Hepatobiliary System and Pancreas > Steatosis, Steatohepatitis, Metabolic Syndrome",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 16581,
      "taxonomyConcern": "Hepatobiliary/metabolic topic nested in cardiovascular AP path; likely needs reassignment or autopsy comorbidity framing.",
      "specimenContext": "autopsy liver and cardiovascular risk context, or systemic metabolic syndrome correlation with liver, heart, and vascular findings",
      "visualAnchorPlan": "gross liver steatosis/steatohepatitis or metabolic syndrome comorbidity diagram with cardiovascular risk linkage",
      "reportingConsequencePrompt": "separate primary hepatobiliary diagnosis from cardiovascular risk contribution and death-certificate language",
      "mimicFrame": "alcohol-related liver disease, congestion, postmortem change, obesity-related comorbidity, or nonspecific macrovesicular steatosis",
      "entityCardSections": [
        "Taxonomy keep/reassign decision with rationale",
        "Definition and scope only after taxonomy decision",
        "Normal/systemic comparator or explicit no-morphology rationale",
        "Gross, microscopic, or clinicopathologic anchor",
        "Top mimic, parser artifact, or adjacent-domain reassignment target",
        "Autopsy/reporting/comorbidity consequence",
        "Safety-critical pitfall: over-attributing causality or teaching in the wrong domain"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Steatosis, Steatohepatitis, Metabolic Syndrome should remain in CV/autopsy or be reassigned.",
        "State the taxonomy rationale in one sentence.",
        "Name the closest adjacent domain and why it may be a better home.",
        "Write a safe autopsy or report comment phrase if this is retained as a comorbidity/correlation topic."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA explicitly chooses keep, reassign, or retire as parser artifact.",
        "Source citation and review date are attached.",
        "Visual anchor or no-image rationale matches the taxonomy decision.",
        "Retrieval answer key explains the keep/reassign rationale.",
        "One pitfall about causal overstatement or domain drift is included."
      ],
      "completionGate": "Not complete until taxonomy decision, source-backed content, visual/no-image rationale, answer key, and faculty review metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Final unassigned AP P0 row; faculty must decide keep-in-CV/autopsy versus reassignment. Concern: Hepatobiliary/metabolic topic nested in cardiovascular AP path; likely needs reassignment or autopsy comorbidity framing."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Content must be authored only after taxonomy keep/reassign decision; include definition, normal/systemic comparator, consequence, mimic, and pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "gross liver steatosis/steatohepatitis or metabolic syndrome comorbidity diagram with cardiovascular risk linkage"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Retrieval prompt exists; faculty-reviewed keep/reassign rationale and answer key are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Faculty taxonomy decision, source citation, image/license status, reviewer, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-cv-taxonomy-review-card-02-1ed9c3dd-c294-405a-934a-28d54bce5fee",
      "sourceQueueId": "ap_cv-1ed9c3dd-c294-405a-934a-28d54bce5fee",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Diabetes Mellitus",
      "category": "Cardiovascular / Autopsy-adjacent",
      "rotation": "Autopsy, cardiovascular, and pulmonary pathology",
      "apSpecPath": "Cardiovascular > Normal Development, Structure, and Function > Diabetes Mellitus",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 16700,
      "taxonomyConcern": "Systemic metabolic disease placed under cardiovascular normal structure/function; likely belongs in endocrine/systemic disease or autopsy clinicopathologic correlation.",
      "specimenContext": "autopsy case or explant/resection correlation where diabetes contributes to cardiovascular, renal, vascular, infectious, or wound-healing morbidity",
      "visualAnchorPlan": "vascular, myocardial, renal, or systemic diabetic complication anchor plus explicit no-single-pathognomonic-lesion caution",
      "reportingConsequencePrompt": "document diabetes as a comorbidity/contributor without overstating cause-of-death certainty; connect to macrovascular/microvascular complications when present",
      "mimicFrame": "background diabetes history without morphologic complication, hypertensive vascular disease, atherosclerosis, or nonspecific terminal changes",
      "entityCardSections": [
        "Taxonomy keep/reassign decision with rationale",
        "Definition and scope only after taxonomy decision",
        "Normal/systemic comparator or explicit no-morphology rationale",
        "Gross, microscopic, or clinicopathologic anchor",
        "Top mimic, parser artifact, or adjacent-domain reassignment target",
        "Autopsy/reporting/comorbidity consequence",
        "Safety-critical pitfall: over-attributing causality or teaching in the wrong domain"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Diabetes Mellitus should remain in CV/autopsy or be reassigned.",
        "State the taxonomy rationale in one sentence.",
        "Name the closest adjacent domain and why it may be a better home.",
        "Write a safe autopsy or report comment phrase if this is retained as a comorbidity/correlation topic."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA explicitly chooses keep, reassign, or retire as parser artifact.",
        "Source citation and review date are attached.",
        "Visual anchor or no-image rationale matches the taxonomy decision.",
        "Retrieval answer key explains the keep/reassign rationale.",
        "One pitfall about causal overstatement or domain drift is included."
      ],
      "completionGate": "Not complete until taxonomy decision, source-backed content, visual/no-image rationale, answer key, and faculty review metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Final unassigned AP P0 row; faculty must decide keep-in-CV/autopsy versus reassignment. Concern: Systemic metabolic disease placed under cardiovascular normal structure/function; likely belongs in endocrine/systemic disease or autopsy clinicopathologic correlation."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Content must be authored only after taxonomy keep/reassign decision; include definition, normal/systemic comparator, consequence, mimic, and pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "vascular, myocardial, renal, or systemic diabetic complication anchor plus explicit no-single-pathognomonic-lesion caution"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Retrieval prompt exists; faculty-reviewed keep/reassign rationale and answer key are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Faculty taxonomy decision, source citation, image/license status, reviewer, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-cv-taxonomy-review-card-03-99a8b9d8-db08-4250-990f-91241f292200",
      "sourceQueueId": "ap_cv-99a8b9d8-db08-4250-990f-91241f292200",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Shwachman-Diamond",
      "category": "Cardiovascular / Autopsy-adjacent",
      "rotation": "Autopsy, cardiovascular, and pulmonary pathology",
      "apSpecPath": "Cardiovascular > Normal Development, Structure, and Function > Shwachman-Diamond",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 16701,
      "taxonomyConcern": "Inherited marrow/pancreatic syndrome nested in cardiovascular AP path; likely taxonomy spillover requiring faculty reassignment.",
      "specimenContext": "autopsy or pediatric/systemic disease case where inherited syndrome findings require clinicopathologic correlation",
      "visualAnchorPlan": "syndrome-level diagram or organ-system correlation table unless a local/licensed histologic anchor is available",
      "reportingConsequencePrompt": "document syndrome-associated findings and decide whether this belongs in pediatric, hematopathology, GI/pancreas, or autopsy teaching",
      "mimicFrame": "nonspecific marrow failure, pancreatic insufficiency, congenital syndrome differential, or parser artifact",
      "entityCardSections": [
        "Taxonomy keep/reassign decision with rationale",
        "Definition and scope only after taxonomy decision",
        "Normal/systemic comparator or explicit no-morphology rationale",
        "Gross, microscopic, or clinicopathologic anchor",
        "Top mimic, parser artifact, or adjacent-domain reassignment target",
        "Autopsy/reporting/comorbidity consequence",
        "Safety-critical pitfall: over-attributing causality or teaching in the wrong domain"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Shwachman-Diamond should remain in CV/autopsy or be reassigned.",
        "State the taxonomy rationale in one sentence.",
        "Name the closest adjacent domain and why it may be a better home.",
        "Write a safe autopsy or report comment phrase if this is retained as a comorbidity/correlation topic."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA explicitly chooses keep, reassign, or retire as parser artifact.",
        "Source citation and review date are attached.",
        "Visual anchor or no-image rationale matches the taxonomy decision.",
        "Retrieval answer key explains the keep/reassign rationale.",
        "One pitfall about causal overstatement or domain drift is included."
      ],
      "completionGate": "Not complete until taxonomy decision, source-backed content, visual/no-image rationale, answer key, and faculty review metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Final unassigned AP P0 row; faculty must decide keep-in-CV/autopsy versus reassignment. Concern: Inherited marrow/pancreatic syndrome nested in cardiovascular AP path; likely taxonomy spillover requiring faculty reassignment."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Content must be authored only after taxonomy keep/reassign decision; include definition, normal/systemic comparator, consequence, mimic, and pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "syndrome-level diagram or organ-system correlation table unless a local/licensed histologic anchor is available"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Retrieval prompt exists; faculty-reviewed keep/reassign rationale and answer key are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Faculty taxonomy decision, source citation, image/license status, reviewer, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    }
  ]
} as const;

export type ApP0CvTaxonomyReviewCard = typeof apP0CvTaxonomyReviewCardBatch.cards[number];
