// Generated by scripts/generate_ap_p0_entity_cards.cjs. Do not edit by hand.

export const apP0EntityCardBatch = {
  "generatedAt": "2026-05-15T22:40:26.564Z",
  "sourcePlan": "reports/ap_gap_closure_plan.json",
  "facultyPacketPath": "reports/ap_p0_entity_card_batch_1_faculty_packet.md",
  "batchName": "P0 core entity card batch 1",
  "batchStrategy": "First 24 P0 rows prioritized toward medical kidney/GU, placenta, GI, cardiovascular/autopsy, endocrine, thoracic, soft tissue, cytology, and head and neck before broader long-tail domains.",
  "status": "draft scaffolds awaiting faculty-reviewed medical content and visual assets",
  "batchReadiness": {
    "completedGates": 0,
    "reviewReadyGates": 24,
    "missingGates": 96,
    "totalGates": 120,
    "percentComplete": 0,
    "percentReviewReady": 20
  },
  "readinessLegend": {
    "complete": "Evidence is present and reviewed.",
    "ready-for-review": "Structured scaffold exists and needs faculty confirmation.",
    "missing": "Required content, asset, source, answer key, or reviewer evidence is not yet attached."
  },
  "cards": [
    {
      "id": "p0-card-01-d3176b1f-e18d-49eb-b9b0-5eeeb00fadc0",
      "sourceQueueId": "ap_gu-d3176b1f-e18d-49eb-b9b0-5eeeb00fadc0",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Diseases associated with acellular closure of glomerular capillaries",
      "category": "Medical Kidney / GU",
      "rotation": "Renal pathology / GU pathology",
      "apSpecPath": "The Genitourinary System > Kidney > Medical Kidney Disease > Diseases associated with acellular closure of glomerular capillaries",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 608,
      "specimenContext": "renal biopsy, nephrectomy, bladder biopsy/TURBT, or cystectomy depending on entity",
      "visualAnchorPlan": "H&E plus IF/EM when medical kidney, or H&E/gross for bladder and lower GU",
      "reportingConsequencePrompt": "diagnostic category, chronicity/activity or report element that changes management",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Diseases associated with acellular closure of glomerular capillaries.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "H&E plus IF/EM when medical kidney, or H&E/gross for bladder and lower GU"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-02-59e217f3-550d-40fb-ba59-d900d6d5a5af",
      "sourceQueueId": "ap_gu-59e217f3-550d-40fb-ba59-d900d6d5a5af",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Non-proliferative glomerulonephropathies",
      "category": "Medical Kidney / GU",
      "rotation": "Renal pathology / GU pathology",
      "apSpecPath": "The Genitourinary System > Kidney > Medical Kidney Disease > Non-proliferative glomerulonephropathies",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 576,
      "specimenContext": "renal biopsy, nephrectomy, bladder biopsy/TURBT, or cystectomy depending on entity",
      "visualAnchorPlan": "H&E plus IF/EM when medical kidney, or H&E/gross for bladder and lower GU",
      "reportingConsequencePrompt": "diagnostic category, chronicity/activity or report element that changes management",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Non-proliferative glomerulonephropathies.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "H&E plus IF/EM when medical kidney, or H&E/gross for bladder and lower GU"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-03-c7c74b2a-9d75-4b81-b78b-fdbf4e85c76d",
      "sourceQueueId": "ap_gu-c7c74b2a-9d75-4b81-b78b-fdbf4e85c76d",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "BCG effects",
      "category": "Medical Kidney / GU",
      "rotation": "Renal pathology / GU pathology",
      "apSpecPath": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > BCG effects",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 762,
      "specimenContext": "renal biopsy, nephrectomy, bladder biopsy/TURBT, or cystectomy depending on entity",
      "visualAnchorPlan": "H&E plus IF/EM when medical kidney, or H&E/gross for bladder and lower GU",
      "reportingConsequencePrompt": "diagnostic category, chronicity/activity or report element that changes management",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by BCG effects.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "H&E plus IF/EM when medical kidney, or H&E/gross for bladder and lower GU"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-04-bc90e1cf-b575-4be6-95e0-95b105b8efaa",
      "sourceQueueId": "ap_gu-bc90e1cf-b575-4be6-95e0-95b105b8efaa",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Diverticula",
      "category": "Medical Kidney / GU",
      "rotation": "Renal pathology / GU pathology",
      "apSpecPath": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Diverticula",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 757,
      "specimenContext": "renal biopsy, nephrectomy, bladder biopsy/TURBT, or cystectomy depending on entity",
      "visualAnchorPlan": "H&E plus IF/EM when medical kidney, or H&E/gross for bladder and lower GU",
      "reportingConsequencePrompt": "diagnostic category, chronicity/activity or report element that changes management",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Diverticula.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "H&E plus IF/EM when medical kidney, or H&E/gross for bladder and lower GU"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-05-2acaf2ec-9515-4398-a7b4-6c624aa84638",
      "sourceQueueId": "ap_gu-2acaf2ec-9515-4398-a7b4-6c624aa84638",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Urethral polyp",
      "category": "Medical Kidney / GU",
      "rotation": "Renal pathology / GU pathology",
      "apSpecPath": "The Genitourinary System > The Urothelial Tract and Bladder > Physiologic Changes, Metabolic Conditions & Trauma/Infarct > Urethral polyp",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 761,
      "specimenContext": "renal biopsy, nephrectomy, bladder biopsy/TURBT, or cystectomy depending on entity",
      "visualAnchorPlan": "H&E plus IF/EM when medical kidney, or H&E/gross for bladder and lower GU",
      "reportingConsequencePrompt": "diagnostic category, chronicity/activity or report element that changes management",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Urethral polyp.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "H&E plus IF/EM when medical kidney, or H&E/gross for bladder and lower GU"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-06-da4bc31a-bf36-45b7-92cc-f3cd0c717c5a",
      "sourceQueueId": "ap_placenta-da4bc31a-bf36-45b7-92cc-f3cd0c717c5a",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Chorangioma",
      "category": "Placenta",
      "rotation": "Placenta/perinatal pathology",
      "apSpecPath": "The Placenta > Normal Anatomy and Histology > Chorangioma",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 3413,
      "specimenContext": "placental disc, membranes, cord, and maternal/fetal surfaces",
      "visualAnchorPlan": "gross orientation image or diagram plus H&E lesion anchor",
      "reportingConsequencePrompt": "maternal/fetal consequence and reportable placental lesion language",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Chorangioma.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "gross orientation image or diagram plus H&E lesion anchor"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-07-258e3696-8b48-4e97-a509-e7c209aeaa4c",
      "sourceQueueId": "ap_placenta-258e3696-8b48-4e97-a509-e7c209aeaa4c",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Fetal Membrane Abnormalities",
      "category": "Placenta",
      "rotation": "Placenta/perinatal pathology",
      "apSpecPath": "The Placenta > Normal Anatomy and Histology > Fetal Membrane Abnormalities",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 3400,
      "specimenContext": "placental disc, membranes, cord, and maternal/fetal surfaces",
      "visualAnchorPlan": "gross orientation image or diagram plus H&E lesion anchor",
      "reportingConsequencePrompt": "maternal/fetal consequence and reportable placental lesion language",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Fetal Membrane Abnormalities.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "gross orientation image or diagram plus H&E lesion anchor"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-08-5becad66-bbe5-44de-ac72-11551d2d7176",
      "sourceQueueId": "ap_placenta-5becad66-bbe5-44de-ac72-11551d2d7176",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Amnion nodosum",
      "category": "Placenta",
      "rotation": "Placenta/perinatal pathology",
      "apSpecPath": "The Placenta > Normal Anatomy and Histology > Fetal Membrane Abnormalities > Amnion nodosum",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 3401,
      "specimenContext": "placental disc, membranes, cord, and maternal/fetal surfaces",
      "visualAnchorPlan": "gross orientation image or diagram plus H&E lesion anchor",
      "reportingConsequencePrompt": "maternal/fetal consequence and reportable placental lesion language",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Amnion nodosum.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "gross orientation image or diagram plus H&E lesion anchor"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-09-4a7a821e-af51-4637-87d8-ea230c5586fe",
      "sourceQueueId": "ap_placenta-4a7a821e-af51-4637-87d8-ea230c5586fe",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Chorioamnionitis",
      "category": "Placenta",
      "rotation": "Placenta/perinatal pathology",
      "apSpecPath": "The Placenta > Normal Anatomy and Histology > Fetal Membrane Abnormalities > Chorioamnionitis",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 3402,
      "specimenContext": "placental disc, membranes, cord, and maternal/fetal surfaces",
      "visualAnchorPlan": "gross orientation image or diagram plus H&E lesion anchor",
      "reportingConsequencePrompt": "maternal/fetal consequence and reportable placental lesion language",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Chorioamnionitis.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "gross orientation image or diagram plus H&E lesion anchor"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-10-146a6aef-b3a9-42c3-90ff-7786f0e19599",
      "sourceQueueId": "ap_placenta-146a6aef-b3a9-42c3-90ff-7786f0e19599",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Other fetal membrane abnormalities",
      "category": "Placenta",
      "rotation": "Placenta/perinatal pathology",
      "apSpecPath": "The Placenta > Normal Anatomy and Histology > Fetal Membrane Abnormalities > Other fetal membrane abnormalities",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 3403,
      "specimenContext": "placental disc, membranes, cord, and maternal/fetal surfaces",
      "visualAnchorPlan": "gross orientation image or diagram plus H&E lesion anchor",
      "reportingConsequencePrompt": "maternal/fetal consequence and reportable placental lesion language",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Other fetal membrane abnormalities.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "gross orientation image or diagram plus H&E lesion anchor"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-11-0391c938-98b7-4f43-aee1-226ec67a227a",
      "sourceQueueId": "ap_placenta-0391c938-98b7-4f43-aee1-226ec67a227a",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Abruption",
      "category": "Placenta",
      "rotation": "Placenta/perinatal pathology",
      "apSpecPath": "The Placenta > Normal Anatomy and Histology > Placental Disc Abnormalities > Abruption",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 3405,
      "specimenContext": "placental disc, membranes, cord, and maternal/fetal surfaces",
      "visualAnchorPlan": "gross orientation image or diagram plus H&E lesion anchor",
      "reportingConsequencePrompt": "maternal/fetal consequence and reportable placental lesion language",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Abruption.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "gross orientation image or diagram plus H&E lesion anchor"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-12-9ebe3f0e-f08e-437a-abd2-fe06aee0554e",
      "sourceQueueId": "ap_placenta-9ebe3f0e-f08e-437a-abd2-fe06aee0554e",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Infarcts",
      "category": "Placenta",
      "rotation": "Placenta/perinatal pathology",
      "apSpecPath": "The Placenta > Normal Anatomy and Histology > Placental Disc Abnormalities > Infarcts",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 3406,
      "specimenContext": "placental disc, membranes, cord, and maternal/fetal surfaces",
      "visualAnchorPlan": "gross orientation image or diagram plus H&E lesion anchor",
      "reportingConsequencePrompt": "maternal/fetal consequence and reportable placental lesion language",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Infarcts.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "gross orientation image or diagram plus H&E lesion anchor"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-13-30aabdd9-30e4-4d72-b501-5267be93a4c4",
      "sourceQueueId": "ap_placenta-30aabdd9-30e4-4d72-b501-5267be93a4c4",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Villitis and intervillositis",
      "category": "Placenta",
      "rotation": "Placenta/perinatal pathology",
      "apSpecPath": "The Placenta > Normal Anatomy and Histology > Placental Disc Abnormalities > Villitis and intervillositis",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 3410,
      "specimenContext": "placental disc, membranes, cord, and maternal/fetal surfaces",
      "visualAnchorPlan": "gross orientation image or diagram plus H&E lesion anchor",
      "reportingConsequencePrompt": "maternal/fetal consequence and reportable placental lesion language",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Villitis and intervillositis.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "gross orientation image or diagram plus H&E lesion anchor"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-14-11519070-c819-4729-ab40-3628bfc77152",
      "sourceQueueId": "ap_placenta-11519070-c819-4729-ab40-3628bfc77152",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Umbilical Cord Abnormalities",
      "category": "Placenta",
      "rotation": "Placenta/perinatal pathology",
      "apSpecPath": "The Placenta > Normal Anatomy and Histology > Umbilical Cord Abnormalities",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 3397,
      "specimenContext": "placental disc, membranes, cord, and maternal/fetal surfaces",
      "visualAnchorPlan": "gross orientation image or diagram plus H&E lesion anchor",
      "reportingConsequencePrompt": "maternal/fetal consequence and reportable placental lesion language",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Umbilical Cord Abnormalities.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "gross orientation image or diagram plus H&E lesion anchor"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-15-e8f2ed40-ae50-4f8c-bf9d-7ee2eba1cda3",
      "sourceQueueId": "ap_placenta-e8f2ed40-ae50-4f8c-bf9d-7ee2eba1cda3",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Blood vessel abnormalities",
      "category": "Placenta",
      "rotation": "Placenta/perinatal pathology",
      "apSpecPath": "The Placenta > Normal Anatomy and Histology > Umbilical Cord Abnormalities > Blood vessel abnormalities",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 3398,
      "specimenContext": "placental disc, membranes, cord, and maternal/fetal surfaces",
      "visualAnchorPlan": "gross orientation image or diagram plus H&E lesion anchor",
      "reportingConsequencePrompt": "maternal/fetal consequence and reportable placental lesion language",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Blood vessel abnormalities.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "gross orientation image or diagram plus H&E lesion anchor"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-16-87ab0736-d554-496f-a2c4-cd4b2ae7bbfe",
      "sourceQueueId": "ap_placenta-87ab0736-d554-496f-a2c4-cd4b2ae7bbfe",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Funisitis",
      "category": "Placenta",
      "rotation": "Placenta/perinatal pathology",
      "apSpecPath": "The Placenta > Normal Anatomy and Histology > Umbilical Cord Abnormalities > Funisitis",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 3399,
      "specimenContext": "placental disc, membranes, cord, and maternal/fetal surfaces",
      "visualAnchorPlan": "gross orientation image or diagram plus H&E lesion anchor",
      "reportingConsequencePrompt": "maternal/fetal consequence and reportable placental lesion language",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Funisitis.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "gross orientation image or diagram plus H&E lesion anchor"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-17-3861597c-5448-414e-911a-dd3237dc0272",
      "sourceQueueId": "ap_gi-3861597c-5448-414e-911a-dd3237dc0272",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Amebic colitis",
      "category": "Gastrointestinal",
      "rotation": "GI pathology",
      "apSpecPath": "The Digestive System > The Gastrointestinal Tract > Familial Colorectal Cancer Syndromes > Amebic colitis",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 2182,
      "specimenContext": "endoscopic biopsy or resection from the relevant GI site",
      "visualAnchorPlan": "low-power architecture plus high-power diagnostic feature",
      "reportingConsequencePrompt": "diagnosis, activity/chronicity, dysplasia/neoplasia status, or management-relevant comment",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Amebic colitis.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power architecture plus high-power diagnostic feature"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-18-be26cbed-b3e6-4693-b09c-adfba6cec5b7",
      "sourceQueueId": "ap_gi-be26cbed-b3e6-4693-b09c-adfba6cec5b7",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Appendicitis",
      "category": "Gastrointestinal",
      "rotation": "GI pathology",
      "apSpecPath": "The Digestive System > The Gastrointestinal Tract > Familial Colorectal Cancer Syndromes > Appendicitis",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 2247,
      "specimenContext": "endoscopic biopsy or resection from the relevant GI site",
      "visualAnchorPlan": "low-power architecture plus high-power diagnostic feature",
      "reportingConsequencePrompt": "diagnosis, activity/chronicity, dysplasia/neoplasia status, or management-relevant comment",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Appendicitis.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power architecture plus high-power diagnostic feature"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-19-f02e61e2-6e6d-44bc-a66f-320a017c2776",
      "sourceQueueId": "ap_gi-f02e61e2-6e6d-44bc-a66f-320a017c2776",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Crohn's disease",
      "category": "Gastrointestinal",
      "rotation": "GI pathology",
      "apSpecPath": "The Digestive System > The Gastrointestinal Tract > Familial Colorectal Cancer Syndromes > Crohn's disease",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 2118,
      "specimenContext": "endoscopic biopsy or resection from the relevant GI site",
      "visualAnchorPlan": "low-power architecture plus high-power diagnostic feature",
      "reportingConsequencePrompt": "diagnosis, activity/chronicity, dysplasia/neoplasia status, or management-relevant comment",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Crohn's disease.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power architecture plus high-power diagnostic feature"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-20-5913044e-b704-4f0f-a81f-3959137b143c",
      "sourceQueueId": "ap_gi-5913044e-b704-4f0f-a81f-3959137b143c",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Enterobius vermicularis",
      "category": "Gastrointestinal",
      "rotation": "GI pathology",
      "apSpecPath": "The Digestive System > The Gastrointestinal Tract > Familial Colorectal Cancer Syndromes > Enterobius vermicularis",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 2248,
      "specimenContext": "endoscopic biopsy or resection from the relevant GI site",
      "visualAnchorPlan": "low-power architecture plus high-power diagnostic feature",
      "reportingConsequencePrompt": "diagnosis, activity/chronicity, dysplasia/neoplasia status, or management-relevant comment",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Enterobius vermicularis.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power architecture plus high-power diagnostic feature"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-21-bbdb2542-3a5c-41dd-ae5a-938d60b7cf05",
      "sourceQueueId": "ap_gi-bbdb2542-3a5c-41dd-ae5a-938d60b7cf05",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Pneumatosis coli",
      "category": "Gastrointestinal",
      "rotation": "GI pathology",
      "apSpecPath": "The Digestive System > The Gastrointestinal Tract > Familial Colorectal Cancer Syndromes > Pneumatosis coli",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 2119,
      "specimenContext": "endoscopic biopsy or resection from the relevant GI site",
      "visualAnchorPlan": "low-power architecture plus high-power diagnostic feature",
      "reportingConsequencePrompt": "diagnosis, activity/chronicity, dysplasia/neoplasia status, or management-relevant comment",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Pneumatosis coli.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power architecture plus high-power diagnostic feature"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-22-783f1f8c-c70a-48d3-baf4-1804002a5432",
      "sourceQueueId": "ap_gi-783f1f8c-c70a-48d3-baf4-1804002a5432",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Pseudomembranous colitis (C. difficile colitis)",
      "category": "Gastrointestinal",
      "rotation": "GI pathology",
      "apSpecPath": "The Digestive System > The Gastrointestinal Tract > Familial Colorectal Cancer Syndromes > Pseudomembranous colitis (C. difficile colitis)",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 2181,
      "specimenContext": "endoscopic biopsy or resection from the relevant GI site",
      "visualAnchorPlan": "low-power architecture plus high-power diagnostic feature",
      "reportingConsequencePrompt": "diagnosis, activity/chronicity, dysplasia/neoplasia status, or management-relevant comment",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Pseudomembranous colitis (C. difficile colitis).",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power architecture plus high-power diagnostic feature"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-23-a68c0f28-2d32-4388-9724-12c991a2dca7",
      "sourceQueueId": "ap_gi-a68c0f28-2d32-4388-9724-12c991a2dca7",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Serrated polyps",
      "category": "Gastrointestinal",
      "rotation": "GI pathology",
      "apSpecPath": "The Digestive System > The Gastrointestinal Tract > Familial Colorectal Cancer Syndromes > Serrated polyps",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 2189,
      "specimenContext": "endoscopic biopsy or resection from the relevant GI site",
      "visualAnchorPlan": "low-power architecture plus high-power diagnostic feature",
      "reportingConsequencePrompt": "diagnosis, activity/chronicity, dysplasia/neoplasia status, or management-relevant comment",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Serrated polyps.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power architecture plus high-power diagnostic feature"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-card-24-39ea9242-9a84-4420-8000-ee2428bc5450",
      "sourceQueueId": "ap_gi-39ea9242-9a84-4420-8000-ee2428bc5450",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Ulcerative colitis",
      "category": "Gastrointestinal",
      "rotation": "GI pathology",
      "apSpecPath": "The Digestive System > The Gastrointestinal Tract > Familial Colorectal Cancer Syndromes > Ulcerative colitis",
      "learnerLevel": "PGY1-PGY2",
      "sourceLine": 2117,
      "specimenContext": "endoscopic biopsy or resection from the relevant GI site",
      "visualAnchorPlan": "low-power architecture plus high-power diagnostic feature",
      "reportingConsequencePrompt": "diagnosis, activity/chronicity, dysplasia/neoplasia status, or management-relevant comment",
      "entityCardSections": [
        "Definition and scope in one learner-safe sentence",
        "Normal or reactive comparator before abnormal pattern",
        "Key morphology anchor with one low-power cue and one high-power cue",
        "Top mimic and the single best discriminator",
        "Ancillary or reporting consequence",
        "Pitfall that could cause a safety-critical miss"
      ],
      "retrievalPrompts": [
        "Before reveal: name the entity or process represented by Ulcerative colitis.",
        "State one feature that must be present before calling it.",
        "Name the closest mimic and the discriminator that separates them.",
        "Write the report or comment phrase that would matter clinically."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this is a true content entity/process/reporting task.",
        "Source citation and review date are attached.",
        "Image/gross/diagram asset is licensed, local, or explicitly deferred.",
        "Answer key is faculty-reviewed before learner reveal.",
        "One near-miss or mimic is included for contrastive learning."
      ],
      "completionGate": "Not complete until entity card, visual anchor, retrieval answer key, and faculty QA metadata are all present.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from normalized AP specification path; faculty must confirm entity/process classification."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Definition, morphology, mimic discriminator, pitfall, and report language still require source-backed authoring."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power architecture plus high-power diagnostic feature"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Prompts exist; faculty-reviewed answer key is not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Reviewer, source citation, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    }
  ]
} as const;

export type ApP0EntityCard = typeof apP0EntityCardBatch.cards[number];
