// Generated by scripts/generate_ap_p0_endo_cards_2.cjs. Do not edit by hand.

export const apP0EndocrineCardBatch2 = {
  "generatedAt": "2026-05-15T22:35:19.797Z",
  "sourcePlan": "reports/ap_gap_closure_plan.json",
  "sourceQueue": "src/content/competency/apGapClosureQueue.ts",
  "facultyPacketPath": "reports/ap_p0_endocrine_card_batch_2_faculty_packet.md",
  "facultyPacketCsvPath": "reports/ap_p0_endocrine_card_batch_2_faculty_packet.csv",
  "batchName": "P0 endocrine entity card batch 2",
  "batchStrategy": "All remaining unused P0 Endocrine rows from the AP gap closure queue after excluding sourceQueueIds already present in existing apP0*CardBatch.ts files; taxonomy-risk rows require keep/reassign QA before medical authoring.",
  "sourceCategory": "ap_endo",
  "sourceP0Rows": 40,
  "existingSourceQueueIdsExcluded": 24,
  "selectedRows": 16,
  "status": "draft endocrine remainder scaffolds awaiting taxonomy QA, source-backed content, visual anchors or reassignment rationale, retrieval answer keys, and faculty review",
  "batchReadiness": {
    "completedGates": 0,
    "reviewReadyGates": 16,
    "missingGates": 64,
    "totalGates": 80,
    "percentComplete": 0,
    "percentReviewReady": 20
  },
  "readinessLegend": {
    "complete": "Evidence is present and reviewed.",
    "ready-for-review": "Structured scaffold exists and needs endocrine/taxonomy faculty confirmation.",
    "missing": "Required source-backed content, visual asset or reassignment rationale, answer key, or reviewer evidence is not yet attached."
  },
  "cards": [
    {
      "id": "p0-endo-batch-2-card-01-29ccdc24-a32b-4bb5-817e-380c55115fb1",
      "sourceQueueId": "ap_endo-29ccdc24-a32b-4bb5-817e-380c55115fb1",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Non-Immune (e.g., Thermal Injury)",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > The Skin and Nails > Non-Immune (e.g., Thermal Injury)",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 11941,
      "endocrineOrganFocus": "taxonomy-review endocrine remainder row",
      "taxonomyRisk": "high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content",
      "specimenContext": "endocrine or endocrine-adjacent specimen only after faculty taxonomy QA confirms the row belongs here; otherwise document the correct AP domain and remove from endocrine learner view",
      "normalComparatorPrompt": "faculty-selected normal endocrine comparator, or a taxonomy-correction note explaining why an endocrine comparator is inappropriate",
      "visualAnchorPlan": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale",
      "mimicDiscriminatorPrompt": "faculty must identify the closest endocrine mimic, systemic mimic, or correct-domain reassignment before content authoring",
      "reportingConsequencePrompt": "do not add learner-facing reporting language until taxonomy QA determines whether this is endocrine, endocrine-adjacent, or misclassified AP-spec content",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Non-Immune (e.g., Thermal Injury) is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 11941; high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-02-f073ec35-2001-4493-a5e3-f77cf39cb9b3",
      "sourceQueueId": "ap_endo-f073ec35-2001-4493-a5e3-f77cf39cb9b3",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Hb S and Related Disorders",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > The Skin and Nails > Hb S and Related Disorders",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 12021,
      "endocrineOrganFocus": "taxonomy-review endocrine remainder row",
      "taxonomyRisk": "high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content",
      "specimenContext": "endocrine or endocrine-adjacent specimen only after faculty taxonomy QA confirms the row belongs here; otherwise document the correct AP domain and remove from endocrine learner view",
      "normalComparatorPrompt": "faculty-selected normal endocrine comparator, or a taxonomy-correction note explaining why an endocrine comparator is inappropriate",
      "visualAnchorPlan": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale",
      "mimicDiscriminatorPrompt": "faculty must identify the closest endocrine mimic, systemic mimic, or correct-domain reassignment before content authoring",
      "reportingConsequencePrompt": "do not add learner-facing reporting language until taxonomy QA determines whether this is endocrine, endocrine-adjacent, or misclassified AP-spec content",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Hb S and Related Disorders is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 12021; high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-03-4b3ce1a2-7423-4c0c-ace2-f529bb549a96",
      "sourceQueueId": "ap_endo-4b3ce1a2-7423-4c0c-ace2-f529bb549a96",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Lead Poisoning",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > The Skin and Nails > Lead Poisoning",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 12033,
      "endocrineOrganFocus": "taxonomy-review endocrine remainder row",
      "taxonomyRisk": "high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content",
      "specimenContext": "endocrine or endocrine-adjacent specimen only after faculty taxonomy QA confirms the row belongs here; otherwise document the correct AP domain and remove from endocrine learner view",
      "normalComparatorPrompt": "faculty-selected normal endocrine comparator, or a taxonomy-correction note explaining why an endocrine comparator is inappropriate",
      "visualAnchorPlan": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale",
      "mimicDiscriminatorPrompt": "faculty must identify the closest endocrine mimic, systemic mimic, or correct-domain reassignment before content authoring",
      "reportingConsequencePrompt": "do not add learner-facing reporting language until taxonomy QA determines whether this is endocrine, endocrine-adjacent, or misclassified AP-spec content",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Lead Poisoning is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 12033; high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-04-acb6750e-f5f9-4671-996f-a198aa3bc7a2",
      "sourceQueueId": "ap_endo-acb6750e-f5f9-4671-996f-a198aa3bc7a2",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Monocytes – Quantitative & Qualitative Aspects",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > The Skin and Nails > Non-Neoplastic Disorders of Leucocytes > Monocytes – Quantitative & Qualitative Aspects",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 12061,
      "endocrineOrganFocus": "taxonomy-review endocrine remainder row",
      "taxonomyRisk": "high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content",
      "specimenContext": "endocrine or endocrine-adjacent specimen only after faculty taxonomy QA confirms the row belongs here; otherwise document the correct AP domain and remove from endocrine learner view",
      "normalComparatorPrompt": "faculty-selected normal endocrine comparator, or a taxonomy-correction note explaining why an endocrine comparator is inappropriate",
      "visualAnchorPlan": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale",
      "mimicDiscriminatorPrompt": "faculty must identify the closest endocrine mimic, systemic mimic, or correct-domain reassignment before content authoring",
      "reportingConsequencePrompt": "do not add learner-facing reporting language until taxonomy QA determines whether this is endocrine, endocrine-adjacent, or misclassified AP-spec content",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Monocytes – Quantitative & Qualitative Aspects is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 12061; high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-05-0b7ce8a1-90dc-4a87-8f98-cf14a51e7f50",
      "sourceQueueId": "ap_endo-0b7ce8a1-90dc-4a87-8f98-cf14a51e7f50",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Leucocyte Infections",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > The Skin and Nails > Infections with Manifestation in the Peripheral Blood > Leucocyte Infections",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 12103,
      "endocrineOrganFocus": "taxonomy-review endocrine remainder row",
      "taxonomyRisk": "high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content",
      "specimenContext": "endocrine or endocrine-adjacent specimen only after faculty taxonomy QA confirms the row belongs here; otherwise document the correct AP domain and remove from endocrine learner view",
      "normalComparatorPrompt": "faculty-selected normal endocrine comparator, or a taxonomy-correction note explaining why an endocrine comparator is inappropriate",
      "visualAnchorPlan": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale",
      "mimicDiscriminatorPrompt": "faculty must identify the closest endocrine mimic, systemic mimic, or correct-domain reassignment before content authoring",
      "reportingConsequencePrompt": "do not add learner-facing reporting language until taxonomy QA determines whether this is endocrine, endocrine-adjacent, or misclassified AP-spec content",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Leucocyte Infections is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 12103; high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-06-7fd770b3-f648-473c-b68b-a12a1ffd69ab",
      "sourceQueueId": "ap_endo-7fd770b3-f648-473c-b68b-a12a1ffd69ab",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Fluid Specimens",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > The Skin and Nails > Fluid Specimens",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 12240,
      "endocrineOrganFocus": "taxonomy-review endocrine remainder row",
      "taxonomyRisk": "high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content",
      "specimenContext": "endocrine or endocrine-adjacent specimen only after faculty taxonomy QA confirms the row belongs here; otherwise document the correct AP domain and remove from endocrine learner view",
      "normalComparatorPrompt": "faculty-selected normal endocrine comparator, or a taxonomy-correction note explaining why an endocrine comparator is inappropriate",
      "visualAnchorPlan": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale",
      "mimicDiscriminatorPrompt": "faculty must identify the closest endocrine mimic, systemic mimic, or correct-domain reassignment before content authoring",
      "reportingConsequencePrompt": "do not add learner-facing reporting language until taxonomy QA determines whether this is endocrine, endocrine-adjacent, or misclassified AP-spec content",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Fluid Specimens is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 12240; high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-07-df71d1a1-6098-4098-8dda-f119adc37f95",
      "sourceQueueId": "ap_endo-df71d1a1-6098-4098-8dda-f119adc37f95",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "CSF",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > The Skin and Nails > Fluid Specimens > CSF",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 12241,
      "endocrineOrganFocus": "taxonomy-review endocrine remainder row",
      "taxonomyRisk": "high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content",
      "specimenContext": "endocrine or endocrine-adjacent specimen only after faculty taxonomy QA confirms the row belongs here; otherwise document the correct AP domain and remove from endocrine learner view",
      "normalComparatorPrompt": "faculty-selected normal endocrine comparator, or a taxonomy-correction note explaining why an endocrine comparator is inappropriate",
      "visualAnchorPlan": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale",
      "mimicDiscriminatorPrompt": "faculty must identify the closest endocrine mimic, systemic mimic, or correct-domain reassignment before content authoring",
      "reportingConsequencePrompt": "do not add learner-facing reporting language until taxonomy QA determines whether this is endocrine, endocrine-adjacent, or misclassified AP-spec content",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether CSF is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 12241; high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-08-df7e7e54-569a-424c-9341-d0135dcd8d31",
      "sourceQueueId": "ap_endo-df7e7e54-569a-424c-9341-d0135dcd8d31",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Immune",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > The Skin and Nails > Immune",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 12335,
      "endocrineOrganFocus": "taxonomy-review endocrine remainder row",
      "taxonomyRisk": "high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content",
      "specimenContext": "endocrine or endocrine-adjacent specimen only after faculty taxonomy QA confirms the row belongs here; otherwise document the correct AP domain and remove from endocrine learner view",
      "normalComparatorPrompt": "faculty-selected normal endocrine comparator, or a taxonomy-correction note explaining why an endocrine comparator is inappropriate",
      "visualAnchorPlan": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale",
      "mimicDiscriminatorPrompt": "faculty must identify the closest endocrine mimic, systemic mimic, or correct-domain reassignment before content authoring",
      "reportingConsequencePrompt": "do not add learner-facing reporting language until taxonomy QA determines whether this is endocrine, endocrine-adjacent, or misclassified AP-spec content",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Immune is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 12335; high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-09-b2f370e8-9df4-44f1-885e-00dd2e6255db",
      "sourceQueueId": "ap_endo-b2f370e8-9df4-44f1-885e-00dd2e6255db",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Inherited",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > The Skin and Nails > Inherited",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 12336,
      "endocrineOrganFocus": "taxonomy-review endocrine remainder row",
      "taxonomyRisk": "high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content",
      "specimenContext": "endocrine or endocrine-adjacent specimen only after faculty taxonomy QA confirms the row belongs here; otherwise document the correct AP domain and remove from endocrine learner view",
      "normalComparatorPrompt": "faculty-selected normal endocrine comparator, or a taxonomy-correction note explaining why an endocrine comparator is inappropriate",
      "visualAnchorPlan": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale",
      "mimicDiscriminatorPrompt": "faculty must identify the closest endocrine mimic, systemic mimic, or correct-domain reassignment before content authoring",
      "reportingConsequencePrompt": "do not add learner-facing reporting language until taxonomy QA determines whether this is endocrine, endocrine-adjacent, or misclassified AP-spec content",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Inherited is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 12336; high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-10-2126e936-be8a-4ecc-ac76-1fb85199e2da",
      "sourceQueueId": "ap_endo-2126e936-be8a-4ecc-ac76-1fb85199e2da",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Other Causes of Thrombocytopenia",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > The Skin and Nails > Other Causes of Thrombocytopenia",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 12337,
      "endocrineOrganFocus": "taxonomy-review endocrine remainder row",
      "taxonomyRisk": "high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content",
      "specimenContext": "endocrine or endocrine-adjacent specimen only after faculty taxonomy QA confirms the row belongs here; otherwise document the correct AP domain and remove from endocrine learner view",
      "normalComparatorPrompt": "faculty-selected normal endocrine comparator, or a taxonomy-correction note explaining why an endocrine comparator is inappropriate",
      "visualAnchorPlan": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale",
      "mimicDiscriminatorPrompt": "faculty must identify the closest endocrine mimic, systemic mimic, or correct-domain reassignment before content authoring",
      "reportingConsequencePrompt": "do not add learner-facing reporting language until taxonomy QA determines whether this is endocrine, endocrine-adjacent, or misclassified AP-spec content",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Other Causes of Thrombocytopenia is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 12337; high taxonomy risk; this row is currently mapped to endocrine but its title/path may indicate skin, hematology, fluid, immune, infectious, or systemic content"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "taxonomy QA image plan: attach endocrine normal-to-abnormal anchor only after confirmed placement, or document no-image/reassignment rationale"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-11-51189037-75fc-4d0d-b402-572deea80a2f",
      "sourceQueueId": "ap_endo-51189037-75fc-4d0d-b402-572deea80a2f",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Malformation",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > Normal Anatomy, Histology, and Development > Medullary, including C-cell Hyperplasia > Malformation",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 16979,
      "endocrineOrganFocus": "thyroid / medullary C-cell axis",
      "taxonomyRisk": "plausible endocrine row; faculty should confirm whether the AP-spec path is thyroid medullary/C-cell content or a misplaced developmental/systemic row",
      "specimenContext": "thyroidectomy, thyroid lobectomy, neck endocrine specimen, or developmental/endocrine correlation specimen with gross site and clinical syndrome context",
      "normalComparatorPrompt": "normal thyroid follicles and expected C-cell distribution before abnormal medullary, developmental, or hormonal-synthesis pattern recognition",
      "visualAnchorPlan": "low-power thyroid/C-cell anatomic orientation plus high-power abnormality cue, with a normal thyroid comparator and explicit note if no representative image is available",
      "mimicDiscriminatorPrompt": "reactive C-cell change, medullary thyroid carcinoma spectrum, developmental anomaly, endocrine cytomegaly, inherited hormonal synthesis disorder, and taxonomy artifact",
      "reportingConsequencePrompt": "state whether the card teaches a diagnosable lesion, developmental finding, inherited endocrine syndrome, or taxonomy correction; add reporting or genetic/clinical correlation consequence only after faculty review",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Malformation is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 16979; plausible endocrine row; faculty should confirm whether the AP-spec path is thyroid medullary/C-cell content or a misplaced developmental/systemic row"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power thyroid/C-cell anatomic orientation plus high-power abnormality cue, with a normal thyroid comparator and explicit note if no representative image is available"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-12-4af23953-d355-43d6-b742-592cb0645c65",
      "sourceQueueId": "ap_endo-4af23953-d355-43d6-b742-592cb0645c65",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Hypoplasia",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > Normal Anatomy, Histology, and Development > Medullary, including C-cell Hyperplasia > Hypoplasia",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 16980,
      "endocrineOrganFocus": "thyroid / medullary C-cell axis",
      "taxonomyRisk": "plausible endocrine row; faculty should confirm whether the AP-spec path is thyroid medullary/C-cell content or a misplaced developmental/systemic row",
      "specimenContext": "thyroidectomy, thyroid lobectomy, neck endocrine specimen, or developmental/endocrine correlation specimen with gross site and clinical syndrome context",
      "normalComparatorPrompt": "normal thyroid follicles and expected C-cell distribution before abnormal medullary, developmental, or hormonal-synthesis pattern recognition",
      "visualAnchorPlan": "low-power thyroid/C-cell anatomic orientation plus high-power abnormality cue, with a normal thyroid comparator and explicit note if no representative image is available",
      "mimicDiscriminatorPrompt": "reactive C-cell change, medullary thyroid carcinoma spectrum, developmental anomaly, endocrine cytomegaly, inherited hormonal synthesis disorder, and taxonomy artifact",
      "reportingConsequencePrompt": "state whether the card teaches a diagnosable lesion, developmental finding, inherited endocrine syndrome, or taxonomy correction; add reporting or genetic/clinical correlation consequence only after faculty review",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Hypoplasia is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 16980; plausible endocrine row; faculty should confirm whether the AP-spec path is thyroid medullary/C-cell content or a misplaced developmental/systemic row"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power thyroid/C-cell anatomic orientation plus high-power abnormality cue, with a normal thyroid comparator and explicit note if no representative image is available"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-13-6d1be720-bf85-4aa9-9539-9d2891cf898e",
      "sourceQueueId": "ap_endo-6d1be720-bf85-4aa9-9539-9d2891cf898e",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Cytomegaly",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > Normal Anatomy, Histology, and Development > Medullary, including C-cell Hyperplasia > Cytomegaly",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 16981,
      "endocrineOrganFocus": "thyroid / medullary C-cell axis",
      "taxonomyRisk": "plausible endocrine row; faculty should confirm whether the AP-spec path is thyroid medullary/C-cell content or a misplaced developmental/systemic row",
      "specimenContext": "thyroidectomy, thyroid lobectomy, neck endocrine specimen, or developmental/endocrine correlation specimen with gross site and clinical syndrome context",
      "normalComparatorPrompt": "normal thyroid follicles and expected C-cell distribution before abnormal medullary, developmental, or hormonal-synthesis pattern recognition",
      "visualAnchorPlan": "low-power thyroid/C-cell anatomic orientation plus high-power abnormality cue, with a normal thyroid comparator and explicit note if no representative image is available",
      "mimicDiscriminatorPrompt": "reactive C-cell change, medullary thyroid carcinoma spectrum, developmental anomaly, endocrine cytomegaly, inherited hormonal synthesis disorder, and taxonomy artifact",
      "reportingConsequencePrompt": "state whether the card teaches a diagnosable lesion, developmental finding, inherited endocrine syndrome, or taxonomy correction; add reporting or genetic/clinical correlation consequence only after faculty review",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Cytomegaly is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 16981; plausible endocrine row; faculty should confirm whether the AP-spec path is thyroid medullary/C-cell content or a misplaced developmental/systemic row"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power thyroid/C-cell anatomic orientation plus high-power abnormality cue, with a normal thyroid comparator and explicit note if no representative image is available"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-14-96a40849-b40b-40a5-a9c8-cfef680e6739",
      "sourceQueueId": "ap_endo-96a40849-b40b-40a5-a9c8-cfef680e6739",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Disorders of Hormonal Synthesis",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > Normal Anatomy, Histology, and Development > Medullary, including C-cell Hyperplasia > Cytomegaly > Disorders of Hormonal Synthesis",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 16982,
      "endocrineOrganFocus": "thyroid / medullary C-cell axis",
      "taxonomyRisk": "plausible endocrine row; faculty should confirm whether the AP-spec path is thyroid medullary/C-cell content or a misplaced developmental/systemic row",
      "specimenContext": "thyroidectomy, thyroid lobectomy, neck endocrine specimen, or developmental/endocrine correlation specimen with gross site and clinical syndrome context",
      "normalComparatorPrompt": "normal thyroid follicles and expected C-cell distribution before abnormal medullary, developmental, or hormonal-synthesis pattern recognition",
      "visualAnchorPlan": "low-power thyroid/C-cell anatomic orientation plus high-power abnormality cue, with a normal thyroid comparator and explicit note if no representative image is available",
      "mimicDiscriminatorPrompt": "reactive C-cell change, medullary thyroid carcinoma spectrum, developmental anomaly, endocrine cytomegaly, inherited hormonal synthesis disorder, and taxonomy artifact",
      "reportingConsequencePrompt": "state whether the card teaches a diagnosable lesion, developmental finding, inherited endocrine syndrome, or taxonomy correction; add reporting or genetic/clinical correlation consequence only after faculty review",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Disorders of Hormonal Synthesis is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 16982; plausible endocrine row; faculty should confirm whether the AP-spec path is thyroid medullary/C-cell content or a misplaced developmental/systemic row"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power thyroid/C-cell anatomic orientation plus high-power abnormality cue, with a normal thyroid comparator and explicit note if no representative image is available"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-15-7cf53ebb-6230-4159-9410-486790e8b9ff",
      "sourceQueueId": "ap_endo-7cf53ebb-6230-4159-9410-486790e8b9ff",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Post-Transplant Lymphoproliferative Disorder (PTLD)",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > Normal Anatomy, Histology, and Development > Post-Transplant Lymphoproliferative Disorder (PTLD)",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 17087,
      "endocrineOrganFocus": "endocrine-adjacent immunocompromised-host process",
      "taxonomyRisk": "high taxonomy risk; row appears under endocrine but may represent systemic infectious/hematolymphoid or transplant-associated content",
      "specimenContext": "endocrine-site biopsy/resection only if the lesion involves thyroid, adrenal, parathyroid, pancreas, or pituitary; otherwise document reassignment",
      "normalComparatorPrompt": "site-specific normal endocrine tissue and background inflammatory/lymphoid distribution before calling infection, PTLD, or viral-associated disease",
      "visualAnchorPlan": "endocrine-site tissue with infectious/lymphoid process, or a no-image taxonomy-correction rationale if the entity belongs outside endocrine",
      "mimicDiscriminatorPrompt": "reactive lymphoid infiltrate, autoimmune thyroiditis, infection, lymphoma, PTLD, metastatic disease, and endocrine taxonomy artifact",
      "reportingConsequencePrompt": "capture immunocompromised-host safety language, EBV/viral or immunophenotypic workup trigger, and reassignment decision before learner release",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Post-Transplant Lymphoproliferative Disorder (PTLD) is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 17087; high taxonomy risk; row appears under endocrine but may represent systemic infectious/hematolymphoid or transplant-associated content"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "endocrine-site tissue with infectious/lymphoid process, or a no-image taxonomy-correction rationale if the entity belongs outside endocrine"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-endo-batch-2-card-16-3437eb7d-29e1-4e05-9ca9-47a970f10438",
      "sourceQueueId": "ap_endo-3437eb7d-29e1-4e05-9ca9-47a970f10438",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Viral Associated Conditions, including HIV",
      "category": "Endocrine",
      "rotation": "Endocrine pathology",
      "apSpecPath": "The Endocrine System > Normal Anatomy, Histology, and Development > Viral Associated Conditions, including HIV",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 17088,
      "endocrineOrganFocus": "endocrine-adjacent immunocompromised-host process",
      "taxonomyRisk": "high taxonomy risk; row appears under endocrine but may represent systemic infectious/hematolymphoid or transplant-associated content",
      "specimenContext": "endocrine-site biopsy/resection only if the lesion involves thyroid, adrenal, parathyroid, pancreas, or pituitary; otherwise document reassignment",
      "normalComparatorPrompt": "site-specific normal endocrine tissue and background inflammatory/lymphoid distribution before calling infection, PTLD, or viral-associated disease",
      "visualAnchorPlan": "endocrine-site tissue with infectious/lymphoid process, or a no-image taxonomy-correction rationale if the entity belongs outside endocrine",
      "mimicDiscriminatorPrompt": "reactive lymphoid infiltrate, autoimmune thyroiditis, infection, lymphoma, PTLD, metastatic disease, and endocrine taxonomy artifact",
      "reportingConsequencePrompt": "capture immunocompromised-host safety language, EBV/viral or immunophenotypic workup trigger, and reassignment decision before learner release",
      "entityCardSections": [
        "Endocrine remainder taxonomy QA and keep/reassign decision",
        "Definition and scope in one learner-safe sentence after source review",
        "Normal endocrine comparator or explicit correct-domain comparator if reassigned",
        "Low-power anatomic/site anchor or reason no endocrine image is appropriate",
        "High-power morphology or systemic-process cue after taxonomy confirmation",
        "Top endocrine mimic or correct-domain mimic and single best discriminator",
        "Ancillary, molecular, infectious, genetic, functional, or reporting consequence when relevant",
        "Pitfall that could create a clinically meaningful miss or taxonomy teaching error"
      ],
      "retrievalPrompts": [
        "Before reveal: decide whether Viral Associated Conditions, including HIV is endocrine, endocrine-adjacent, or misclassified for this AP-spec path.",
        "State the normal comparator or explain why the correct comparator belongs outside endocrine.",
        "Name the closest mimic and the discriminator or reassignment evidence that separates them.",
        "State any ancillary, infectious, genetic, molecular, functional, or clinical correlation that would matter.",
        "Write the safe report/comment or taxonomy note that should appear before learner release."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms endocrine placement or documents correct AP-domain reassignment.",
        "Definition, scope, comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image/reassignment rationale.",
        "Retrieval answer key is reviewed before learner reveal.",
        "One contrastive near-miss or taxonomy pitfall is included for durable discrimination.",
        "Editorial status prevents misclassified content from appearing as canonical endocrine material."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed content, visual anchor or reassignment rationale, retrieval answer key, and faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Unused ap_endo P0 row at source line 17088; high taxonomy risk; row appears under endocrine but may represent systemic infectious/hematolymphoid or transplant-associated content"
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition/scope, normal comparator or taxonomy correction, morphology, mimic discriminator, pitfall, and learner-safe consequence."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "endocrine-site tissue with infectious/lymphoid process, or a no-image taxonomy-correction rationale if the entity belongs outside endocrine"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Remainder-batch retrieval prompts are scaffolded; faculty-reviewed answers and spaced-repeat reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Endocrine faculty/taxonomy reviewer, source citation, image/license or reassignment status, editorial decision, and review date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    }
  ]
} as const;

export type ApP0EndocrineCard2 = typeof apP0EndocrineCardBatch2.cards[number];
