// Generated by scripts/generate_ap_p0_breast_cards.cjs. Do not edit by hand.

export const apP0BreastCardBatch = {
  "generatedAt": "2026-05-29T20:31:41.119Z",
  "sourcePlan": "reports/ap_gap_closure_plan.json",
  "sourceQueue": "src/content/competency/apGapClosureQueue.ts",
  "excludedExistingSourceQueueIds": 196,
  "excludedParserSpilloverRows": 12,
  "excludedParserSpilloverRule": "Exclude AP parser spillover paths that begin with Breast > Lung Primary from the Breast entity-card product.",
  "facultyPacketPath": "reports/ap_p0_breast_card_batch_faculty_packet.md",
  "facultyPacketCsvPath": "reports/ap_p0_breast_card_batch_faculty_packet.csv",
  "batchName": "P0 breast entity card batch",
  "batchStrategy": "All available unassigned P0 Breast rows, excluding Lung Primary parser spillover, capped at 24, converted into normal-comparator and concordance-aware draft scaffolds with five readiness gates.",
  "status": "draft content attached; awaiting faculty review, citation, and asset/license completion",
  "categoryCoverage": {
    "categoryId": "ap_breast",
    "category": "Breast",
    "queueP0Rows": 19,
    "parserSpilloverRowsExcluded": 12,
    "eligibleBreastP0Rows": 7,
    "selectedCards": 7
  },
  "batchReadiness": {
    "completedGates": 0,
    "reviewReadyGates": 28,
    "missingGates": 7,
    "totalGates": 35,
    "percentComplete": 0,
    "percentReviewReady": 80
  },
  "readinessLegend": {
    "complete": "Evidence is present and reviewed.",
    "ready-for-review": "Structured scaffold exists and needs breast pathology faculty confirmation.",
    "missing": "Required breast content, asset, source, answer key, or reviewer evidence is not yet attached."
  },
  "cards": [
    {
      "id": "p0-breast-card-01-b82b09fd-c24e-4aec-9ac7-a08c7ab5c109",
      "sourceQueueId": "ap_breast-b82b09fd-c24e-4aec-9ac7-a08c7ab5c109",
      "editorialStatus": "draft-content-ready-for-review",
      "priority": "P0 core board/sign-out gap",
      "title": "Cysts",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Cysts",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 324,
      "learningFrame": "normal-to-abnormal breast foundation",
      "specimenContext": "core biopsy, excision, or reduction mammoplasty specimen with terminal duct lobular unit orientation and radiology correlation when applicable",
      "normalComparatorPrompt": "normal terminal duct lobular unit, duct, lobule, stroma, and myoepithelial layer before lesion-level interpretation",
      "visualAnchorPlan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
      "mimicDiscriminatorPrompt": "benign proliferative change, fibroepithelial lesion, vascular lesion, therapy effect, or invasive carcinoma mimic as appropriate",
      "ancillaryDecisionPrompt": "state whether myoepithelial markers, ER/PR/HER2, or no ancillary testing is appropriate for this teaching target",
      "reportingConsequencePrompt": "safe benign report wording, radiology-pathology concordance, or escalation trigger when morphology is discordant",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Cysts.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until drafted content, visual inspection plan, retrieval key, and taxonomy scaffold receive faculty QA plus citation/reviewer metadata.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 324; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "ready-for-review",
          "evidence": "Deterministic draft entity card content attached from ABPath path, organ-system profile, mimic/discriminator template, and report-consequence scaffold; requires faculty fact-check before canonical release."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "ready-for-review",
          "evidence": "Visual inspection sequence attached; asset remains pending. Plan: normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "ready-for-review",
          "evidence": "Draft retrieval answer key attached for entity/process, required feature, mimic discriminator, and report consequence; requires faculty review before learner answer reveal is canonical."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 4,
        "missingGates": 1,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 80
      },
      "entityCardDraft": {
        "definition": "Cysts is treated in this curriculum as an ABPath AP content-specification topic within Diabetic mastopathy; learners should first confirm the specimen context, then decide whether the process is a true entity, pattern, specimen task, or reportable finding.",
        "normalComparator": "Compare against normal terminal duct lobular unit or expected breast stroma/epithelium before labeling the abnormality.",
        "morphologyAnchor": "Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Cysts.",
        "topMimic": "usual hyperplasia, reactive change, in situ carcinoma, invasive carcinoma, or treatment effect depending on the path context",
        "discriminator": "architecture plus cytologic atypia, myoepithelial pattern, biomarker context, and whether invasion or concordance changes management",
        "ancillaryOrReportingConsequence": "ER/PR/HER2, myoepithelial stains, margin/synoptic language, or radiology-pathology concordance when relevant",
        "safetyPitfall": "missing invasion, overcalling reactive/proliferative change, or omitting biomarker/concordance language that changes care",
        "sourceBasis": "Drafted from ABPath AP content-spec path: Breast > Normal Anatomy and Histology > Diabetic mastopathy > Cysts. Source line: 324.",
        "scopedDomain": "Breast"
      },
      "retrievalAnswerKey": [
        {
          "prompt": "Before reveal: name the entity or process represented by Cysts.",
          "answer": "Cysts; scoped to Diabetic mastopathy in the ABPath AP content specifications.",
          "reasoning": "Start by naming the content-spec target and its organ-system location before adding details."
        },
        {
          "prompt": "State one feature that must be present before calling it.",
          "answer": "Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Cysts.",
          "reasoning": "The learner must commit to an observable morphologic or workflow feature rather than a memorized label."
        },
        {
          "prompt": "Name the closest mimic and the discriminator that separates them.",
          "answer": "usual hyperplasia, reactive change, in situ carcinoma, invasive carcinoma, or treatment effect depending on the path context; separate with architecture plus cytologic atypia, myoepithelial pattern, biomarker context, and whether invasion or concordance changes management.",
          "reasoning": "Contrastive recall strengthens diagnostic discrimination and reduces common overcall/undercall errors."
        },
        {
          "prompt": "Write the report or comment phrase that would matter clinically.",
          "answer": "ER/PR/HER2, myoepithelial stains, margin/synoptic language, or radiology-pathology concordance when relevant",
          "reasoning": "The close of the card must connect recognition to a report, staging, adequacy, ancillary, or safety action."
        }
      ],
      "visualAnchorDraft": {
        "plan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
        "inspectionSequence": [
          "Orient to Breast and specimen context before magnifying.",
          "Find the normal/reactive comparator: Compare against normal terminal duct lobular unit or expected breast stroma/epithelium before labeling the abnormality.",
          "At low power and high power, test the morphology anchor: Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Cysts.",
          "Before sign-out, check the pitfall: missing invasion, overcalling reactive/proliferative change, or omitting biomarker/concordance language that changes care"
        ],
        "assetStatus": "pending licensed/local image or explicit no-image rationale"
      }
    },
    {
      "id": "p0-breast-card-02-2605228a-e2fd-4c25-a6e0-d3ee3ca6e074",
      "sourceQueueId": "ap_breast-2605228a-e2fd-4c25-a6e0-d3ee3ca6e074",
      "editorialStatus": "draft-content-ready-for-review",
      "priority": "P0 core board/sign-out gap",
      "title": "Adenosis",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Adenosis",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 325,
      "learningFrame": "normal-to-abnormal breast foundation",
      "specimenContext": "core biopsy, excision, or reduction mammoplasty specimen with terminal duct lobular unit orientation and radiology correlation when applicable",
      "normalComparatorPrompt": "normal terminal duct lobular unit, duct, lobule, stroma, and myoepithelial layer before lesion-level interpretation",
      "visualAnchorPlan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
      "mimicDiscriminatorPrompt": "benign proliferative change, fibroepithelial lesion, vascular lesion, therapy effect, or invasive carcinoma mimic as appropriate",
      "ancillaryDecisionPrompt": "state whether myoepithelial markers, ER/PR/HER2, or no ancillary testing is appropriate for this teaching target",
      "reportingConsequencePrompt": "safe benign report wording, radiology-pathology concordance, or escalation trigger when morphology is discordant",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Adenosis.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until drafted content, visual inspection plan, retrieval key, and taxonomy scaffold receive faculty QA plus citation/reviewer metadata.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 325; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "ready-for-review",
          "evidence": "Deterministic draft entity card content attached from ABPath path, organ-system profile, mimic/discriminator template, and report-consequence scaffold; requires faculty fact-check before canonical release."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "ready-for-review",
          "evidence": "Visual inspection sequence attached; asset remains pending. Plan: normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "ready-for-review",
          "evidence": "Draft retrieval answer key attached for entity/process, required feature, mimic discriminator, and report consequence; requires faculty review before learner answer reveal is canonical."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 4,
        "missingGates": 1,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 80
      },
      "entityCardDraft": {
        "definition": "Adenosis is treated in this curriculum as an ABPath AP content-specification topic within Diabetic mastopathy; learners should first confirm the specimen context, then decide whether the process is a true entity, pattern, specimen task, or reportable finding.",
        "normalComparator": "Compare against normal terminal duct lobular unit or expected breast stroma/epithelium before labeling the abnormality.",
        "morphologyAnchor": "Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Adenosis.",
        "topMimic": "usual hyperplasia, reactive change, in situ carcinoma, invasive carcinoma, or treatment effect depending on the path context",
        "discriminator": "architecture plus cytologic atypia, myoepithelial pattern, biomarker context, and whether invasion or concordance changes management",
        "ancillaryOrReportingConsequence": "ER/PR/HER2, myoepithelial stains, margin/synoptic language, or radiology-pathology concordance when relevant",
        "safetyPitfall": "missing invasion, overcalling reactive/proliferative change, or omitting biomarker/concordance language that changes care",
        "sourceBasis": "Drafted from ABPath AP content-spec path: Breast > Normal Anatomy and Histology > Diabetic mastopathy > Adenosis. Source line: 325.",
        "scopedDomain": "Breast"
      },
      "retrievalAnswerKey": [
        {
          "prompt": "Before reveal: name the entity or process represented by Adenosis.",
          "answer": "Adenosis; scoped to Diabetic mastopathy in the ABPath AP content specifications.",
          "reasoning": "Start by naming the content-spec target and its organ-system location before adding details."
        },
        {
          "prompt": "State one feature that must be present before calling it.",
          "answer": "Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Adenosis.",
          "reasoning": "The learner must commit to an observable morphologic or workflow feature rather than a memorized label."
        },
        {
          "prompt": "Name the closest mimic and the discriminator that separates them.",
          "answer": "usual hyperplasia, reactive change, in situ carcinoma, invasive carcinoma, or treatment effect depending on the path context; separate with architecture plus cytologic atypia, myoepithelial pattern, biomarker context, and whether invasion or concordance changes management.",
          "reasoning": "Contrastive recall strengthens diagnostic discrimination and reduces common overcall/undercall errors."
        },
        {
          "prompt": "Write the report or comment phrase that would matter clinically.",
          "answer": "ER/PR/HER2, myoepithelial stains, margin/synoptic language, or radiology-pathology concordance when relevant",
          "reasoning": "The close of the card must connect recognition to a report, staging, adequacy, ancillary, or safety action."
        }
      ],
      "visualAnchorDraft": {
        "plan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
        "inspectionSequence": [
          "Orient to Breast and specimen context before magnifying.",
          "Find the normal/reactive comparator: Compare against normal terminal duct lobular unit or expected breast stroma/epithelium before labeling the abnormality.",
          "At low power and high power, test the morphology anchor: Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Adenosis.",
          "Before sign-out, check the pitfall: missing invasion, overcalling reactive/proliferative change, or omitting biomarker/concordance language that changes care"
        ],
        "assetStatus": "pending licensed/local image or explicit no-image rationale"
      }
    },
    {
      "id": "p0-breast-card-03-2a8fcd9a-2b21-4c2c-90de-aed238adba69",
      "sourceQueueId": "ap_breast-2a8fcd9a-2b21-4c2c-90de-aed238adba69",
      "editorialStatus": "draft-content-ready-for-review",
      "priority": "P0 core board/sign-out gap",
      "title": "Hemangioma",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Hemangioma",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 332,
      "learningFrame": "normal-to-abnormal breast foundation",
      "specimenContext": "core biopsy, excision, or reduction mammoplasty specimen with terminal duct lobular unit orientation and radiology correlation when applicable",
      "normalComparatorPrompt": "normal terminal duct lobular unit, duct, lobule, stroma, and myoepithelial layer before lesion-level interpretation",
      "visualAnchorPlan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
      "mimicDiscriminatorPrompt": "benign proliferative change, fibroepithelial lesion, vascular lesion, therapy effect, or invasive carcinoma mimic as appropriate",
      "ancillaryDecisionPrompt": "state whether myoepithelial markers, ER/PR/HER2, or no ancillary testing is appropriate for this teaching target",
      "reportingConsequencePrompt": "safe benign report wording, radiology-pathology concordance, or escalation trigger when morphology is discordant",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Hemangioma.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until drafted content, visual inspection plan, retrieval key, and taxonomy scaffold receive faculty QA plus citation/reviewer metadata.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 332; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "ready-for-review",
          "evidence": "Deterministic draft entity card content attached from ABPath path, organ-system profile, mimic/discriminator template, and report-consequence scaffold; requires faculty fact-check before canonical release."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "ready-for-review",
          "evidence": "Visual inspection sequence attached; asset remains pending. Plan: normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "ready-for-review",
          "evidence": "Draft retrieval answer key attached for entity/process, required feature, mimic discriminator, and report consequence; requires faculty review before learner answer reveal is canonical."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 4,
        "missingGates": 1,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 80
      },
      "entityCardDraft": {
        "definition": "Hemangioma is treated in this curriculum as an ABPath AP content-specification topic within Diabetic mastopathy; learners should first confirm the specimen context, then decide whether the process is a true entity, pattern, specimen task, or reportable finding.",
        "normalComparator": "Compare against normal terminal duct lobular unit or expected breast stroma/epithelium before labeling the abnormality.",
        "morphologyAnchor": "Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Hemangioma.",
        "topMimic": "usual hyperplasia, reactive change, in situ carcinoma, invasive carcinoma, or treatment effect depending on the path context",
        "discriminator": "architecture plus cytologic atypia, myoepithelial pattern, biomarker context, and whether invasion or concordance changes management",
        "ancillaryOrReportingConsequence": "ER/PR/HER2, myoepithelial stains, margin/synoptic language, or radiology-pathology concordance when relevant",
        "safetyPitfall": "missing invasion, overcalling reactive/proliferative change, or omitting biomarker/concordance language that changes care",
        "sourceBasis": "Drafted from ABPath AP content-spec path: Breast > Normal Anatomy and Histology > Diabetic mastopathy > Hemangioma. Source line: 332.",
        "scopedDomain": "Breast"
      },
      "retrievalAnswerKey": [
        {
          "prompt": "Before reveal: name the entity or process represented by Hemangioma.",
          "answer": "Hemangioma; scoped to Diabetic mastopathy in the ABPath AP content specifications.",
          "reasoning": "Start by naming the content-spec target and its organ-system location before adding details."
        },
        {
          "prompt": "State one feature that must be present before calling it.",
          "answer": "Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Hemangioma.",
          "reasoning": "The learner must commit to an observable morphologic or workflow feature rather than a memorized label."
        },
        {
          "prompt": "Name the closest mimic and the discriminator that separates them.",
          "answer": "usual hyperplasia, reactive change, in situ carcinoma, invasive carcinoma, or treatment effect depending on the path context; separate with architecture plus cytologic atypia, myoepithelial pattern, biomarker context, and whether invasion or concordance changes management.",
          "reasoning": "Contrastive recall strengthens diagnostic discrimination and reduces common overcall/undercall errors."
        },
        {
          "prompt": "Write the report or comment phrase that would matter clinically.",
          "answer": "ER/PR/HER2, myoepithelial stains, margin/synoptic language, or radiology-pathology concordance when relevant",
          "reasoning": "The close of the card must connect recognition to a report, staging, adequacy, ancillary, or safety action."
        }
      ],
      "visualAnchorDraft": {
        "plan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
        "inspectionSequence": [
          "Orient to Breast and specimen context before magnifying.",
          "Find the normal/reactive comparator: Compare against normal terminal duct lobular unit or expected breast stroma/epithelium before labeling the abnormality.",
          "At low power and high power, test the morphology anchor: Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Hemangioma.",
          "Before sign-out, check the pitfall: missing invasion, overcalling reactive/proliferative change, or omitting biomarker/concordance language that changes care"
        ],
        "assetStatus": "pending licensed/local image or explicit no-image rationale"
      }
    },
    {
      "id": "p0-breast-card-04-a932fcfa-fe27-4db4-8180-ca7b7289715f",
      "sourceQueueId": "ap_breast-a932fcfa-fe27-4db4-8180-ca7b7289715f",
      "editorialStatus": "draft-content-ready-for-review",
      "priority": "P0 core board/sign-out gap",
      "title": "Leiomyoma",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Leiomyoma",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 333,
      "learningFrame": "normal-to-abnormal breast foundation",
      "specimenContext": "core biopsy, excision, or reduction mammoplasty specimen with terminal duct lobular unit orientation and radiology correlation when applicable",
      "normalComparatorPrompt": "normal terminal duct lobular unit, duct, lobule, stroma, and myoepithelial layer before lesion-level interpretation",
      "visualAnchorPlan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
      "mimicDiscriminatorPrompt": "benign proliferative change, fibroepithelial lesion, vascular lesion, therapy effect, or invasive carcinoma mimic as appropriate",
      "ancillaryDecisionPrompt": "state whether myoepithelial markers, ER/PR/HER2, or no ancillary testing is appropriate for this teaching target",
      "reportingConsequencePrompt": "safe benign report wording, radiology-pathology concordance, or escalation trigger when morphology is discordant",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Leiomyoma.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until drafted content, visual inspection plan, retrieval key, and taxonomy scaffold receive faculty QA plus citation/reviewer metadata.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 333; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "ready-for-review",
          "evidence": "Deterministic draft entity card content attached from ABPath path, organ-system profile, mimic/discriminator template, and report-consequence scaffold; requires faculty fact-check before canonical release."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "ready-for-review",
          "evidence": "Visual inspection sequence attached; asset remains pending. Plan: normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "ready-for-review",
          "evidence": "Draft retrieval answer key attached for entity/process, required feature, mimic discriminator, and report consequence; requires faculty review before learner answer reveal is canonical."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 4,
        "missingGates": 1,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 80
      },
      "entityCardDraft": {
        "definition": "Leiomyoma is treated in this curriculum as an ABPath AP content-specification topic within Diabetic mastopathy; learners should first confirm the specimen context, then decide whether the process is a true entity, pattern, specimen task, or reportable finding.",
        "normalComparator": "Compare against normal terminal duct lobular unit or expected breast stroma/epithelium before labeling the abnormality.",
        "morphologyAnchor": "Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Leiomyoma.",
        "topMimic": "usual hyperplasia, reactive change, in situ carcinoma, invasive carcinoma, or treatment effect depending on the path context",
        "discriminator": "architecture plus cytologic atypia, myoepithelial pattern, biomarker context, and whether invasion or concordance changes management",
        "ancillaryOrReportingConsequence": "ER/PR/HER2, myoepithelial stains, margin/synoptic language, or radiology-pathology concordance when relevant",
        "safetyPitfall": "missing invasion, overcalling reactive/proliferative change, or omitting biomarker/concordance language that changes care",
        "sourceBasis": "Drafted from ABPath AP content-spec path: Breast > Normal Anatomy and Histology > Diabetic mastopathy > Leiomyoma. Source line: 333.",
        "scopedDomain": "Breast"
      },
      "retrievalAnswerKey": [
        {
          "prompt": "Before reveal: name the entity or process represented by Leiomyoma.",
          "answer": "Leiomyoma; scoped to Diabetic mastopathy in the ABPath AP content specifications.",
          "reasoning": "Start by naming the content-spec target and its organ-system location before adding details."
        },
        {
          "prompt": "State one feature that must be present before calling it.",
          "answer": "Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Leiomyoma.",
          "reasoning": "The learner must commit to an observable morphologic or workflow feature rather than a memorized label."
        },
        {
          "prompt": "Name the closest mimic and the discriminator that separates them.",
          "answer": "usual hyperplasia, reactive change, in situ carcinoma, invasive carcinoma, or treatment effect depending on the path context; separate with architecture plus cytologic atypia, myoepithelial pattern, biomarker context, and whether invasion or concordance changes management.",
          "reasoning": "Contrastive recall strengthens diagnostic discrimination and reduces common overcall/undercall errors."
        },
        {
          "prompt": "Write the report or comment phrase that would matter clinically.",
          "answer": "ER/PR/HER2, myoepithelial stains, margin/synoptic language, or radiology-pathology concordance when relevant",
          "reasoning": "The close of the card must connect recognition to a report, staging, adequacy, ancillary, or safety action."
        }
      ],
      "visualAnchorDraft": {
        "plan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
        "inspectionSequence": [
          "Orient to Breast and specimen context before magnifying.",
          "Find the normal/reactive comparator: Compare against normal terminal duct lobular unit or expected breast stroma/epithelium before labeling the abnormality.",
          "At low power and high power, test the morphology anchor: Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Leiomyoma.",
          "Before sign-out, check the pitfall: missing invasion, overcalling reactive/proliferative change, or omitting biomarker/concordance language that changes care"
        ],
        "assetStatus": "pending licensed/local image or explicit no-image rationale"
      }
    },
    {
      "id": "p0-breast-card-05-ba5f6b06-f921-4a8e-9e91-24f117a6bf82",
      "sourceQueueId": "ap_breast-ba5f6b06-f921-4a8e-9e91-24f117a6bf82",
      "editorialStatus": "draft-content-ready-for-review",
      "priority": "P0 core board/sign-out gap",
      "title": "Therapy induced changes",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Therapy induced changes",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 470,
      "learningFrame": "therapy-effect and treatment-history integration",
      "specimenContext": "post-neoadjuvant breast excision or mastectomy with pretreatment diagnosis, treatment history, tumor bed sampling, and nodal context",
      "normalComparatorPrompt": "untreated breast parenchyma and baseline tumor morphology when available",
      "visualAnchorPlan": "tumor bed fibrosis/necrosis/treatment-effect field paired with residual carcinoma or no-residual-disease comparator",
      "mimicDiscriminatorPrompt": "scar, biopsy site change, fat necrosis, prior procedure effect, and residual invasive or in situ carcinoma",
      "ancillaryDecisionPrompt": "connect morphology to residual cancer burden, receptor reassessment when indicated, and synoptic treatment-effect elements",
      "reportingConsequencePrompt": "residual disease, tumor bed dimensions, nodal treatment effect, and management-relevant synoptic language",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Therapy induced changes.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until drafted content, visual inspection plan, retrieval key, and taxonomy scaffold receive faculty QA plus citation/reviewer metadata.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 470; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "ready-for-review",
          "evidence": "Deterministic draft entity card content attached from ABPath path, organ-system profile, mimic/discriminator template, and report-consequence scaffold; requires faculty fact-check before canonical release."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "ready-for-review",
          "evidence": "Visual inspection sequence attached; asset remains pending. Plan: tumor bed fibrosis/necrosis/treatment-effect field paired with residual carcinoma or no-residual-disease comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "ready-for-review",
          "evidence": "Draft retrieval answer key attached for entity/process, required feature, mimic discriminator, and report consequence; requires faculty review before learner answer reveal is canonical."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 4,
        "missingGates": 1,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 80
      },
      "entityCardDraft": {
        "definition": "Therapy induced changes is treated in this curriculum as an ABPath AP content-specification topic within Breast; learners should first confirm the specimen context, then decide whether the process is a true entity, pattern, specimen task, or reportable finding.",
        "normalComparator": "Compare against normal terminal duct lobular unit or expected breast stroma/epithelium before labeling the abnormality.",
        "morphologyAnchor": "Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Therapy induced changes.",
        "topMimic": "usual hyperplasia, reactive change, in situ carcinoma, invasive carcinoma, or treatment effect depending on the path context",
        "discriminator": "architecture plus cytologic atypia, myoepithelial pattern, biomarker context, and whether invasion or concordance changes management",
        "ancillaryOrReportingConsequence": "ER/PR/HER2, myoepithelial stains, margin/synoptic language, or radiology-pathology concordance when relevant",
        "safetyPitfall": "missing invasion, overcalling reactive/proliferative change, or omitting biomarker/concordance language that changes care",
        "sourceBasis": "Drafted from ABPath AP content-spec path: Breast > Therapy induced changes. Source line: 470.",
        "scopedDomain": "Breast"
      },
      "retrievalAnswerKey": [
        {
          "prompt": "Before reveal: name the entity or process represented by Therapy induced changes.",
          "answer": "Therapy induced changes; scoped to Breast in the ABPath AP content specifications.",
          "reasoning": "Start by naming the content-spec target and its organ-system location before adding details."
        },
        {
          "prompt": "State one feature that must be present before calling it.",
          "answer": "Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Therapy induced changes.",
          "reasoning": "The learner must commit to an observable morphologic or workflow feature rather than a memorized label."
        },
        {
          "prompt": "Name the closest mimic and the discriminator that separates them.",
          "answer": "usual hyperplasia, reactive change, in situ carcinoma, invasive carcinoma, or treatment effect depending on the path context; separate with architecture plus cytologic atypia, myoepithelial pattern, biomarker context, and whether invasion or concordance changes management.",
          "reasoning": "Contrastive recall strengthens diagnostic discrimination and reduces common overcall/undercall errors."
        },
        {
          "prompt": "Write the report or comment phrase that would matter clinically.",
          "answer": "ER/PR/HER2, myoepithelial stains, margin/synoptic language, or radiology-pathology concordance when relevant",
          "reasoning": "The close of the card must connect recognition to a report, staging, adequacy, ancillary, or safety action."
        }
      ],
      "visualAnchorDraft": {
        "plan": "tumor bed fibrosis/necrosis/treatment-effect field paired with residual carcinoma or no-residual-disease comparator",
        "inspectionSequence": [
          "Orient to Breast and specimen context before magnifying.",
          "Find the normal/reactive comparator: Compare against normal terminal duct lobular unit or expected breast stroma/epithelium before labeling the abnormality.",
          "At low power and high power, test the morphology anchor: Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Therapy induced changes.",
          "Before sign-out, check the pitfall: missing invasion, overcalling reactive/proliferative change, or omitting biomarker/concordance language that changes care"
        ],
        "assetStatus": "pending licensed/local image or explicit no-image rationale"
      }
    },
    {
      "id": "p0-breast-card-06-fe908fb0-3f26-4218-b27f-15b4d8241a74",
      "sourceQueueId": "ap_breast-fe908fb0-3f26-4218-b27f-15b4d8241a74",
      "editorialStatus": "draft-content-ready-for-review",
      "priority": "P0 core board/sign-out gap",
      "title": "Normal Cytology",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Normal Cytology",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 5722,
      "learningFrame": "breast lesion scaffold",
      "specimenContext": "breast core biopsy, excision, mastectomy, or axillary specimen with imaging target, laterality, size, and clinical history captured before diagnosis",
      "normalComparatorPrompt": "normal terminal duct lobular unit and myoepithelial layer before abnormal architecture or cytology",
      "visualAnchorPlan": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator",
      "mimicDiscriminatorPrompt": "usual ductal hyperplasia, atypia, DCIS, invasive carcinoma, fibroepithelial lesion, vascular lesion, or therapy/procedure effect as appropriate",
      "ancillaryDecisionPrompt": "state the IHC, biomarker, myoepithelial, or molecular test that would be appropriate if any",
      "reportingConsequencePrompt": "diagnostic category, radiology-pathology concordance, excision need, biomarker implication, or synoptic consequence",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Normal Cytology.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until drafted content, visual inspection plan, retrieval key, and taxonomy scaffold receive faculty QA plus citation/reviewer metadata.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 5722; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "ready-for-review",
          "evidence": "Deterministic draft entity card content attached from ABPath path, organ-system profile, mimic/discriminator template, and report-consequence scaffold; requires faculty fact-check before canonical release."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "ready-for-review",
          "evidence": "Visual inspection sequence attached; asset remains pending. Plan: low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "ready-for-review",
          "evidence": "Draft retrieval answer key attached for entity/process, required feature, mimic discriminator, and report consequence; requires faculty review before learner answer reveal is canonical."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 4,
        "missingGates": 1,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 80
      },
      "entityCardDraft": {
        "definition": "Normal Cytology is treated in this curriculum as an ABPath AP content-specification topic within Breast; learners should first confirm the specimen context, then decide whether the process is a true entity, pattern, specimen task, or reportable finding.",
        "normalComparator": "Compare against normal terminal duct lobular unit or expected breast stroma/epithelium before labeling the abnormality.",
        "morphologyAnchor": "Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Normal Cytology.",
        "topMimic": "usual hyperplasia, reactive change, in situ carcinoma, invasive carcinoma, or treatment effect depending on the path context",
        "discriminator": "architecture plus cytologic atypia, myoepithelial pattern, biomarker context, and whether invasion or concordance changes management",
        "ancillaryOrReportingConsequence": "ER/PR/HER2, myoepithelial stains, margin/synoptic language, or radiology-pathology concordance when relevant",
        "safetyPitfall": "missing invasion, overcalling reactive/proliferative change, or omitting biomarker/concordance language that changes care",
        "sourceBasis": "Drafted from ABPath AP content-spec path: Breast > Normal Cytology. Source line: 5722.",
        "scopedDomain": "Breast"
      },
      "retrievalAnswerKey": [
        {
          "prompt": "Before reveal: name the entity or process represented by Normal Cytology.",
          "answer": "Normal Cytology; scoped to Breast in the ABPath AP content specifications.",
          "reasoning": "Start by naming the content-spec target and its organ-system location before adding details."
        },
        {
          "prompt": "State one feature that must be present before calling it.",
          "answer": "Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Normal Cytology.",
          "reasoning": "The learner must commit to an observable morphologic or workflow feature rather than a memorized label."
        },
        {
          "prompt": "Name the closest mimic and the discriminator that separates them.",
          "answer": "usual hyperplasia, reactive change, in situ carcinoma, invasive carcinoma, or treatment effect depending on the path context; separate with architecture plus cytologic atypia, myoepithelial pattern, biomarker context, and whether invasion or concordance changes management.",
          "reasoning": "Contrastive recall strengthens diagnostic discrimination and reduces common overcall/undercall errors."
        },
        {
          "prompt": "Write the report or comment phrase that would matter clinically.",
          "answer": "ER/PR/HER2, myoepithelial stains, margin/synoptic language, or radiology-pathology concordance when relevant",
          "reasoning": "The close of the card must connect recognition to a report, staging, adequacy, ancillary, or safety action."
        }
      ],
      "visualAnchorDraft": {
        "plan": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator",
        "inspectionSequence": [
          "Orient to Breast and specimen context before magnifying.",
          "Find the normal/reactive comparator: Compare against normal terminal duct lobular unit or expected breast stroma/epithelium before labeling the abnormality.",
          "At low power and high power, test the morphology anchor: Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Normal Cytology.",
          "Before sign-out, check the pitfall: missing invasion, overcalling reactive/proliferative change, or omitting biomarker/concordance language that changes care"
        ],
        "assetStatus": "pending licensed/local image or explicit no-image rationale"
      }
    },
    {
      "id": "p0-breast-card-07-807f09d4-89f3-42fd-856e-5be0f851413c",
      "sourceQueueId": "ap_breast-807f09d4-89f3-42fd-856e-5be0f851413c",
      "editorialStatus": "draft-content-ready-for-review",
      "priority": "P0 core board/sign-out gap",
      "title": "Normal Anatomy, History, and Development",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Normal Anatomy, History, and Development",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 17232,
      "learningFrame": "normal-to-abnormal breast foundation",
      "specimenContext": "core biopsy, excision, or reduction mammoplasty specimen with terminal duct lobular unit orientation and radiology correlation when applicable",
      "normalComparatorPrompt": "normal terminal duct lobular unit, duct, lobule, stroma, and myoepithelial layer before lesion-level interpretation",
      "visualAnchorPlan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
      "mimicDiscriminatorPrompt": "benign proliferative change, fibroepithelial lesion, vascular lesion, therapy effect, or invasive carcinoma mimic as appropriate",
      "ancillaryDecisionPrompt": "state whether myoepithelial markers, ER/PR/HER2, or no ancillary testing is appropriate for this teaching target",
      "reportingConsequencePrompt": "safe benign report wording, radiology-pathology concordance, or escalation trigger when morphology is discordant",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Normal Anatomy, History, and Development.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until drafted content, visual inspection plan, retrieval key, and taxonomy scaffold receive faculty QA plus citation/reviewer metadata.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 17232; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "ready-for-review",
          "evidence": "Deterministic draft entity card content attached from ABPath path, organ-system profile, mimic/discriminator template, and report-consequence scaffold; requires faculty fact-check before canonical release."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "ready-for-review",
          "evidence": "Visual inspection sequence attached; asset remains pending. Plan: normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "ready-for-review",
          "evidence": "Draft retrieval answer key attached for entity/process, required feature, mimic discriminator, and report consequence; requires faculty review before learner answer reveal is canonical."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 4,
        "missingGates": 1,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 80
      },
      "entityCardDraft": {
        "definition": "Normal Anatomy, History, and Development is treated in this curriculum as an ABPath AP content-specification topic within Breast; learners should first confirm the specimen context, then decide whether the process is a true entity, pattern, specimen task, or reportable finding.",
        "normalComparator": "Compare against normal terminal duct lobular unit or expected breast stroma/epithelium before labeling the abnormality.",
        "morphologyAnchor": "Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Normal Anatomy, History, and Development.",
        "topMimic": "usual hyperplasia, reactive change, in situ carcinoma, invasive carcinoma, or treatment effect depending on the path context",
        "discriminator": "architecture plus cytologic atypia, myoepithelial pattern, biomarker context, and whether invasion or concordance changes management",
        "ancillaryOrReportingConsequence": "ER/PR/HER2, myoepithelial stains, margin/synoptic language, or radiology-pathology concordance when relevant",
        "safetyPitfall": "missing invasion, overcalling reactive/proliferative change, or omitting biomarker/concordance language that changes care",
        "sourceBasis": "Drafted from ABPath AP content-spec path: Breast > Normal Anatomy, History, and Development. Source line: 17232.",
        "scopedDomain": "Breast"
      },
      "retrievalAnswerKey": [
        {
          "prompt": "Before reveal: name the entity or process represented by Normal Anatomy, History, and Development.",
          "answer": "Normal Anatomy, History, and Development; scoped to Breast in the ABPath AP content specifications.",
          "reasoning": "Start by naming the content-spec target and its organ-system location before adding details."
        },
        {
          "prompt": "State one feature that must be present before calling it.",
          "answer": "Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Normal Anatomy, History, and Development.",
          "reasoning": "The learner must commit to an observable morphologic or workflow feature rather than a memorized label."
        },
        {
          "prompt": "Name the closest mimic and the discriminator that separates them.",
          "answer": "usual hyperplasia, reactive change, in situ carcinoma, invasive carcinoma, or treatment effect depending on the path context; separate with architecture plus cytologic atypia, myoepithelial pattern, biomarker context, and whether invasion or concordance changes management.",
          "reasoning": "Contrastive recall strengthens diagnostic discrimination and reduces common overcall/undercall errors."
        },
        {
          "prompt": "Write the report or comment phrase that would matter clinically.",
          "answer": "ER/PR/HER2, myoepithelial stains, margin/synoptic language, or radiology-pathology concordance when relevant",
          "reasoning": "The close of the card must connect recognition to a report, staging, adequacy, ancillary, or safety action."
        }
      ],
      "visualAnchorDraft": {
        "plan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
        "inspectionSequence": [
          "Orient to Breast and specimen context before magnifying.",
          "Find the normal/reactive comparator: Compare against normal terminal duct lobular unit or expected breast stroma/epithelium before labeling the abnormality.",
          "At low power and high power, test the morphology anchor: Use low-power duct/lobular architecture, epithelial proliferation pattern, stromal response, and high-power cytologic atypia to decide whether the finding fits Normal Anatomy, History, and Development.",
          "Before sign-out, check the pitfall: missing invasion, overcalling reactive/proliferative change, or omitting biomarker/concordance language that changes care"
        ],
        "assetStatus": "pending licensed/local image or explicit no-image rationale"
      }
    }
  ]
} as const;

export type ApP0BreastCard = typeof apP0BreastCardBatch.cards[number];
