// Generated by scripts/generate_ap_p0_breast_cards.cjs. Do not edit by hand.

export const apP0BreastCardBatch = {
  "generatedAt": "2026-05-15T22:35:18.105Z",
  "sourcePlan": "reports/ap_gap_closure_plan.json",
  "sourceQueue": "src/content/competency/apGapClosureQueue.ts",
  "excludedExistingSourceQueueIds": 193,
  "facultyPacketPath": "reports/ap_p0_breast_card_batch_faculty_packet.md",
  "facultyPacketCsvPath": "reports/ap_p0_breast_card_batch_faculty_packet.csv",
  "batchName": "P0 breast entity card batch",
  "batchStrategy": "All available unassigned P0 Breast rows, capped at 24, converted into normal-comparator and concordance-aware draft scaffolds with five readiness gates.",
  "status": "draft breast scaffolds awaiting taxonomy QA, source-backed content, visual anchors, retrieval answer keys, and faculty review metadata",
  "categoryCoverage": {
    "categoryId": "ap_breast",
    "category": "Breast",
    "queueP0Rows": 19,
    "selectedCards": 19
  },
  "batchReadiness": {
    "completedGates": 0,
    "reviewReadyGates": 19,
    "missingGates": 76,
    "totalGates": 95,
    "percentComplete": 0,
    "percentReviewReady": 20
  },
  "readinessLegend": {
    "complete": "Evidence is present and reviewed.",
    "ready-for-review": "Structured scaffold exists and needs breast pathology faculty confirmation.",
    "missing": "Required breast content, asset, source, answer key, or reviewer evidence is not yet attached."
  },
  "cards": [
    {
      "id": "p0-breast-card-01-b82b09fd-c24e-4aec-9ac7-a08c7ab5c109",
      "sourceQueueId": "ap_breast-b82b09fd-c24e-4aec-9ac7-a08c7ab5c109",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Cysts",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Cysts",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 324,
      "learningFrame": "normal-to-abnormal breast foundation",
      "specimenContext": "core biopsy, excision, or reduction mammoplasty specimen with terminal duct lobular unit orientation and radiology correlation when applicable",
      "normalComparatorPrompt": "normal terminal duct lobular unit, duct, lobule, stroma, and myoepithelial layer before lesion-level interpretation",
      "visualAnchorPlan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
      "mimicDiscriminatorPrompt": "benign proliferative change, fibroepithelial lesion, vascular lesion, therapy effect, or invasive carcinoma mimic as appropriate",
      "ancillaryDecisionPrompt": "state whether myoepithelial markers, ER/PR/HER2, or no ancillary testing is appropriate for this teaching target",
      "reportingConsequencePrompt": "safe benign report wording, radiology-pathology concordance, or escalation trigger when morphology is discordant",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Cysts.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 324; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-02-2605228a-e2fd-4c25-a6e0-d3ee3ca6e074",
      "sourceQueueId": "ap_breast-2605228a-e2fd-4c25-a6e0-d3ee3ca6e074",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Adenosis",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Adenosis",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 325,
      "learningFrame": "normal-to-abnormal breast foundation",
      "specimenContext": "core biopsy, excision, or reduction mammoplasty specimen with terminal duct lobular unit orientation and radiology correlation when applicable",
      "normalComparatorPrompt": "normal terminal duct lobular unit, duct, lobule, stroma, and myoepithelial layer before lesion-level interpretation",
      "visualAnchorPlan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
      "mimicDiscriminatorPrompt": "benign proliferative change, fibroepithelial lesion, vascular lesion, therapy effect, or invasive carcinoma mimic as appropriate",
      "ancillaryDecisionPrompt": "state whether myoepithelial markers, ER/PR/HER2, or no ancillary testing is appropriate for this teaching target",
      "reportingConsequencePrompt": "safe benign report wording, radiology-pathology concordance, or escalation trigger when morphology is discordant",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Adenosis.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 325; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-03-2a8fcd9a-2b21-4c2c-90de-aed238adba69",
      "sourceQueueId": "ap_breast-2a8fcd9a-2b21-4c2c-90de-aed238adba69",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Hemangioma",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Hemangioma",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 332,
      "learningFrame": "normal-to-abnormal breast foundation",
      "specimenContext": "core biopsy, excision, or reduction mammoplasty specimen with terminal duct lobular unit orientation and radiology correlation when applicable",
      "normalComparatorPrompt": "normal terminal duct lobular unit, duct, lobule, stroma, and myoepithelial layer before lesion-level interpretation",
      "visualAnchorPlan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
      "mimicDiscriminatorPrompt": "benign proliferative change, fibroepithelial lesion, vascular lesion, therapy effect, or invasive carcinoma mimic as appropriate",
      "ancillaryDecisionPrompt": "state whether myoepithelial markers, ER/PR/HER2, or no ancillary testing is appropriate for this teaching target",
      "reportingConsequencePrompt": "safe benign report wording, radiology-pathology concordance, or escalation trigger when morphology is discordant",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Hemangioma.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 332; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-04-a932fcfa-fe27-4db4-8180-ca7b7289715f",
      "sourceQueueId": "ap_breast-a932fcfa-fe27-4db4-8180-ca7b7289715f",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Leiomyoma",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Normal Anatomy and Histology > Diabetic mastopathy > Leiomyoma",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 333,
      "learningFrame": "normal-to-abnormal breast foundation",
      "specimenContext": "core biopsy, excision, or reduction mammoplasty specimen with terminal duct lobular unit orientation and radiology correlation when applicable",
      "normalComparatorPrompt": "normal terminal duct lobular unit, duct, lobule, stroma, and myoepithelial layer before lesion-level interpretation",
      "visualAnchorPlan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
      "mimicDiscriminatorPrompt": "benign proliferative change, fibroepithelial lesion, vascular lesion, therapy effect, or invasive carcinoma mimic as appropriate",
      "ancillaryDecisionPrompt": "state whether myoepithelial markers, ER/PR/HER2, or no ancillary testing is appropriate for this teaching target",
      "reportingConsequencePrompt": "safe benign report wording, radiology-pathology concordance, or escalation trigger when morphology is discordant",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Leiomyoma.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 333; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-05-ba5f6b06-f921-4a8e-9e91-24f117a6bf82",
      "sourceQueueId": "ap_breast-ba5f6b06-f921-4a8e-9e91-24f117a6bf82",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Therapy induced changes",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Therapy induced changes",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 470,
      "learningFrame": "therapy-effect and treatment-history integration",
      "specimenContext": "post-neoadjuvant breast excision or mastectomy with pretreatment diagnosis, treatment history, tumor bed sampling, and nodal context",
      "normalComparatorPrompt": "untreated breast parenchyma and baseline tumor morphology when available",
      "visualAnchorPlan": "tumor bed fibrosis/necrosis/treatment-effect field paired with residual carcinoma or no-residual-disease comparator",
      "mimicDiscriminatorPrompt": "scar, biopsy site change, fat necrosis, prior procedure effect, and residual invasive or in situ carcinoma",
      "ancillaryDecisionPrompt": "connect morphology to residual cancer burden, receptor reassessment when indicated, and synoptic treatment-effect elements",
      "reportingConsequencePrompt": "residual disease, tumor bed dimensions, nodal treatment effect, and management-relevant synoptic language",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Therapy induced changes.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 470; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "tumor bed fibrosis/necrosis/treatment-effect field paired with residual carcinoma or no-residual-disease comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-06-3a0a1c98-5417-4a39-b0fe-b81ca4cafc2d",
      "sourceQueueId": "ap_breast-3a0a1c98-5417-4a39-b0fe-b81ca4cafc2d",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Drug and Therapy Changes",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Lung Primary > Cerebrospinal Fluid (CSF) > Drug and Therapy Changes",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 4616,
      "learningFrame": "therapy-effect and treatment-history integration",
      "specimenContext": "post-neoadjuvant breast excision or mastectomy with pretreatment diagnosis, treatment history, tumor bed sampling, and nodal context",
      "normalComparatorPrompt": "untreated breast parenchyma and baseline tumor morphology when available",
      "visualAnchorPlan": "tumor bed fibrosis/necrosis/treatment-effect field paired with residual carcinoma or no-residual-disease comparator",
      "mimicDiscriminatorPrompt": "scar, biopsy site change, fat necrosis, prior procedure effect, and residual invasive or in situ carcinoma",
      "ancillaryDecisionPrompt": "connect morphology to residual cancer burden, receptor reassessment when indicated, and synoptic treatment-effect elements",
      "reportingConsequencePrompt": "residual disease, tumor bed dimensions, nodal treatment effect, and management-relevant synoptic language",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Drug and Therapy Changes.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 4616; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "tumor bed fibrosis/necrosis/treatment-effect field paired with residual carcinoma or no-residual-disease comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-07-1021aa23-ea15-4038-861e-7a80e806821d",
      "sourceQueueId": "ap_breast-1021aa23-ea15-4038-861e-7a80e806821d",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Shunt and Foreign Body Reactions",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Lung Primary > Cerebrospinal Fluid (CSF) > Shunt and Foreign Body Reactions",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 4617,
      "learningFrame": "breast lesion scaffold",
      "specimenContext": "breast core biopsy, excision, mastectomy, or axillary specimen with imaging target, laterality, size, and clinical history captured before diagnosis",
      "normalComparatorPrompt": "normal terminal duct lobular unit and myoepithelial layer before abnormal architecture or cytology",
      "visualAnchorPlan": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator",
      "mimicDiscriminatorPrompt": "usual ductal hyperplasia, atypia, DCIS, invasive carcinoma, fibroepithelial lesion, vascular lesion, or therapy/procedure effect as appropriate",
      "ancillaryDecisionPrompt": "state the IHC, biomarker, myoepithelial, or molecular test that would be appropriate if any",
      "reportingConsequencePrompt": "diagnostic category, radiology-pathology concordance, excision need, biomarker implication, or synoptic consequence",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Shunt and Foreign Body Reactions.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 4617; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-08-6bffa019-efd2-4760-8ff0-00dac30a64c5",
      "sourceQueueId": "ap_breast-6bffa019-efd2-4760-8ff0-00dac30a64c5",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Reactive Pleocytosis (e.g., Mollaret)",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Lung Primary > Cerebrospinal Fluid (CSF) > Shunt and Foreign Body Reactions > Reactive Pleocytosis (e.g., Mollaret)",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 4618,
      "learningFrame": "breast lesion scaffold",
      "specimenContext": "breast core biopsy, excision, mastectomy, or axillary specimen with imaging target, laterality, size, and clinical history captured before diagnosis",
      "normalComparatorPrompt": "normal terminal duct lobular unit and myoepithelial layer before abnormal architecture or cytology",
      "visualAnchorPlan": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator",
      "mimicDiscriminatorPrompt": "usual ductal hyperplasia, atypia, DCIS, invasive carcinoma, fibroepithelial lesion, vascular lesion, or therapy/procedure effect as appropriate",
      "ancillaryDecisionPrompt": "state the IHC, biomarker, myoepithelial, or molecular test that would be appropriate if any",
      "reportingConsequencePrompt": "diagnostic category, radiology-pathology concordance, excision need, biomarker implication, or synoptic consequence",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Reactive Pleocytosis (e.g., Mollaret).",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 4618; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-09-6b18e9dc-c078-495e-8853-37cb9329dea2",
      "sourceQueueId": "ap_breast-6b18e9dc-c078-495e-8853-37cb9329dea2",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Fungal (e.g., Candida)",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Lung Primary > The Urinary Tract > Fungal (e.g., Candida)",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 4743,
      "learningFrame": "breast lesion scaffold",
      "specimenContext": "breast core biopsy, excision, mastectomy, or axillary specimen with imaging target, laterality, size, and clinical history captured before diagnosis",
      "normalComparatorPrompt": "normal terminal duct lobular unit and myoepithelial layer before abnormal architecture or cytology",
      "visualAnchorPlan": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator",
      "mimicDiscriminatorPrompt": "usual ductal hyperplasia, atypia, DCIS, invasive carcinoma, fibroepithelial lesion, vascular lesion, or therapy/procedure effect as appropriate",
      "ancillaryDecisionPrompt": "state the IHC, biomarker, myoepithelial, or molecular test that would be appropriate if any",
      "reportingConsequencePrompt": "diagnostic category, radiology-pathology concordance, excision need, biomarker implication, or synoptic consequence",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Fungal (e.g., Candida).",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 4743; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-10-7ddcbb0f-8aaa-46f2-b77d-a3e1f31def7d",
      "sourceQueueId": "ap_breast-7ddcbb0f-8aaa-46f2-b77d-a3e1f31def7d",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Parasitic (e.g., Schistosoma)",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Lung Primary > The Urinary Tract > Parasitic (e.g., Schistosoma)",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 4744,
      "learningFrame": "breast lesion scaffold",
      "specimenContext": "breast core biopsy, excision, mastectomy, or axillary specimen with imaging target, laterality, size, and clinical history captured before diagnosis",
      "normalComparatorPrompt": "normal terminal duct lobular unit and myoepithelial layer before abnormal architecture or cytology",
      "visualAnchorPlan": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator",
      "mimicDiscriminatorPrompt": "usual ductal hyperplasia, atypia, DCIS, invasive carcinoma, fibroepithelial lesion, vascular lesion, or therapy/procedure effect as appropriate",
      "ancillaryDecisionPrompt": "state the IHC, biomarker, myoepithelial, or molecular test that would be appropriate if any",
      "reportingConsequencePrompt": "diagnostic category, radiology-pathology concordance, excision need, biomarker implication, or synoptic consequence",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Parasitic (e.g., Schistosoma).",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 4744; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-11-5fa2507f-a7c7-4230-83ad-18c3a342a164",
      "sourceQueueId": "ap_breast-5fa2507f-a7c7-4230-83ad-18c3a342a164",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Viral (e.g., Polyoma)",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Lung Primary > The Urinary Tract > Parasitic (e.g., Schistosoma) > Viral (e.g., Polyoma)",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 4745,
      "learningFrame": "breast lesion scaffold",
      "specimenContext": "breast core biopsy, excision, mastectomy, or axillary specimen with imaging target, laterality, size, and clinical history captured before diagnosis",
      "normalComparatorPrompt": "normal terminal duct lobular unit and myoepithelial layer before abnormal architecture or cytology",
      "visualAnchorPlan": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator",
      "mimicDiscriminatorPrompt": "usual ductal hyperplasia, atypia, DCIS, invasive carcinoma, fibroepithelial lesion, vascular lesion, or therapy/procedure effect as appropriate",
      "ancillaryDecisionPrompt": "state the IHC, biomarker, myoepithelial, or molecular test that would be appropriate if any",
      "reportingConsequencePrompt": "diagnostic category, radiology-pathology concordance, excision need, biomarker implication, or synoptic consequence",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Viral (e.g., Polyoma).",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 4745; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-12-37b48393-6e98-42df-ae1f-af8812b75ecf",
      "sourceQueueId": "ap_breast-37b48393-6e98-42df-ae1f-af8812b75ecf",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Infections",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Lung Primary > Respiratory Exfoliative (Sputum, Brushing, Washing) > Infections",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 4849,
      "learningFrame": "breast lesion scaffold",
      "specimenContext": "breast core biopsy, excision, mastectomy, or axillary specimen with imaging target, laterality, size, and clinical history captured before diagnosis",
      "normalComparatorPrompt": "normal terminal duct lobular unit and myoepithelial layer before abnormal architecture or cytology",
      "visualAnchorPlan": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator",
      "mimicDiscriminatorPrompt": "usual ductal hyperplasia, atypia, DCIS, invasive carcinoma, fibroepithelial lesion, vascular lesion, or therapy/procedure effect as appropriate",
      "ancillaryDecisionPrompt": "state the IHC, biomarker, myoepithelial, or molecular test that would be appropriate if any",
      "reportingConsequencePrompt": "diagnostic category, radiology-pathology concordance, excision need, biomarker implication, or synoptic consequence",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Infections.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 4849; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-13-8164ef68-6102-440f-982c-d5c07a9bbc74",
      "sourceQueueId": "ap_breast-8164ef68-6102-440f-982c-d5c07a9bbc74",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Bacterial / Mycobacterial",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Lung Primary > Respiratory Exfoliative (Sputum, Brushing, Washing) > Bacterial / Mycobacterial",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 4850,
      "learningFrame": "breast lesion scaffold",
      "specimenContext": "breast core biopsy, excision, mastectomy, or axillary specimen with imaging target, laterality, size, and clinical history captured before diagnosis",
      "normalComparatorPrompt": "normal terminal duct lobular unit and myoepithelial layer before abnormal architecture or cytology",
      "visualAnchorPlan": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator",
      "mimicDiscriminatorPrompt": "usual ductal hyperplasia, atypia, DCIS, invasive carcinoma, fibroepithelial lesion, vascular lesion, or therapy/procedure effect as appropriate",
      "ancillaryDecisionPrompt": "state the IHC, biomarker, myoepithelial, or molecular test that would be appropriate if any",
      "reportingConsequencePrompt": "diagnostic category, radiology-pathology concordance, excision need, biomarker implication, or synoptic consequence",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Bacterial / Mycobacterial.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 4850; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-14-c9016898-a487-48e6-be1f-b6f813c7e5b3",
      "sourceQueueId": "ap_breast-c9016898-a487-48e6-be1f-b6f813c7e5b3",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Endoscopic Brushings",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Lung Primary > Esophageal Cytopathology > Endoscopic Brushings",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 5074,
      "learningFrame": "breast lesion scaffold",
      "specimenContext": "breast core biopsy, excision, mastectomy, or axillary specimen with imaging target, laterality, size, and clinical history captured before diagnosis",
      "normalComparatorPrompt": "normal terminal duct lobular unit and myoepithelial layer before abnormal architecture or cytology",
      "visualAnchorPlan": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator",
      "mimicDiscriminatorPrompt": "usual ductal hyperplasia, atypia, DCIS, invasive carcinoma, fibroepithelial lesion, vascular lesion, or therapy/procedure effect as appropriate",
      "ancillaryDecisionPrompt": "state the IHC, biomarker, myoepithelial, or molecular test that would be appropriate if any",
      "reportingConsequencePrompt": "diagnostic category, radiology-pathology concordance, excision need, biomarker implication, or synoptic consequence",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Endoscopic Brushings.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 5074; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-15-90f3726b-a2dc-4b50-a0d2-fbf7c9f34e2f",
      "sourceQueueId": "ap_breast-90f3726b-a2dc-4b50-a0d2-fbf7c9f34e2f",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Indications / Techniques",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Lung Primary > Pancreatic Cytopathology > Indications / Techniques",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 5259,
      "learningFrame": "breast lesion scaffold",
      "specimenContext": "breast core biopsy, excision, mastectomy, or axillary specimen with imaging target, laterality, size, and clinical history captured before diagnosis",
      "normalComparatorPrompt": "normal terminal duct lobular unit and myoepithelial layer before abnormal architecture or cytology",
      "visualAnchorPlan": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator",
      "mimicDiscriminatorPrompt": "usual ductal hyperplasia, atypia, DCIS, invasive carcinoma, fibroepithelial lesion, vascular lesion, or therapy/procedure effect as appropriate",
      "ancillaryDecisionPrompt": "state the IHC, biomarker, myoepithelial, or molecular test that would be appropriate if any",
      "reportingConsequencePrompt": "diagnostic category, radiology-pathology concordance, excision need, biomarker implication, or synoptic consequence",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Indications / Techniques.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 5259; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-16-60c26c37-80e6-487b-a8ba-258ad30bde2f",
      "sourceQueueId": "ap_breast-60c26c37-80e6-487b-a8ba-258ad30bde2f",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Indications for Evaluation",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Lung Primary > Pancreatic Cytopathology > Indications for Evaluation",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 5260,
      "learningFrame": "breast lesion scaffold",
      "specimenContext": "breast core biopsy, excision, mastectomy, or axillary specimen with imaging target, laterality, size, and clinical history captured before diagnosis",
      "normalComparatorPrompt": "normal terminal duct lobular unit and myoepithelial layer before abnormal architecture or cytology",
      "visualAnchorPlan": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator",
      "mimicDiscriminatorPrompt": "usual ductal hyperplasia, atypia, DCIS, invasive carcinoma, fibroepithelial lesion, vascular lesion, or therapy/procedure effect as appropriate",
      "ancillaryDecisionPrompt": "state the IHC, biomarker, myoepithelial, or molecular test that would be appropriate if any",
      "reportingConsequencePrompt": "diagnostic category, radiology-pathology concordance, excision need, biomarker implication, or synoptic consequence",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Indications for Evaluation.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 5260; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-17-a749573e-6763-45b2-bf7f-7092d22f98d4",
      "sourceQueueId": "ap_breast-a749573e-6763-45b2-bf7f-7092d22f98d4",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Epithelial Myoepithelial Carcinoma",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Lung Primary > Salivary Gland FNA > Epithelial Myoepithelial Carcinoma",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 5383,
      "learningFrame": "breast lesion scaffold",
      "specimenContext": "breast core biopsy, excision, mastectomy, or axillary specimen with imaging target, laterality, size, and clinical history captured before diagnosis",
      "normalComparatorPrompt": "normal terminal duct lobular unit and myoepithelial layer before abnormal architecture or cytology",
      "visualAnchorPlan": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator",
      "mimicDiscriminatorPrompt": "usual ductal hyperplasia, atypia, DCIS, invasive carcinoma, fibroepithelial lesion, vascular lesion, or therapy/procedure effect as appropriate",
      "ancillaryDecisionPrompt": "state the IHC, biomarker, myoepithelial, or molecular test that would be appropriate if any",
      "reportingConsequencePrompt": "diagnostic category, radiology-pathology concordance, excision need, biomarker implication, or synoptic consequence",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Epithelial Myoepithelial Carcinoma.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 5383; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-18-fe908fb0-3f26-4218-b27f-15b4d8241a74",
      "sourceQueueId": "ap_breast-fe908fb0-3f26-4218-b27f-15b4d8241a74",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Normal Cytology",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Normal Cytology",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 5722,
      "learningFrame": "breast lesion scaffold",
      "specimenContext": "breast core biopsy, excision, mastectomy, or axillary specimen with imaging target, laterality, size, and clinical history captured before diagnosis",
      "normalComparatorPrompt": "normal terminal duct lobular unit and myoepithelial layer before abnormal architecture or cytology",
      "visualAnchorPlan": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator",
      "mimicDiscriminatorPrompt": "usual ductal hyperplasia, atypia, DCIS, invasive carcinoma, fibroepithelial lesion, vascular lesion, or therapy/procedure effect as appropriate",
      "ancillaryDecisionPrompt": "state the IHC, biomarker, myoepithelial, or molecular test that would be appropriate if any",
      "reportingConsequencePrompt": "diagnostic category, radiology-pathology concordance, excision need, biomarker implication, or synoptic consequence",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Normal Cytology.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 5722; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "low-power breast architecture plus high-power diagnostic feature and normal/reactive comparator"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    },
    {
      "id": "p0-breast-card-19-807f09d4-89f3-42fd-856e-5be0f851413c",
      "sourceQueueId": "ap_breast-807f09d4-89f3-42fd-856e-5be0f851413c",
      "editorialStatus": "draft-scaffold",
      "priority": "P0 core board/sign-out gap",
      "title": "Normal Anatomy, History, and Development",
      "category": "Breast",
      "rotation": "Breast pathology",
      "apSpecPath": "Breast > Normal Anatomy, History, and Development",
      "learnerLevel": "PGY1-PGY2",
      "difficulty": "C",
      "sourceLine": 17232,
      "learningFrame": "normal-to-abnormal breast foundation",
      "specimenContext": "core biopsy, excision, or reduction mammoplasty specimen with terminal duct lobular unit orientation and radiology correlation when applicable",
      "normalComparatorPrompt": "normal terminal duct lobular unit, duct, lobule, stroma, and myoepithelial layer before lesion-level interpretation",
      "visualAnchorPlan": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue",
      "mimicDiscriminatorPrompt": "benign proliferative change, fibroepithelial lesion, vascular lesion, therapy effect, or invasive carcinoma mimic as appropriate",
      "ancillaryDecisionPrompt": "state whether myoepithelial markers, ER/PR/HER2, or no ancillary testing is appropriate for this teaching target",
      "reportingConsequencePrompt": "safe benign report wording, radiology-pathology concordance, or escalation trigger when morphology is discordant",
      "entityCardSections": [
        "Breast taxonomy QA and specimen/radiology context",
        "Definition and scope in one learner-safe sentence",
        "Normal terminal duct lobular unit or myoepithelial comparator before abnormal pattern",
        "Low-power architecture and high-power cytologic or stromal cue",
        "Top mimic and single best discriminator",
        "Ancillary, biomarker, concordance, or synoptic/reporting consequence",
        "Pitfall that could create a clinically meaningful breast-pathology miss"
      ],
      "retrievalPrompts": [
        "Before reveal: identify the breast entity, normal structure, or treatment-related process represented by Normal Anatomy, History, and Development.",
        "State the normal comparator and one feature that must be present before making this call.",
        "Name the closest mimic and the discriminator that separates them.",
        "State the ancillary test, biomarker/synoptic element, or radiology-pathology concordance step that would matter if any.",
        "Write the concise report/comment phrase that would be safe for a junior resident."
      ],
      "spacingSchedule": [
        "same session",
        "1 day",
        "3 days",
        "7 days",
        "21 days"
      ],
      "facultyReviewChecklist": [
        "Taxonomy QA confirms this queue row is a valid breast teaching target or documents correction.",
        "Definition, normal comparator, morphology, mimic, discriminator, consequence, and pitfall are source-backed.",
        "Visual anchor is local/licensed or has an explicit no-image rationale.",
        "Retrieval answer key is faculty-reviewed before learner reveal.",
        "Radiology-pathology concordance, biomarker, myoepithelial, or synoptic implication is handled when relevant."
      ],
      "completionGate": "Not complete until taxonomy QA, source-backed breast content, visual anchor, retrieval answer key, and breast faculty review metadata are all satisfied.",
      "gateStatuses": [
        {
          "id": "taxonomy-qa",
          "label": "Taxonomy QA",
          "status": "ready-for-review",
          "evidence": "Generated from Breast AP specification path at source line 17232; faculty must confirm whether this is an entity, normal structure, treatment effect, or parser artifact."
        },
        {
          "id": "content-authoring",
          "label": "Entity card content",
          "status": "missing",
          "evidence": "Needs source-backed definition, normal comparator, morphology, mimic discriminator, ancillary/reporting consequence, and safety pitfall."
        },
        {
          "id": "visual-anchor",
          "label": "Visual anchor",
          "status": "missing",
          "evidence": "normal breast lobule/duct comparator plus lesion-specific low-power architecture and high-power epithelial/stromal cue"
        },
        {
          "id": "retrieval-key",
          "label": "Retrieval answer key",
          "status": "missing",
          "evidence": "Breast prompt set exists; faculty-reviewed answer key and reveal text are not yet attached."
        },
        {
          "id": "faculty-review",
          "label": "Faculty review",
          "status": "missing",
          "evidence": "Breast faculty reviewer, source citation, image/license status, biomarker/synoptic check when relevant, and last-reviewed date are not yet attached."
        }
      ],
      "readiness": {
        "completedGates": 0,
        "reviewReadyGates": 1,
        "missingGates": 4,
        "totalGates": 5,
        "percentComplete": 0,
        "percentReviewReady": 20
      }
    }
  ]
} as const;

export type ApP0BreastCard = typeof apP0BreastCardBatch.cards[number];
