#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
COORDINATION_URL="${SKI_CORTEX_COORDINATION_URL:-http://127.0.0.1:8765}"
PACKET_PATH="${1:-}"
TEMP_PACKET=""
RESPONSE_PATH="${COORDINATION_CHECKPOINT_RESPONSE:-}"

cleanup() {
  if [[ -n "$TEMP_PACKET" && -f "$TEMP_PACKET" ]]; then
    rm -f "$TEMP_PACKET"
  fi
}
trap cleanup EXIT

cd "$REPO_ROOT"

if [[ -z "$PACKET_PATH" ]]; then
  TEMP_PACKET="$(mktemp /tmp/didactic-coordination-checkpoint.XXXXXX.json)"
  PACKET_PATH="$TEMP_PACKET"
  node - "$PACKET_PATH" <<'NODE'
const { execFileSync } = require("node:child_process");
const { writeFileSync } = require("node:fs");

function git(...args) {
  try {
    return execFileSync("git", args, { encoding: "utf8" }).trim();
  } catch {
    return "unknown";
  }
}

const status = git("status", "--short");
const changedFiles = status
  .split("\n")
  .map((line) => line.trim())
  .filter(Boolean)
  .map((line) => line.slice(3).trim());

const packet = {
  repo: "Didactic_Series",
  branch: git("branch", "--show-current"),
  head: git("rev-parse", "--short", "HEAD"),
  promotion_state: changedFiles.length ? "BRANCHED_UNCOMMITTED" : "LOCAL_ONLY",
  repository_state: changedFiles.length ? "CONTROLLED_DIRTY" : "CLEAN_SYNCED",
  terminal_status: changedFiles.length ? "PARTIAL" : "VALIDATED",
  changed_files: changedFiles,
  checks_run: ["git status --short"],
  guardrails_preserved: [
    "no_external_actions",
    "dashboard_changes_blocked",
    "deployment_blocked",
    "tracked_artifact_refresh_blocked",
  ],
  new_capabilities: ["repo_side_checkpoint_emission"],
  blocked_capabilities: [],
  handoff_to_ski_cortex: "checkpoint_emitted_by_didactic_wrapper",
  coordination_evidence: {
    preflight_wrapper: true,
    checkpoint_wrapper: true,
  },
  required_downstream_changes: [],
  redundancy_check: {
    classification: "NEW_TRANCHE",
    searched_ski_cortex_checkpoint: true,
    searched_repo_state_packet: true,
    notes: "Generated by Didactic Series coordination checkpoint wrapper.",
  },
  next_safe_action: "Review SKI-CORTEX latest checkpoint before the next repo mutation.",
  human_approval_required: false,
};

writeFileSync(process.argv[2], `${JSON.stringify(packet, null, 2)}\n`, "utf8");
NODE
fi

if [[ ! -f "$PACKET_PATH" ]]; then
  echo "Coordination checkpoint packet not found: $PACKET_PATH" >&2
  exit 66
fi

if [[ -z "$RESPONSE_PATH" ]]; then
  RESPONSE_PATH="$(mktemp /tmp/didactic-coordination-checkpoint-response.XXXXXX)"
fi

if ! curl --fail --silent --show-error \
  -H "Content-Type: application/json" \
  --data-binary "@$PACKET_PATH" \
  "$COORDINATION_URL/coordinate/checkpoint" \
  >"$RESPONSE_PATH"; then
  echo "SKI-CORTEX coordination checkpoint endpoint unavailable; checkpoint not emitted." >&2
  exit 75
fi

node - "$RESPONSE_PATH" <<'NODE'
const { readFileSync } = require("node:fs");

const response = JSON.parse(readFileSync(process.argv[2], "utf8"));
console.log(`COORDINATION_CHECKPOINT_STATUS=${response.status}`);
console.log(`COORDINATION_CHECKPOINT_STORED=${response.stored === true}`);
console.log(`COORDINATION_CHECKPOINT_RESPONSE=${process.argv[2]}`);

if (response.status !== "PASS" || response.stored !== true) {
  console.error("SKI-CORTEX coordination checkpoint was rejected.");
  for (const error of response.errors || []) {
    console.error(`- ${error}`);
  }
  process.exit(77);
}
NODE
