#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
COORDINATION_URL="${SKI_CORTEX_COORDINATION_URL:-http://127.0.0.1:8765}"
PACKET_PATH="${1:-}"
TEMP_PACKET=""
RESPONSE_PATH="${COORDINATION_PREFLIGHT_RESPONSE:-}"

cleanup() {
  if [[ -n "$TEMP_PACKET" && -f "$TEMP_PACKET" ]]; then
    rm -f "$TEMP_PACKET"
  fi
}
trap cleanup EXIT

cd "$REPO_ROOT"

if [[ -z "$PACKET_PATH" ]]; then
  TEMP_PACKET="$(mktemp /tmp/didactic-coordination-preflight.XXXXXX.json)"
  PACKET_PATH="$TEMP_PACKET"
  node - "$PACKET_PATH" <<'NODE'
const { execFileSync } = require("node:child_process");
const { writeFileSync } = require("node:fs");

function git(...args) {
  try {
    return execFileSync("git", args, { encoding: "utf8" }).trim();
  } catch {
    return "unknown";
  }
}

const status = git("status", "--short");
const changedFiles = status
  .split("\n")
  .map((line) => line.trim())
  .filter(Boolean)
  .map((line) => line.slice(3).trim());

const packet = {
  repo: "Didactic_Series",
  branch: git("branch", "--show-current"),
  head: git("rev-parse", "--short", "HEAD"),
  promotion_state: "LOCAL_ONLY",
  repository_state: changedFiles.length ? "CONTROLLED_DIRTY" : "CLEAN_SYNCED",
  terminal_status: "NOT_STARTED",
  changed_files: changedFiles,
  checks_run: ["git status --short"],
  guardrails_preserved: [
    "no_external_actions",
    "dashboard_changes_blocked",
    "deployment_blocked",
    "tracked_artifact_refresh_blocked",
  ],
  new_capabilities: [],
  blocked_capabilities: [],
  handoff_to_ski_cortex: "preflight_request",
  coordination_evidence: {
    preflight_wrapper: true,
    checkpoint_wrapper: true,
  },
  required_downstream_changes: [],
  redundancy_check: {
    classification: "NEW_TRANCHE",
    searched_ski_cortex_checkpoint: true,
    searched_repo_state_packet: true,
    notes: "Generated by Didactic Series coordination preflight wrapper.",
  },
  next_safe_action: "Proceed only if SKI-CORTEX coordinate preflight allows the tranche.",
  human_approval_required: false,
};

writeFileSync(process.argv[2], `${JSON.stringify(packet, null, 2)}\n`, "utf8");
NODE
fi

if [[ ! -f "$PACKET_PATH" ]]; then
  echo "Coordination preflight packet not found: $PACKET_PATH" >&2
  exit 66
fi

if [[ -z "$RESPONSE_PATH" ]]; then
  RESPONSE_PATH="$(mktemp /tmp/didactic-coordination-preflight-response.XXXXXX)"
fi

if ! curl --fail --silent --show-error \
  -H "Content-Type: application/json" \
  --data-binary "@$PACKET_PATH" \
  "$COORDINATION_URL/coordinate/preflight" \
  >"$RESPONSE_PATH"; then
  echo "SKI-CORTEX coordination preflight unavailable; blocking by default." >&2
  exit 75
fi

node - "$RESPONSE_PATH" <<'NODE'
const { readFileSync } = require("node:fs");

const response = JSON.parse(readFileSync(process.argv[2], "utf8"));
const classification = response.classification;
const allowed = response.allowed === true;
const blocked = response.blocked === true;
const blockedClassifications = new Set(["BLOCKED", "REDUNDANT", "REQUIRES_HUMAN_APPROVAL"]);

console.log(`COORDINATION_PREFLIGHT_CLASSIFICATION=${classification}`);
console.log(`COORDINATION_PREFLIGHT_ALLOWED=${allowed}`);
console.log(`COORDINATION_PREFLIGHT_RESPONSE=${process.argv[2]}`);

if (blocked || !allowed || blockedClassifications.has(classification)) {
  console.error("SKI-CORTEX coordination preflight blocked this action.");
  for (const reason of response.blocked_reasons || []) {
    console.error(`- ${reason}`);
  }
  process.exit(77);
}
NODE
